### DISCUSSION TITLE
Import CookBook Yaml Files

### DISCUSSION THREAD

**Discussion by enchant97** [mealie-recipes/mealie#1572] [Feature Request]
I would like the ability to import my existing data from CookBook app. Which can export as a zip of yaml files. Example shown below:

## Zip structure

```
export.zip /
    name.yml
    ...
```

## Yaml file

```yaml
name: muffins
servings: 12 servings
source: https://www.example.com
image: https://media.thecookbookapp.com/XXX.jpg
on_favorites: no
favorite: no
prep_time: 20 minutes
cook_time: 20 minutes
other_time: 0 minutes
nutritional_info: |
  Per serving: 
  Calories : 312
  Fat : 14g
  Saturated fat : 6g
  Carbs : 40g
  Sugar : 24g
  Fiber : 1g
  Protein : 6g
  Salt : 0.6g
notes: |
  note text ...
ingredients: |
  140 g golden caster sugar
  175 g soft butter
directions: |
  direction one

  direction two

```

## Other info
Known optional values:

- nutritional_info
- notes

The "directions" has each step separated by a blank newline.

The "source" is either text or a URL.
