### DISCUSSION TITLE
Custom style injection

### DISCUSSION THREAD

**Discussion by mchill** [mealie-recipes/mealie#1722] [Feature Request]
**Before submitting this feature request I have**
- [x] Reviewed the documentation and verified that my feature request isn't already a feature.
- [x] Reviewed the existing feature requests and my feature has not been requested.
- [x] Checked the [tasks tagged](https://github.com/hay-kot/mealie/issues?q=is%3Aissue+is%3Aopen+label%3Atask+) issues and verified my feature is not covered

**Please Describe The Problem To Be Solved**
I use HTML and inline CSS to style my recipe instructions. This has a few limitations:
* No way to keep styles DRY across steps/recipes.
* Some styles are impossible to define inline. For example, you cannot add media queries for responsive layouts.

It would be nice to have an easy way to inject a custom global stylesheet that you can mount into the container.

**(Optional): Suggest A Solution**
I don't have experience with Vue or Nuxt, so unfortunately I don't have any good suggestions. But if you point me in the right direction, I'd be willing to take a go at implementing this.

**Additional Information**
- [ ] If the feature is accepted I'm willing to submit a PR to provide this feature

**Comment by mchill** [comment]
I attached an example of what I'm trying to accomplish. Right now I achieve this using the following workaround:

1. Mount a `custom.css` file in `/app/assets`
    ```css
    @media (max-width: 959px) {
      .step img {
        width: 100%;
        padding-top: 16px;
      }
    }
    
    @media (min-width: 960px) {
      .step {
        display: flex;
        align-items: start;
      }
      .step img {
        width: 30%;
        padding-left: 16px;
      }
    }
    
    .ep {
      color: #48BEA6;
    }
    ```
2. Mount an overridden `run.sh` in `/app`
    ```bash
    # Production entry point for the frontend docker container

    sed -i 's#\[{ src: "~/assets/main.css" }, { src: "~/assets/style-overrides.scss" }\]#[{ src: "~/assets/main.css" }, { src: "~/assets/style-overrides.scss" }, { src: "~/assets/custom.css" }]#' nuxt.config.js
    yarn install
    yarn build
    
    # Web Server
    caddy start --config /app/Caddyfile
    
    # Start Node Application
    yarn start -p 3001
    ````
3. Wrap a step in the `"step"` class
    ```html
    <div class="step">
      <div>
        In a small pot, combine <b>rice</b>, <b>1¼ cups water</b> <span class="ep"><b>(2¼ cups for 4 servings)</b></span>, and a <b>big pinch of salt</b>. Bring to a boil, then cover and reduce heat to low. Cook until rice is tender, 15-20 minutes. Keep covered off heat until ready to serve.
      </div>
      <img src="<url>"></img>
    </div>
    ```

<img width="200" alt="Screen Shot 2022-10-12 at 8 33 02 PM" src="https://user-images.githubusercontent.com/13862873/195473484-b051c8fb-f214-4ff8-ba10-2123a9535849.png"><img width="600" alt="Screen Shot 2022-10-12 at 8 34 12 PM" src="https://user-images.githubusercontent.com/13862873/195473489-fa3497bc-ce3f-43de-8393-c63583114119.png">
