### DISCUSSION TITLE
502 error with Caddy and Mealie

### DISCUSSION THREAD

**Discussion by poperigby** [mealie-recipes/mealie#1791] [Q&A]
Hey, I'm having a bit of trouble with Mealie and Caddy. This is my Docker Compose file:
```yaml
services:
  mealie:
    container_name: mealie
    hostname: mealie
    image: hkotel/mealie:latest
    environment:
      TZ: America/Los_Angeles
      RECIPE_PUBLIC: 'true'
      RECIPE_SHOW_NUTRITION: 'true'
      RECIPE_SHOW_ASSETS: 'true'
      RECIPE_LANDSCAPE_VIEW: 'true'
      RECIPE_DISABLE_COMMENTS: 'false'
      RECIPE_DISABLE_AMOUNT: 'false'
    volumes:
      - data:/app/data
    restart: always
volumes:
  data:
networks:
  default:
    name: reverse_proxy
    external: true
```
`reverse_proxy` is an external network that both Mealie and Caddy are connected to.

This is the relevant part of my Caddyfile:
```
food.haddock.cc { # Mealie
    import auth
    reverse_proxy mealie:9925
}
```

When I navigate to https://food.haddock.cc, I just a get 502 bad gateway error, and this shows up in my Caddy log:
```
{
  "level": "error",
  "ts": 1667173634.9382792,
  "logger": "http.log.error",
  "msg": "dial tcp 172.27.0.7:9925: connect: connection refused",
  "request": {
    "remote_ip": "172.71.150.74",
    "remote_port": "49610",
    "proto": "HTTP/2.0",
    "method": "GET",
    "host": "food.haddock.cc",
    "uri": "/",
    "headers": {
      "Cdn-Loop": [
        "cloudflare"
      ],
      "Cf-Visitor": [
        "{\"scheme\":\"https\"}"
      ],
      "Upgrade-Insecure-Requests": [
        "1"
      ],
      "Cookie": [],
      "Cf-Connecting-Ip": [
        "63.231.52.232"
      ],
      "Accept-Encoding": [
        "gzip"
      ],
      "Cf-Ray": [
        "762808f25d55eb57-SEA"
      ],
      "Accept": [
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
      ],
      "Accept-Language": [
        "en-US,en;q=0.5"
      ],
      "Sec-Fetch-Mode": [
        "navigate"
      ],
      "Sec-Fetch-Site": [
        "cross-site"
      ],
      "X-Forwarded-Proto": [
        "https"
      ],
      "User-Agent": [
        "Mozilla/5.0 (X11; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0"
      ],
      "Priority": [
        "u=1"
      ],
      "Sec-Fetch-Dest": [
        "document"
      ],
      "Cf-Ipcountry": [
        "US"
      ],
      "X-Forwarded-For": [
        "63.231.52.232"
      ]
    },
    "tls": {
      "resumed": false,
      "version": 772,
      "cipher_suite": 4865,
      "proto": "h2",
      "server_name": "food.haddock.cc"
    }
  },
  "duration": 0.000845008,
  "status": 502,
  "err_id": "nrqi5g6ub",
  "err_trace": "reverseproxy.statusError (reverseproxy.go:1271)"
}
```
