### DISCUSSION TITLE
Single Container Feedback

### DISCUSSION THREAD

**Discussion by hay-kot** [mealie-recipes/mealie#1949] [General]
Since [#1948](https://github.com/hay-kot/mealie/pull/1948) we've started publishing an experimental image that merges both the frontend and backend services into a single container image. This image is currently in an experimental state, and should be used with caution. Continued support for this image will be based on user feedback and demand, if you're using this image please let us know how it's working for you.

Note that frontend and backend configurations are both applied to the same container.

```yml
---
version: "3.7"
services:
  mealie-omni:
    image: hkotel/mealie:omni-nightly
    container_name: mealie
    volumes:
      - mealie-data:/app/data/
    environment:
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/Anchorage
      - BASE_URL=https://mealie.yourdomain.com
    restart: always

volumes:
  mealie-data:
    driver: local
```

**Comment by mxkolb30** [comment]
Migrated my existing mealie containers to the new omni image. Worked like a charm. Thanks!

**Reply by y8s** [reply]
What method did you use for migration? the internal backups and migration feature?

**Reply by mxkolb30** [reply]
"Migrated" was perhaps the wrong word. I only updated my docker-compose.yml and kept the same volume.

**Reply by y8s** [reply]
I tried using portainer to copy the whole stack but it didn't keep the volume completely intact (no users came along for some reason) so I did what you said. Updated the docker compose to use just the omni image and removed the API-specific env stuff and it came right up as expected. So much simpler to manage.

**Comment by cullenmcdermott** [comment]
I just set it up and imported my recipes from my 0.5 installation and it seems to work great! The only issue I had was setting the port correctly but I found the right port and it came up just fine after that.

**Comment by itsjustpyro** [comment]
Very interested in this. Just re-setup Mealie on a new Truenas Scale instance and was having issues with the TrueChart for it. 

Decided instead of dealing with that to just try this as a docker image, and happy so far! Just restoring my instance now and hopefully my friends are able to just hop right back in this week!

**Comment by audifan88** [comment]
Just upgraded my old instance from 1.0.3 to 1.0.5/latest then set everything up on the single image container, much easier this way to maintain, thanks for the great recipe book!

**Comment by bartmans** [comment]
Can't seem to make this work. What port does the omni use?

**Reply by shiruken** [reply]
It's not documented explicitly, but it's the [same as the frontend](https://nightly.mealie.io/documentation/getting-started/installation/installation-checklist/#docker-diagram) for the two-container implementation: 3000.

**Reply by bartmans** [reply]
Mmm. I thought frontend is 9925?

Had to add 
ports:
      - "9926:3000"
because 9925 was already taken by existing dual container setup.

Omni is now reachable on :9926. Will check it out further.

**Reply by shiruken** [reply]
9925 is the _host_ port in that example and can be whatever you want. 3000 is the fixed _container_ port.

**Comment by psarossy** [comment]
I've switched to this for my k8s deployment and it makes it both much cleaner and less annoying to set up in several ways.
Ran into the port documentation issue as well, but that's and easy fix.

+1 to maintaining (or switching to) a single container image!

**Comment by shiruken** [comment]
Tested this on my Unraid system using an existing data volume and it seems to have transitioned seamlessly from the two-container setup without issue. Definitely will be the preferred pathway on Unraid since Docker Compose isn't natively supported.

For the record, this was the minimal configuration necessary to get it working:
![Add Container](https://user-images.githubusercontent.com/867617/212752931-4082ae37-ba35-425b-bfb6-fff6a41bb7ce.png)

**Reply by OvernightPancake** [reply]
I just wanted to leave a helpful hint here for anyone like me that struggled to set this up in Unraid:

I had to add the variables 'FRONTEND_PORT' & 'API_PORT' in order to make this run. Make sure that you set these ports to something unused and you should be good to go.
Once logged in, all I had to do was restore the backup from my main Mealie container as a Migration and the recipes moved over.

**Reply by shiruken** [reply]
Interesting. I just re-tested with the exact configuration shown in my screenshot and _did not_ have to specify any additional variables to get it to work. Those two variables also aren't specified in the documentation, are they just local names?

**Reply by OvernightPancake** [reply]
I agree, not sure why it would not work for me as it did for you. I ended up doing some digging in the [Backend Confirguration](https://nightly.mealie.io/documentation/getting-started/installation/backend-config/) documentation for running 2 separate containers and tried those variables. Let me test it again and see if this was just a one-off.

**Reply by OvernightPancake** [reply]
Weird, I've tried it again and got this working without an issue. Perhaps my original issue had something to do with my custom docker networks and port usage. Oh well, 5th times the charm and it now works without the extra variables!

**Reply by ghost** [reply]
Can you share your template from unraid?

**Comment by swaggerino** [comment]
Also gave the omni a try on unraid. Great work! I'm all for a single container.

**Comment by Jefe2** [comment]
This morning I installed this container on my ARM-64 system and migrated from v0.5.6.  Works beautifully so far.  Really appreciate the single-container setup!

**Comment by bentolor** [comment]
Just tried to include this into my setup involving Letsencrypt / ACME-Companion, Nextcloud, and co. You can see the base of my template at https://github.com/bentolor/docker-nextcloud-collabora-postgresql-letsencrypt/

I initially tried to deploy it in a subpath, but then saw the FAQ entry. Eventually I stumbled upon, that the container exposes two ports and the API port is auto-preferred, while the frontend port `3000` was not visible in `docker ps`. 

This snippet eventually seems to work for me in my setup.

```
  mealie-omni:
    image: hkotel/mealie:omni-nightly
    container_name: mealie
    volumes:
      - mealie-data:/app/data/
    networks:
      - proxy-tier
    environment:
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ="Europe/Berlin"
      - BASE_URL=https://MY-DYNDSN-ADDRESS/
      - LETSENCRYPT_HOST=MY-DYNDSN-ADDRESS
      - VIRTUAL_HOST=MY-DYNDSN-ADDRESS
      - VIRTUAL_NETWORK=proxy-tier
      - VIRTUAL_PORT=3000
    restart: always
```
Of course, not to forget to declare the `mealie-data` in the `volumes`-Section.

**Comment by epheterson** [comment]
I tried this and when I load in the browser I just get: `{"detail":"Not Found"}`

I first tried with no data, to restore a backup instead and saw Not Found. Then I tried copying the contents of the docker volume to a new directory and pointing the container to that, also Not Found. Finally I used Portainer to point it to the existing mealie volume, and still Not Found. Not sure what to try next!

**Reply by shiruken** [reply]
Make sure you map port 3000 on the container to the host:

```yaml
ports:
  - 9925:3000
```

**Reply by epheterson** [reply]
Oh thanks, I decided to try loading the image directly and using Synology Docker UI to set up the ENV variables mentioned above. Through that process the default container port was 9000. 

I’ll try this tonight, but looks like the default container config needs to be updated.

**Reply by bartmans** [reply]
See above if you try to install next to existing Mealie, use other port ie 9926

**Reply by epheterson** [reply]
Yup, that works, thanks! 

@hay-kot please make the default config 3000 instead of 9000 for people who use tools that populate the defaults during setup.

@bartmans Yeah I did use a new host port for omni, and also never ran both instances at the same time.

**Comment by Plevuus** [comment]
It works and it works well! I had some trouble assigning the existing volumes to the omni docker, but that is due to my limited docker knowledge. The only issue I found so far is that the 'copy asset' button in the recipe edit window is not working anymore.  I guess that it is not related to omni. I moved from V1.0.0beta5 to the omni-nightly. I really like the 'I made this' button!

**Comment by JvdMaat** [comment]
Very much in favor of a single container setup. To me mealie is a single app. Very few apps I have use multiple containers, and in most cases, the second container is a database or something that really should be externalized.
Can you release an  omni v1.0.0b5.5? Any point in time non-nightly version would do for my purposes of regular home use.

**Comment by CuratorViper** [comment]
Yes please, single container all the way!
Migrated from the dual container to the omni without any issues!

**Comment by fivestones** [comment]
I updated my docker-compose.yml file as shown at the top of this discussion, and just like that, it's working great!

I'm very happy to have this omni container. Thanks!

**Comment by aberlaas** [comment]
Single container has my preference. Working like a charm.

**Comment by modem7** [comment]
Add me as a +1 on using the omni container

**Comment by PeterJT** [comment]
Not sure if it's significant but if I do docker logs mealie_omni I see an error

```
/app/run.sh: 50: [: unexpected operator
yarn run v1.22.19
warning Skipping preferred cache folder "/.cache/yarn" because it is not writable.
warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-1001".
$ nuxt start -p 3000
```
Mind you all does work.

**Comment by Ernie4President** [comment]
Just did a fresh install on a Proxmox LXC virtual -with Docker inside- and all is running smoothly.

Now, I would like the data of Mealie to be written on my NAS. I've tried several options but can't seem to get the hang of it.
I'm using this in the volumes section (trying NFS now instead of SMB):
```
volumes:
  nas:
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.178.133,rw
      device: ":/volume1/proxmox/mealie”
```
I realise this question is probably a bit off-topic....

**Reply by epheterson** [reply]
I also moved my mealie data to a standard path, no longer a docker volume. For a fresh setup just put two paths on this line:
volumes:
      - mealie-data:/app/data/
      
For an existing setup you have to resolve that mealie-data path (I used Portainer to view them), copy the contents to your new directory, then change the directory for the container.

**Reply by Ernie4President** [reply]
Not sure I understand completely. Can you elaborate you remark on ' just put two paths on this line' ?
Forgot to mention I'm learning Proxmox/LCX/Docker/Portainer by trail/error. With the help of google and youtube I've been able to launch a LCX container with Mealie installed. Also I have mounted my NAS to the folder /mnt/nas, so the NAS folder is available in the LCX. Tried to make it work by changing the line:
```
    volumes:
      - mealie-data:/mnt/nas/mealiev1/
```
That doesn't work because this path points to the inside of the docker container -if I understand correctly. 
Not sure how to continue. Can you help?

**Reply by JvdMaat** [reply]
If that is the standard docker-compose format, you would want something like this:
    volumes:
      - /mnt/nas/mealiev1:/app/data
That would map the NFS mounted path to /app/data inside the Mealie container.

**Reply by Ernie4President** [reply]
Why didn't I think of that? Working perfect! Thank you @epheterson and @JvdMaat! You made me very happy 👍 
Really like the fact that the docker container and the data are separated now. 
As suggested by Eric, I was able to move the content from the 'old' docker instance to the NAS.

Again, thanks!

**Reply by mgrimace** [reply]
Hey do you mind sharing how you setup your LXC and your compose file? I'm planning to try the same thing (LXC + mount data on a NAS). Thanks!

**Reply by mgrimace** [reply]
More specifically, if I replace the `mealie-data:/app/data/` with `/mnt/media/recipes:/app/data` I can't login using the default credentials. It works with the default `mealie-data:/app/data/` though, but I'd like for it to be on my NAS.

**Reply by michaelcox12** [reply]
I'm having the same issue, setting the data to be stored on the NAS instead of mealie-data and the default credentials aren't letting me log in

**Comment by CamelT0E** [comment]
Registration of user does not work,
`ALLOW_SIGNUP=true` is enabled.

![grafik](https://user-images.githubusercontent.com/59985723/223750432-cb0ea7e1-d152-4f70-a8fe-9c6236497d64.png)

Show recipes as with the old version without login, there are not in the version?
`RECIPE_PUBLIC=true` is enabled.

Postgres doesn't work with old database. SQLite works fine. Maybe need a clean new database.
Somewhere I also read something with superuser rights in the new version. But I can't find it anymore.

**Reply by bentolor** [reply]
Can confirm. `/register` leads to 404. Worked for my installation in older versions.

**Reply by bartmans** [reply]
Not just omni, my two container nightly also gives 404.

**Reply by hay-kot** [reply]
I think the Nuxt router changed behavior during an upgrade, you can work around this by navigating to `/register/register` until we get it fixed. 

https://demo.mealie.io/register/register

- https://github.com/hay-kot/mealie/issues/2222#issue-1615799321

**Reply by CamelT0E** [reply]
it's fixed with the last version, many thanks!

Is there possibility to view recipes without log in? In the old version this is possible.

**Comment by rgardn12** [comment]
running single container, no issues!

**Comment by roelven** [comment]
Have been running the omni container for about a week now behind a Caddy reverse proxy and with Mailgun as my SMTP server, works like a charm! Extending the docker-compose.yml to get Caddy + Lets Encrypt running was very straightforward.

Here's my docker-compose.yml in case it's interesting:

```
version: "3.7"
services:
  mealie-omni:
    image: hkotel/mealie:omni-nightly
    container_name: mealie
    networks:
      - caddy
    labels:
      caddy: mealie.something.com
      caddy.reverse_proxy: "{{upstreams 3000}}"
    ports:
      - "3000:3000"
      - "9000:9000"
    volumes:
      - mealie-data:/app/data/
    environment:
      - ALLOW_SIGNUP=false
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - BASE_URL=https://mealie.something.com
      - DEFAULT_GROUP="XXXXXX"
      - DEFAULT_EMAIL=XXXXXXX
      # =====================================
      - SMTP_HOST=smtp.mailgun.org
      - SMTP_PORT=587
      - SMTP_FROM_NAME=Mealie
      - SMTP_AUTH_STRATEGY=TLS
      - SMTP_FROM_EMAIL=XXXXXXXXXX
      - SMTP_USER=XXXXXXXXX
      - SMTP_PASSWORD=XXXXXX
    restart: always

networks:
  caddy:
    external: true

volumes:
  mealie-data:
    driver: local

```
