### DISCUSSION TITLE
Database locked when using remote (NAS) volume for config

### DISCUSSION THREAD

**Discussion by mgrimace** [mealie-recipes/mealie#2430] [Q&A]
Hello,

I'm a new user and trying to setup Mealie for the first time. No matter what group name I enter, including random names/digits it gives me the error `group name is taken`. I'm using the single container build with the compose file below. Note I have an SMB/CIFS NAS mounted for the /app/data, and attempted to change the port to 9925 to access the webui since 3000 was already taken by gethomepage.dev. 

Thanks in advance for any help!

```
---
version: "3.7"
services:
  mealie-omni:
    image: hkotel/mealie:omni-nightly
    container_name: mealie
    ports:
      - 9925:3000
      - 9924:9000
    volumes:
      - /mnt/media/media/recipes:/app/data/
    environment:
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - BASE_URL=https://mealie.mydomain.com
    networks:
      - homelab
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined

networks:
  homelab:
    driver: bridge
    external: true
```
