### DISCUSSION TITLE
Absolute simplest docker compose setup for complete idiots?

### DISCUSSION THREAD

**Discussion by bee-san** [mealie-recipes/mealie#2491] [General]
I'm trying to set up https://nightly.mealie.io/documentation/getting-started/installation/postgres/ but I am too dumb to understand much of this.

I changed the URL to `127.0.0.1` and it's not working:

```
---
version: "3.7"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-5
    container_name: mealie-frontend
    depends_on:
      - mealie-api
    environment:
    # Set Frontend ENV Variables Here
      - API_URL=http://127.0.0.1:9000 # 
    restart: always
    ports:
      - "9925:3000" # 
    volumes:
      - mealie-data:/app/data/ # 
  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-5
    container_name: mealie-api
    deploy:
      resources:
        limits:
          memory: 1000M # 
    depends_on:
      - postgres
    volumes:
      - mealie-data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/Anchorage
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=http://127.0.0.1

    # Database Settings
      - DB_ENGINE=postgres
      - POSTGRES_USER=mealie
      - POSTGRES_PASSWORD=mealie
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mealie
    restart: always
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ./mealie-pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mealie
      POSTGRES_USER: mealie

volumes:
  mealie-data:
    driver: local
  mealie-pgdata:
    driver: local
```

Here's my errors:

```
$ nuxt start -p 3001
ℹ [HPM] Proxy created: api  -> http://127.0.0.1:9000
ℹ [HPM] Proxy rewrite rule created: "api" ~> "/api"
ℹ [HPM] Proxy created: /api  -> http://127.0.0.1:9000
ℹ Listening on: http://XXXXXX:3001/

 ERROR  connect ECONNREFUSED 127.0.0.1:9000

  at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)


 ERROR  connect ECONNREFUSED 127.0.0.1:9000

  at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
```

Can anyone help me out? I just want to run this without thinking too hard :) 

Thank you.

**Comment by michaelcox12** [comment]
Same here. I would love to have instructions on setting up Mealie 1.0 "for dummies." I can get the 0.5 version running no problems but I can't work through how to do a simple install of 1.0 in Portainer

**Comment by hay-kot** [comment]
> I changed the URL to 127.0.0.1 and it's not working:

You don't need to change this. Put it back to what it was, and it should work.

**Comment by chagwood** [comment]
Same experience for me. Tried the app out the other day from docker with latest tag. Worked great. Wanted the latest version. Had a rough time figuring out what to do. Still haven't stood up the new one.

**Comment by AlstonChan** [comment]
I also have similar error, and when run the container again without detached mode, the postgres container is spitting out error like - password authentication failed for user "mealie", which I dont have much idea why as I did not change the default env.

**Comment by mrfenyx** [comment]
This works for me. I am using Portainer for deployment of the stack and running Docker on a Synology NAS. This should only affect your volume mapping though.

```
version: "3.7"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-nightly
    container_name: mealie-frontend
    restart: always
    ports:
      - 9925:3000
    environment:
      - API_URL=http://mealie-api:9000
    volumes:
      - /volume1/docker/mealie:/app/data/
  mealie-api:
    image: hkotel/mealie:api-nightly
    container_name: mealie-api
    volumes:
      - /volume1/docker/mealie:/app/data/
    environment:
      - ALLOW_SIGNUP=true
      - PUID=1026
      - PGID=100
      - TZ=Europe/Berlin
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=<your_BASE_url e.g. host_IP:mapped_PORT>
    restart: always

volumes:
  mealie-data:
    driver: local
```
