### DISCUSSION TITLE
Sync food itmes

### DISCUSSION THREAD

**Discussion by LeaderbotX400** [mealie-recipes/mealie#2721] [Feature Request]
### First Check

- [X] I used the GitHub search to find a similar requests and didn't find it.
- [X] Checked the [tasks tagged](https://github.com/hay-kot/mealie/issues?q=is%3Aissue+is%3Aopen+label%3Atask+) issues and verified my feature is not covered

### Please provide a concise description of the problem that would be addressed by this feature.

It's annoying, though not to a degree where it's a deal breaker. When one admin creates an ingredient, it is not visible to everyone else in the group.

### Please provide a concise description of the feature that would resolve your issue.

A toggle or have the default behavior for all items created to be synchronized within a group (e.g. if I add red pepper flakes, they should be available to all users when making a recipe)

### Please consider and list out some caveats or tradeoffs made in your design decision

Unknown at this time

### Additional Information

- [ ] If this is accepted I'm willing to submit a PR to provide this feature
- [ ] If this is accepted I'm willing to help maintain this feature
- [ ] I'm willing to sponsor/pay a developer to do this work

**Comment by michael-genson** [comment]
Can you post your deployment details, along with an example of what you're seeing? What you're describing is expected behavior within a single group

**Comment by LeaderbotX400** [comment]
Interesting. Once I made a test group and some accounts to validate this, it works exactly as you explained

Likely a non-issue and I just need my users to refresh, or logout then log back in

Docker compose
```yaml
version: '3.9'

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:nightly
    container_name: mealie
    ports:
        - "9925:9000" # 
    deploy:
      resources:
        limits:
          memory: 2048M # 
    volumes:
      - mealie-data:/app/data/
    labels:
      traefik.enable: true
      traefik.http.routers.mealie.rule: Host(`meals.<mydomain>.<tld>`) || Host(`recipes.<mydomain>.<tld>`)
      traefik.http.services.mealie.loadbalancer.server.port: 9925
    environment:
    # Set Backend ENV Variables Here
      - PUID=1000
      - PGID=1000
      - TZ=ETC/UTC
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://meals.<mydomain>.<tld>
      - ALLOW_SIGNUP=false
    restart: always

volumes:
  mealie-data:
    driver: local
```
