### DISCUSSION TITLE
Mealie Scraping drives me crazy

### DISCUSSION THREAD

**Discussion by incoggnito** [mealie-recipes/mealie#2856] [Show and tell]
I am currently on the same version as the mealie demo site. The scraping for the recipes works there. On my server it only works sporadically. I connect to the docker container and execute the scraping command manually:

`asyncio.run(scraper_strategies.safe_scrape_html("https://eat.de/rezept/vegetarische-enchiladas/"))`

Sometimes everything works immediately and sometimes I get a timeout. I suspect my firewall or the network, but can't find anything. I have already tried tcpdump and the firewall logs. What do you think?

**Comment by boc-the-git** [comment]
Please provide your docker-compose file, redacting any sensitive details.

You have other containers running similarly, without issues?

The discord could be the best place to get more timely responses.

**Reply by incoggnito** [reply]
```
---
version: "3.7"
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:nightly
    container_name: mealie
    ports:
        - "9925:9000" #
    deploy:
      resources:
        limits:
          memory: 1500M #
    volumes:
      - mealie-data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=false
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - MAX_WORKERS=2
      - WEB_CONCURRENCY=2
      - WEB_GUNICORN=true
      - BASE_URL=https://sub.domain.vip
    restart: always

volumes:
  mealie-data:
    driver: local
```
I have no other containers running. I usually split everything into lxc containers on my proxmox servers. I would like to avoid docker, but it's seems not the best way for deploying mealie.

I will check the discord server later on. Thank you :)
