### DISCUSSION TITLE
Setting the SMTP_PASSWORD with docker compose secrets

### DISCUSSION THREAD

**Discussion by Weizenritter** [mealie-recipes/mealie#3291] [Q&A] [answered]
Hey there. Since I like checking in all my configs I like them to be free of secrets in clear text. I wonder if it's possible to provide the value of the variable SMTP_PASSWORD with an docker compose secret. Here an example of what I would imagine:
```yaml
---
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.3.2
    container_name: mealie
    ports:
      - "9925:9000"
    volumes:
      - ./mealie_data:/etc/mealie/data
    environment:
      - TZ=Europe/Berlin
      - BASE_URL=https://mealie.example.com
      - SMTP_AUTH_STRATEGY=TLS
      - SMTP_FROM_EMAIL=user@example.com
      - SMTP_HOST=smtp.example.com
      - SMTP_PASSWORD_FILE=/run/secrets/smtp_password  # <-- Look here
      - SMTP_PORT=587
      - SMTP_USER=user@example.com
    secrets:
      - source: smtp_password
secrets:
  smtp_password:
    name: my_smtp_password
    file: /path/to/smtp_password
```

Note the `_FILE` suffix, it's a convention that some official images implement, as stated in the [documentation of docker compose](https://docs.docker.com/compose/use-secrets) (scroll to the bottom for the note).

If it's possible in some other way I'd like to here how, thanks in advance!
