### DISCUSSION TITLE
OAuth setup with Keycloak

### DISCUSSION THREAD

**Discussion by garbast** [mealie-recipes/mealie#3428] [OAuth Provider Example]
### Configuration Example

I'm trying to use Keycloak as login provider in Mealie. For that i have tinkered around with some environment settings, but cant get it running. Could someone help?

```
docker-compose.yaml
services:
  mealie:
    environment:
      #OpenID Connect
      - OIDC_AUTH_ENABLED=true
      - OIDC_CONFIGURATION_URL=https://<domain>/realms/family/.well-known/openid-configuration
      - OIDC_CLIENT_ID=mealie
      - OIDC_USER_GROUP=50fb10ba-d22d-4540-a561-195e5fc3ba16
      - OIDC_AUTO_REDIRECT=false
      - OIDC_PROVIDER_NAME=SSO
```
In Keycloak i use (i skipped the url block, because that only contains https://<domain>/ and alike):

Client ID: mealie
Client authentication: on
Authorization: on
Authentication flow: standard low and direkt access grants

What do i miss?

**Comment by guillomep** [comment]
I got an error too saying "invalid scope" on mealie side and "Invalid value for parameter: scope"

**Reply by cmintey** [reply]
Does Keycloak not tell you what the invalid scope value is? These are the scopes that should be configured in Keycloak: `openid profile email groups`. 

There was someone on Discord setting up for Keycloak and said they needed a custom mapper for groups. Maybe this thread would help: https://discord.com/channels/795445547577770014/795489625803849740/1219618707953946686

**Reply by stephanvierkant** [reply]
Can you share the solution here? I've got the same problem, but that link doesn't seem to work.

**Reply by VincentSC** [reply]
Since I did not find a clear explanation in this discussion, I'm sharing what I did to get Mealie working with Keycloak.

The first problem is that Keycloak does not have a scope or mapper for `groups`, and needs to be manually added. Source is: https://shaaf.dev/keycloak-tutorial/6-usergroups/

The second problem is PKCE. That's the easy problem to fix.

# Create a groups scope

## Step 1: A new client scope

Create a new "client scope" called "groups". Make it "default" if you want it in all your OpenID clients, or "optional" when not. I'm picking default, as I probably want to try to get everything on groups.
![image](https://github.com/user-attachments/assets/6ffb3701-eee2-4ffe-84d7-d15a358971ab)

## step 2: mappers

Then you need two mappers. That's the second tab

The first is a "Group Membership" configuration. Click on `Add Mapper` -> `By Configuration` -> `Group Membership`. Then map `groups` to ` groups`, like this:
- Name: groups
- Token Claim Name: groups

![image](https://github.com/user-attachments/assets/ca3d393c-e385-4e0e-90ae-65c2e0c11318)

The second is a "User Attribute" configuration, where you map `user_type` to `user_type`:
- Name: user_type
- User Attribute: user_type
- Token Claim Name: user_type

![image](https://github.com/user-attachments/assets/2ff8c6a2-0023-4f76-aaa3-41932ed57d93)

# Important last step!
As you probably have made the client "mealie" already, you need to add the _now_ default Client Scope "groups". So go to the tab "Client scopes", click on "add" and there you will see "groups".

# PKCE

Turn on client authentication, leave authorization off. You don't need "Service accounts roles". Like this:

![image](https://github.com/user-attachments/assets/4fd57232-f8fe-4a8b-a49a-a3ac10d869dd)

The only thing you need to do, is:
- go to tab "Advanced"
- scroll down to "Proof Key for Code Exchange Code Challenge Method"
- put that to "S256".

# Other stuff

Now a bit about groups. You see it starts with a `/` - that's correct, and no need to use the hash. This is because it's a directory of sub-groups. So you can have `/family` for users and `/family/old_enough_to_cook` for admins. I see all examples only use root-levels groups, and that's a waste of potential.

For completeness, here are my environment variables:
```
      #OpenID Connect
      - OIDC_AUTH_ENABLED=true
      - OIDC_SIGNUP_ENABLED=true
      - OIDC_CONFIGURATION_URL=https://<keycloak.domain>/auth/realms/master/.well-known/openid-configuration
      - OIDC_CLIENT_ID=mealie
      - OIDC_CLIENT_SECRET=ScrambledEggs
      - OIDC_AUTO_REDIRECT=true
      - OIDC_USER_GROUP=/A
      - OIDC_ADMIN_GROUP=/B
      - OIDC_PROVIDER_NAME=Keycloak
```

**Reply by igbjnI05bF** [reply]
This did work for me, but is this really the intended design of groups within Keycloak? Reading the documentation, and having configured other apps such as Nextcloud, Jellyfin, Grafana, etc, admin and user should be set up as client roles, not groups. Groups are for grouping together multiple client roles, or client roles across multiple clients.

It just seems odd that I now have to have a /mealie-user and /mealie-admin set up directly in the realm group settings. It seems messy and hurts my OCD brain. Wouldn't this be better implemented in clients -> mealie -> roles so that they are contained just to mealie and not globally to the realm? And then add the client scope mapper for mealie-dedicated for client roles?

**Reply by VincentSC** [reply]
Mmm, could be. I just went with the flow here.
I found:
> In Keycloak, Groups are just a collection of users that you can apply roles and attributes to in one place. Roles define a type of user and applications assign permission and access control to roles

So, groups would be more internally. So that means that Mealie-groups should be mapped to KC-roles?

**Reply by igbjnI05bF** [reply]
Yes, I think so. I'm not a developer by any means, but that's the way I'm interpreting it and the way other apps seem to handle it. I think it makes sense that way.

**Reply by igbjnI05bF** [reply]
is it possible to do this currently with keycloak roles? or would something need to be changed in mealie to allow it? i haven't had luck so far trying, not sure if i should keep trying or if it's just not possible at the moment

**Reply by afromanex** [reply]
Yes, to configure roles, you need to remove the forward slashes 
OIDC_USER_GROUP=A
OIDC_ADMIN_GROUP=B

Then in keycloak, you'll need to add A and B roles to your mealie client, 
A and B roles would have to be added to a group or groups assigned to the user 
The groups client scope needs to add your group mapper 
And the groups mapper needs to use the "User Client Role" configuration. 

Using roles assigned to groups adds flexibility to configuration, at the cost of some additional complexity. I personally have mine configured similar to @VincentSC where users are assigned specific groups for app access... It's nice to be able to look at a user's groups and say, "Oh, they have a mealie group, so they have access to mealie"

**Comment by cmintey** [comment]
Set `LOG_LEVEL=DEBUG` in your environment variables for Mealie to get some additional logging. Those logs might point you in the right direction

**Reply by guillomep** [reply]
I manage to get it work by settings the groups scope correctly in Keycloak. But now, I’m getting an infinite loop, with « Invalid username or password » on Mealie but correct authentification on Keycloak

**Reply by cmintey** [reply]
The infinite redirect bug has been fixed on the `nightly` version. Hopefully a new release will come soon if you don't want to switch to it

**Comment by garbast** [comment]
I needed to empty out OIDC_USER_GROUP in the docker environment.

In addition i needed to deactivate the "Client authentication" checkbox in the client settings in Keycloak.

After that i was able to login.

**Comment by guillomep** [comment]
I manage to get things working with keycloak.

I added a client scope "groups" in keycloak with the following configuration:

```yaml
  name: groups
  description: Add groups to token
  protocol: openid-connect
  attributes:
    include.in.token.scope: 'true'
    display.on.consent.screen: 'true'
    gui.order: ''
    consent.screen.text: ''
  protocolMappers:
  - name: groups
    protocol: openid-connect
    protocolMapper: oidc-group-membership-mapper
    consentRequired: false
    config:
      full.path: 'true'
      introspection.token.claim: 'true'
      userinfo.token.claim: 'true'
      multivalued: 'true'
      id.token.claim: 'true'
      access.token.claim: 'true'
      claim.name: groups
```

Then I added a client for mealie:

```yaml
  client_id: mealie
  description: Client use to connect to mealie
  root_url: https://mealie.example.com
  admin_url: https://mealie.example.com
  base_url: https://mealie.example.com/g/home
  surrogate_auth_required: false
  enabled: true
  always_display_in_console: true
  redirectUris:
  - https://mealie.example.com/login?direct=1
  - https://mealie.example.com/login
  webOrigins:
  - https://mealie.example.com
  standard_flow_enabled: true
  implicit_flow_enabled: false
  direct_access_grants_enabled: false
  service_accounts_enabled: false
  public_client: true
  frontchannel_logout: true
  client_authenticator_type: client-secret
  protocol: openid-connect
  defaultClientScopes:
  - profile
  - email
  - groups
  attributes:
    user.info.response.signature.alg: RS256
    post.logout.redirect.uris: https://mealie.example.com/login?direct=1##https://mealie.example.com/login
    oauth2.device.authorization.grant.enabled: 'false'
    access.token.signed.response.alg: RS256
    backchannel.logout.revoke.offline.tokens: 'false'
    use.refresh.tokens: 'true'
    oidc.ciba.grant.enabled: 'false'
    id.token.signed.response.alg: RS256
    backchannel.logout.session.required: 'true'
    client_credentials.use_refresh_token: 'false'
    require.pushed.authorization.requests: 'false'
    tls.client.certificate.bound.access.tokens: 'false'
    authorization.signed.response.alg: RS256
    display.on.consent.screen: 'false'
    pkce.code.challenge.method: S256
    token.response.type.bearer.lower-case: 'false'
```

And finally I have use the following configuration in mealie:

```yaml
    - OIDC_AUTH_ENABLED=true
    - OIDC_SIGNUP_ENABLED=true
    - OIDC_CONFIGURATION_URL=https://keycloak.example.com/realms/example/.well-known/openid-configuration
    - OIDC_CLIENT_ID=mealie
    - OIDC_USER_GROUP=/read
    - OIDC_ADMIN_GROUP=/admin
    - OIDC_SIGNING_ALGORITHM=RS256
```

Beware that since in the scope I enable full path on group mapper I need to add a `/` before group names in mealie.
