### DISCUSSION TITLE
Deploying Mealie Recipe Manager on Fly.io

### DISCUSSION THREAD

**Discussion by Ravio1i** [mealie-recipes/mealie#3436] [Show and tell]
# Deploying Mealie Recipe Manager on Fly.io
 
Today, I'm excited to share my journey with Mealie, a fantastic recipe manager that has become an indispensable part of my digital kitchen. As someone who travels frequently, finding a reliable, cost-effective solution to access my collection of recipes from anywhere was essential. This led me to deploy Mealie on [Fly.io](https://fly.io/) (I'm not getting paid by them 😆), a cloud hosting platform that has offered me a seamless, budget-friendly hosting solution. Let's dive into the process and how you can do it too!

## Deployment

Deploying Mealie on Fly.io is a breeze. With a simple Fly configuration that utilizes the Mealie Docker image, I set up the necessary environment variables without hassle. For those looking to deploy, here's how you can start.

You can either create or let it generate you the `fly.toml`. Using the fly.io [getting started](https://fly.io/docs/apps/launch/) you can then run `fly launch`. Here is an example with mounts so you can ensure that the data is not lost.

```toml
app = '<your-mealie-app-name>'
primary_region = 'ams'

[env]
  ALLOW_SIGNUP = 'false'
  BASE_URL = 'https://<your-mealie-app-name>.fly.dev'
  MAX_WORKERS = '1'
  PGID = '1000'
  PUID = '1000'
  TZ = 'Europe/Berlin'
  WEB_CONCURRENCY = '1'
  SMTP_HOST = "smtp.gmail.com"
  SMTP_PORT = "465"
  SMTP_AUTH_STRATEGY = "SSL"

[[mounts]]
  source = 'mealie'
  destination = '/app/data'

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
```

Use the command below to deploy the Mealie recipe manager using the specified Docker image from the GitHub Container Registry.

```bash
fly deploy --image ghcr.io/mealie-recipes/mealie:v1.4.0
```

## Secrets

Mealie requires certain secrets, e.g for the SMTP server configuration or OIDC. You can set these easily through the `fly secrets` command or via the Fly web interface. My secrets included:

- `SMTP_USER`
- `SMTP_PASSWORD`
- `SMTP_FROM_EMAIL`
- `SMTP_FROM_NAME`

Notably, in my case the SMTP password is an app-specific password, which you can manage through [your Google account settings](https://myaccount.google.com/apppasswords) for enhanced security.

## Updates

When a new version of Mealie is released, simply update the image tag to the new version and redeploy using the same command. Fly.io conveniently uses a canary deployment strategy by default, ensuring smooth transitions between versions.

```bash
fly deploy --image ghcr.io/mealie-recipes/mealie:<someotherversion>
```
