### DISCUSSION TITLE
[OIDC] Authelia redirect giving 404 error. Nothing in logs in either Authelia or Mealia

### DISCUSSION THREAD

**Discussion by JustEnoughDucks** [mealie-recipes/mealie#3450] [Q&A]
Hey, I set up mealie and I love it so far! The only thing I wish is that it could parse recipes from videos for the people who for some reason don't add text recipes ;).

I am trying to integrate it into my existing Authelia SSO via the method described in [#3338](https://github.com/mealie-recipes/mealie/discussions/3338)

I have turned on debug, but I simply get a 404 error when I try to use the SSO and nothing in the logs of either authelia or mealie. I am not sure that it is even reaching the correct auth URL even though all of my other apps reach it fine.

Only thing in the logs (DEBUG: True)

```
04/11/2024
01:35:57 PM
INFO:     192.168.90.1:33902 - "GET /null?protocol=oauth2&response_type=code&access_type&client_id=mealie&redirect_uri=https%3A%2F%2Fmealie.my.website%2Flogin&scope=openid%20profile%20email%20groups&state=9rGH3xuHbq&code_challenge_method=S256&code_challenge=<redacted> HTTP/1.1" 200 OK
04/11/2024
01:35:58 PM
INFO:     192.168.90.1:33902 - "GET /sw.js HTTP/1.1" 304 Not Modified
```

Here is my environment variables for mealie:

```
      # OIDC SSO Variables
      OIDC_AUTH_ENABLED: True
      OIDC_SIGNUP_ENABLED: True
      OIDC_CONFIGURATION_URL: https://authelia.my.website/.well-known/openid-configuration
      OIDC_CLIENT_ID: mealie
      OIDC_PROVIDER_NAME: Authelia
      LOG_LEVEL: DEBUG

```

Here is my authelia config:

```
      - client_id: 'mealie'
        client_name: 'Mealie'
        authorization_policy: 'one_factor'
        redirect_uris:
          - 'https://mealie.my.website/login'
        public: true
        pkce_challenge_method: S256
        grant_types:
          - authorization_code
        scopes:
          - openid
          - profile
          - groups
          - email
```

Inside of mealie then if I manually log it, it detects that everything is set up for OIDC, so I know I'm not _missing_ any setup variables.

Is there anything I can do to further debug this and find the source? Thank you.
