### DISCUSSION TITLE
Authelia Authentication does not work

### DISCUSSION THREAD

**Discussion by cosmadora** [mealie-recipes/mealie#3508] [Q&A] [answered]
Hi, I have a working mealie installation where I can login with local users.
Today I tried to configure Single Sign-On via Authelia. T
he "Login with Authelia" Button is visible on the login screen, and I get correctly redirected to Authelia, can login there and get redirected back to Mealie. But I don't get logged in, i still get the login screen and I can repeat it as long as I wish without any change in behaviour.

I've seen the Guide in https://github.com/mealie-recipes/mealie/discussions/3338, but the configuration doesn't work (https://www.authelia.com/integration/openid-connect/mealie/)

I would appreciate any help <3

Mealie Config:
```yaml
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.5.1
    container_name: mealie
    restart: always
    expose:
      - 9000
    deploy:
      resources:
        limits:
          memory: 500M
    volumes:
      - /opt/mealie/data:/app/data/
    environment:
      ALLOW_SIGNUP: false
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://mealie.example.com

      OIDC_AUTH_ENABLED: true
      OIDC_SIGNUP_ENABLED: true
      OIDC_CONFIGURATION_URL: https://sso.example.com/.well-known/openid-configuration
      OIDC_CLIENT_ID: 'mealie'
      OIDC_USER_GROUP: 'Mealie'
      OIDC_ADMIN_GROUP: 'Mealie-Admin'
      OIDC_AUTO_REDIRECT: false
      OIDC_PROVIDER_NAME: 'Authelia (Single Sign-On)'

      LOG_LEVEL: DEBUG
```

Authelia Config:
```yaml
      - client_id: 'mealie'
        client_name: 'Mealie (https://mealie.example.com)'
        public: true
        authorization_policy: custom_ldap
        pkce_challenge_method: S256
        grant_types:
          - authorization_code
        scopes:
          - openid
          - profile
          - groups
          - email
        redirect_uris:
          - https://mealie.example.com/login
        pre_configured_consent_duration: '1y'
        require_pkce: true
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'none'
```

Mealie Logs during Login:
```
mealie  | INFO     2024-04-22T15:17:11 - [172.18.10.2:0] 200 OK "GET /api/app/about HTTP/1.1"
mealie  | INFO     2024-04-22T15:17:12 - [172.18.10.2:0] 304 Not Modified "GET /sw.js HTTP/1.1"
mealie  | INFO     2024-04-22T15:17:13 - [172.18.10.2:0] 307 Temporary Redirect "GET /login?code=authelia_ac_<...>&iss=https%3A%2F%2Fsso.example.com&scope=openid+profile+email+groups&state=Kbya7Yyw7G HTTP/1.1"
mealie  | INFO     2024-04-22T15:17:13 - [172.18.10.2:0] 200 OK "GET /login/?code=authelia_ac_<...>&iss=https%3A%2F%2Fsso.example.com&scope=openid+profile+email+groups&state=Kbya7Yyw7G HTTP/1.1"
mealie  | INFO     2024-04-22T15:17:14 - [172.18.10.2:0] 304 Not Modified "GET /sw.js HTTP/1.1"
mealie  | INFO     2024-04-22T15:17:14 - [172.18.10.2:0] 200 OK "GET /api/app/about/startup-info HTTP/1.1"
```
