### DISCUSSION TITLE
Mealie starts, stops and restart in loop

### DISCUSSION THREAD

**Discussion by nocrack21** [mealie-recipes/mealie#3934] [Q&A]
Hi folks,

Just tried installing mealie on an RPI4. I am not managing to run mealie properly using docker compose and your instructions.
After starting it, running `docker compose top` I get this error
`Error response from daemon: Container 65b7abf855d953a8de9cdcbe35cfd237645b561eee4cb741fc4ad90853cd2699 is restarting, wait until the container is running`
Docker log mealie or `docker compose log mealie` are blank so I am not sure where else I can provide log from

yaml file is box standard using your sqlite version and only adding the plarform tag othewise docker was throwing an error trying to pull the wrong code base

```
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    platform: linux/arm64
    container_name: mealie
    restart: always
    ports:
        - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: true
      PUID: 1000
      PGID: 1000
      TZ: Australia/Sydney
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://192.168.1.3

volumes:
  mealie-data:
```

Running docker 27.0.3 and a homeassistant container fine
kernel Linux 6.1.21-v8+ aarch64
Distro Raspbian GNU/Linux 11 (bullseye)

Thanks for your help!
