### DISCUSSION TITLE
Questions

### DISCUSSION THREAD

**Discussion by mpetcuRO** [mealie-recipes/mealie#3998] [General]
Hello, I'm new to Mealie but old Home Assistant user, previously I used an scrips and templates in HA to give me a random meal every day.

My questions are:
- Is there an auto random picker in Mealie? (every day to pick an random meal based on the rules made no need for me to go to meal planner and push random)
- how can I get a link to todays meal recipe? (to use it in HA when you click on the picture entity that shows today meal)
- is there an way to get a sensor for the side dish? (same as we get in HA the today meal sensor and meal ID for the picture, I use the side for the salad and want to have in shown in HA)

**Comment by michael-genson** [comment]
I haven't done too much looking at integrating HA and Mealie, but you should be able to create random meals and get a link to today's recipe using the API. Check out `https://your-mealie-url/docs`. For instance, on the demo:

[Create random meal](https://demo.mealie.io/docs#/Groups%3A%20Mealplans/create_random_meal_api_groups_mealplans_random_post)

[Get today's meals](https://demo.mealie.io/docs#/Groups%3A%20Mealplans/get_todays_meals_api_groups_mealplans_today_get)

**Reply by ghuser238490** [reply]
Hi @mpetcuRO , 
maybe you want to check out the Home Assistant Mealie integration, which got many new features together with the HA 2024.8 update:
[https://www.home-assistant.io/integrations/mealie](https://www.home-assistant.io/integrations/mealie)

**Reply by mpetcuRO** [reply]
Thanks, I have updated HA to 2024.8 and the integration got some love and now has service calls, based on them I was able to create an automation that dos two of my questions.
Still can't figure out how to get an URL link for today meal recipe so i can link it to the HA lovelance (for easy access of today's meal from HA)

Automation to do the following:
- push a random pick for every dimmer and side dish if there are none planned for that day (if you pick it manually then respects your chose and dos not generate other meals)
- get's the today meal ID for the camera entity so you can get the link for the today meal picture (removes the need to create sensors in configuration.yaml
- get's today "dinner" and "side"  to an input text for easy showing in HA lovelance interface.
- sends a notification to mobile with dinner and side dish.

Automation code:
`alias: Mealie - Random Dinner
description: ""
trigger:
  - platform: time
    at: "07:00:00"
condition:
  - condition: state
    entity_id: input_boolean.meal_rec
    state: "on"
action:
  - if:
      - condition: state
        entity_id: calendar.mealie_dinner
        state: "off"
    then:
      - action: mealie.set_random_mealplan
        metadata: {}
        data:
          entry_type: dinner
          date: "{{ strptime(states('sensor.date'), '%Y-%m-%d') }}"
  - if:
      - condition: state
        entity_id: calendar.mealie_side
        state: "off"
    then:
      - action: mealie.set_random_mealplan
        metadata: {}
        data:
          entry_type: side
          date: "{{ strptime(states('sensor.date'), '%Y-%m-%d') }}"
  - action: mealie.get_mealplan
    metadata: {}
    data:
      start_date: "{{ strptime(states('sensor.date'), '%Y-%m-%d') }}"
    response_variable: result
  - action: input_text.set_value
    metadata: {}
    data:
      value: >-
        {% for meal in result.mealplan if meal.entry_type == "dinner" -%} {{
        meal.recipe['recipe_id'] if meal.recipe is not none else meal.title -}}
        {{ ", " if not loop.last }} {%- endfor %}
    target:
      entity_id: input_text.mealie_today_id_txt
  - action: input_text.set_value
    metadata: {}
    data:
      value: >-
        {% for meal in result.mealplan if meal.entry_type == "dinner" -%} {{
        meal.recipe['name'] if meal.recipe is not none else meal.title -}} {{ ",
        " if not loop.last }} {%- endfor %}, {% for meal in result.mealplan if
        meal.entry_type == "side" -%} {{ meal.recipe['name'] if meal.recipe is
        not none else meal.title -}} {{ ", " if not loop.last }} {%- endfor %}
    target:
      entity_id: input_text.mealie_today_meal_txt
  - action: notify.notify_marius
    metadata: {}
    data:
      title: Home Assistant
      message: >-
        Dinner: {% for meal in result.mealplan if meal.entry_type == "dinner"
        -%} {{ meal.recipe['name'] if meal.recipe is not none else meal.title
        -}} {{ ", " if not loop.last }} {%- endfor %}, Side: {% for meal in
        result.mealplan if meal.entry_type == "side" -%} {{ meal.recipe['name']
        if meal.recipe is not none else meal.title -}} {{ ", " if not loop.last
        }} {%- endfor %}
mode: single
`

**Reply by ghuser238490** [reply]
> Still can't figure out how to get an URL link for today meal recipe so i can link it to the HA lovelance (for easy access of today's meal from HA)

I'm no expert in yaml but I think you are very close, because the service `mealie.get_mealplan` returns the recipe slug as well. 
Just add your server address and the group name and you get the recipe url. 

Assuming your group name is 'home' and there's only one dinner entry in the daily mealplan:

```
platform:
  - trigger:
      - platform: time_pattern
        minutes: /1
    action:
      - action: mealie.get_mealplan
        data:
          config_entry_id: YOUR_MEALIE_CONFIG_ENTITY_ID
        response_variable: result
    sensor:
      - name: "Dinner today URL"
        unique_id: mealie_dinner_today_url
        state: >
          {% for meal in result.mealplan if meal.entry_type == "dinner" -%}
          https://your-server.com/g/home/r/{{ meal.recipe['slug']  }}
          {%- endfor %}
```

You can get your config_entry_id by using actions within [Developer Tools](https://www.home-assistant.io/docs/tools/dev-tools/), using the above action and viewing the YAML.

You can use this sensor in a lovelace markdown card, for example:

```
type: markdown
[Today's dinner]({{states('sensor.dinner_today')}})
```

**Reply by mpetcuRO** [reply]
Thank you ghuser238490 did not realize that the "slug" is the actual path of the URL.
Unfortunately the picture entity dos not allow templating in HA so I'm force to display it with the markdown
I added the your code to my automation, here it is if someone will need it.

```
alias: Mealie - Random Dinner
description: "Get random dinner and side if not manualy setup, get "
trigger:
  - platform: time
    at: "07:00:00"
condition:
  - condition: state
    entity_id: input_boolean.meal_rec
    state: "on"
action:
  - if:
      - condition: state
        entity_id: calendar.mealie_dinner
        state: "off"
    then:
      - action: mealie.set_random_mealplan
        metadata: {}
        data:
          config_entry_id: 01J3MP2CP8YYF97N66F7GTFRK0
          entry_type: dinner
          date: "{{ now().timestamp() | timestamp_custom('%Y-%m-%d') }}"
  - if:
      - condition: state
        entity_id: calendar.mealie_side
        state: "off"
    then:
      - action: mealie.set_random_mealplan
        metadata: {}
        data:
          config_entry_id: 01J3MP2CP8YYF97N66F7GTFRK0
          entry_type: side
          date: "{{ now().timestamp() | timestamp_custom('%Y-%m-%d') }}"
  - action: input_text.set_value
    metadata: {}
    data:
      value: ""
    target:
      entity_id:
        - input_text.mealie_today_id_txt
        - input_text.mealie_today_slug_txt
        - input_text.mealie_today_meal_txt
    enabled: true
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
    enabled: false
  - action: mealie.get_mealplan
    metadata: {}
    data:
      config_entry_id: 01J3MP2CP8YYF97N66F7GTFRK0
      start_date: "{{ now().timestamp() | timestamp_custom('%Y-%m-%d') }}"
    response_variable: result
  - action: input_text.set_value
    metadata: {}
    data:
      value: >-
        {% for meal in result.mealplan if meal.entry_type == "dinner" -%} {{
        meal.recipe['recipe_id'] if meal.recipe is not none else meal.title -}}
        {{ ", " if not loop.last }} {%- endfor %}
    target:
      entity_id: input_text.mealie_today_id_txt
  - action: input_text.set_value
    metadata: {}
    data:
      value: >-
        Dinner -  {% for meal in result.mealplan if meal.entry_type == "dinner"
        -%} {{ meal.recipe['name'] if meal.recipe is not none else meal.title
        -}} {{ ", " if not loop.last }} {%- endfor %}, Side - {% for meal in
        result.mealplan if meal.entry_type == "side" -%} {{ meal.recipe['name']
        if meal.recipe is not none else meal.title -}} {{ ", " if not loop.last
        }} {%- endfor %}
    target:
      entity_id: input_text.mealie_today_meal_txt
  - action: input_text.set_value
    metadata: {}
    data:
      value: |-
        {% for meal in result.mealplan if meal.entry_type == "dinner" -%}
        {{ meal.recipe['slug']  }}
        {%- endfor %}
    target:
      entity_id: input_text.mealie_today_slug_txt
  - action: notify.notify_marius
    metadata: {}
    data:
      title: Home Assistant
      message: >-
        Dinner: {% for meal in result.mealplan if meal.entry_type == "dinner"
        -%} {{ meal.recipe['name'] if meal.recipe is not none else meal.title
        -}} {{ ", " if not loop.last }} {%- endfor %}, Side: {% for meal in
        result.mealplan if meal.entry_type == "side" -%} {{ meal.recipe['name']
        if meal.recipe is not none else meal.title -}} {{ ", " if not loop.last
        }} {%- endfor %}
mode: single

```
