### DISCUSSION TITLE
Recovering Mealie v0.5.0 database

### DISCUSSION THREAD

**Discussion by bubbishdev** [mealie-recipes/mealie#4099] [Q&A] [answered]
Hi, I am trying to recover a Mealie instance from an old server. All I have are the files from the old server - I can't get docker to start. I have checked the images and the database are good (I can read data in the database).

I found this discussion (#1690) but it doesn't work in my situation.

I tried to create a Mealie `v0.5.0` instance but docker outputs:
```
 x mealie Error manifest unknown
```

Here is the docker compose file:
```
services:
  mealie:
    container_name: mealie
    image: ghcr.io/mealie-recipes/mealie:v0.5.0
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      # Default Recipe Settings
      RECIPE_PUBLIC: 'true'
      RECIPE_SHOW_NUTRITION: 'true'
      RECIPE_SHOW_ASSETS: 'true'
      RECIPE_LANDSCAPE_VIEW: 'true'
      RECIPE_DISABLE_COMMENTS: 'false'
      RECIPE_DISABLE_AMOUNT: 'false'
      # Gunicorn
      # WEB_CONCURRENCY: 2
      # WORKERS_PER_CORE: 0.5
      # MAX_WORKERS: 8
    volumes:
      - ./mealie/data:/app/data
```

Is there a way to manually migrate the data from `v0.5.0` to the latest (`v1.12.0`)?

I can't find where I saved any of the backups.

Please feel free to ask for more information if you need it.
Thank you for your time
