### DISCUSSION TITLE
Backups via Home Assistant Automation

### DISCUSSION THREAD

**Discussion by JoTec2002** [mealie-recipes/mealie#4669] [Show and tell]
This is an alternative to the [n8n Backup guide](https://docs.mealie.io/documentation/community-guide/n8n-backup-automation/) published in the docs. It just uses an Home Assistant installation, which might be more feasible for some people who don’t want another application.

**[!CAUTION] This only automates the backup function, this does not backup your data to anywhere except your local Mealie instance. Please make sure you are backing up your data to an external source.**

1. Create a new Mealie API Key. [Mealie Docs](https://docs.mealie.io/documentation/getting-started/api-usage/)
2. Add to your Home Assistant `secret.yaml`:
```
mealiebearertoken: "Bearer <YOUR_GENERATED_API_KEY>”
```
3. Add needed REST-Commands to your Home Assistant `configuration.yaml`. **Make sure to reboot Home Assistant afterwards**:
```
rest_command:
  run_mealie_backup:
    url: "https://<YOUR_MEALIE_URL>/api/admin/backups"
    method: POST
    headers:
      Authorization: !secret mealiebearertoken
  get_mealie_backups:
    url: "https:// <YOUR_MEALIE_URL>/api/admin/backups"
    method: GET
    headers:
      Authorization: !secret mealiebearertoken
  delete_backup:
    url: "https:// <YOUR_MEALIE_URL>/api/admin/backups/{{ backup_name }}"
    method: DELETE
    headers:
      Authorization: !secret mealiebearertoken
```
5. Create a new Home Assistant Automation. Change Edit Mode to yaml an Insert:
```
alias: Mealie Backup Schedule
description: Schedules Mealie backups and manages backups
triggers:
  - at: "05:00:00"
    trigger: time
conditions: []
actions:
  - alias: Run Mealie Backup
    action: rest_command.run_mealie_backup
    response_variable: run_mealie_backup_response
    data: {}
    enabled: true
  - alias: Get Mealie Backups
    action: rest_command.get_mealie_backups
    response_variable: get_mealie_backups_response
    data: {}
  - if:
      - condition: template
        value_template: "{{ get_mealie_backups_response['status'] == 200 }}"
    then:
      - alias: Parse data
        variables:
          backups: "{{ get_mealie_backups_response['content']['imports'] }}"
          backup_count: "{{ backups|length }}"
          backups_to_delete: "{{backups[7:]}}"
      - repeat:
          sequence:
            - alias: get Last backup
              variables:
                backup_to_delete: "{{ repeat.item.name }}"
            - action: rest_command.delete_backup
              data:
                backup_name: "{{ backup_to_delete }}"
          for_each: "{{backups_to_delete}}"
    else:
      - action: notify.mobile_app_iphone
        data:
          title: Could not Get Mealie Backups
          message: "HTTP code: {{ get_mealie_backups_response['returncode'] }}"
mode: single
```
This will trigger a Backup in Mealie at 5AM and will keep the last 7 Backups.
