### DISCUSSION TITLE
Mealie with openrouter.ai / any experiences or model recommendations?

### DISCUSSION THREAD

**Discussion by au-ee** [mealie-recipes/mealie#5040] [General]
Hi, I am using openrouter.ai because it wraps a whole bunch of free and chargeable LLMs without the need to signup everywhere.
For the moment, I am using `openai/gpt4o`. That worked great with Mealie but its usage is rather expensive. 
I tried the Mealie image recognition with `google/gemini-2.0-flash-lite-preview-02-05:free` which is free of charge, but the results were not so great. I also tried with `anthropic/claude-3.5-sonnet` which is apparently good in processing images, but I was not so happy with my first tests.

Has any of you tried different models with Mealie? Any experiences / recommendations?

This is my current config:
``` yaml
OPENAI_BASE_URL: https://openrouter.ai/api/v1
OPENAI_API_KEY: ***my key***
OPENAI_MODEL: openai/gpt-4o 
# replace by the openrouter model id , e.g. google/gemini-2.0-flash-lite-preview-02-05:free
OPENAI_ENABLE_IMAGE_SERVICES: true
OPENAI_SEND_DATABASE_DATA: true
```

I am not affiliated with openrouter. I just like their universal interface which enables me to play around with different models, quickly.
