### DISCUSSION TITLE
Accent-insensitive search

### DISCUSSION THREAD

**Discussion by ThunderTecke** [mealie-recipes/mealie#5267] [Feature Request]
### First Check

- [X] I used the GitHub search to find a similar requests and didn't find it.
- [X] Checked the [tasks tagged](https://github.com/mealie-recipes/mealie/issues?q=is%3Aissue+is%3Aopen+label%3Atask+) issues and verified my feature is not covered

### Please provide a concise description of the problem that would be addressed by this feature.

In French (for example), when I need to find a word with an accent. I must write the accent to find it

### Please provide a concise description of the feature that would resolve your issue.

Make an accent-insensitive search.
For example, to find "pâtes" I should be able to write "pates".

### Please consider and list out some caveats or tradeoffs made in your design decision

None

### Additional Information

- [ ] If this is accepted I'm willing to submit a PR to provide this feature
- [ ] If this is accepted I'm willing to help maintain this feature
- [ ] I'm willing to sponsor/pay a developer to do this work

**Comment by michael-genson** [comment]
Can you share your deployment details? This should already work

**Comment by ThunderTecke** [comment]
It's running on a Raspberry Pi 5 4Go (64bits) with Docker. I can give you the Docker compose later in the day

**Comment by ThunderTecke** [comment]
![Screenshot_20250323-133728~2.png](https://github.com/user-attachments/assets/bd3e89cb-3cde-48ef-9398-0c4584133dfc)

![Screenshot_20250323-133742~2.png](https://github.com/user-attachments/assets/3aa7ba0c-a6e3-4354-91fa-1c512bb35067)

As you can see "crème fraiche" is not found with "creme", but yes with "crème".

I'm using an android phone with Brave as web browser.

And below a part of my docker-compose.yml

```
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    restart: unless-stopped
    ports:
      - "9925:9000"
    volumes:
      - ./mealie/data:/app/data
    environment:
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: America/Montreal

volumes:
  mealie-data:
```
