### DISCUSSION TITLE
In App Theme Selector

### DISCUSSION THREAD

**Discussion by TerrapinPi** [mealie-recipes/mealie#5369] [Feature Request]
### First Check

- [X] I used the GitHub search to find a similar requests and didn't find it.
- [X] Checked the [tasks tagged](https://github.com/mealie-recipes/mealie/issues?q=is%3Aissue+is%3Aopen+label%3Atask+) issues and verified my feature is not covered

### Please provide a concise description of the problem that would be addressed by this feature.

There's currently no option for users to select a theme. Light and dark themes can only be set at app installation.

### Please provide a concise description of the feature that would resolve your issue.

Provide an option for users to select a theme.

### Please consider and list out some caveats or tradeoffs made in your design decision

Currently, the only documentation on changing themes is here: https://docs.mealie.io/documentation/getting-started/installation/backend-config/#theming

The theme section really could be improved to provide some additional context and examples. For example, it took me a while to figure out how to format the theme environment variables in my docker-compose. Then, I have no idea how the colors will look in the app until the app is up and running and I load it into the browser. Having an option to select a theme from within the app would make this whole process a lot easier.

If not added to in-app options, please consider providing an example docker-compose with the theming options included.

```
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.8.0 # 
    container_name: mealie
    restart: always
    ports:
        - "9925:9000" # 
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - /mnt/mars/apps/mealie:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 568
      PGID: 568
      TZ: America/Denver
      # Change the light theme colors
      THEME_LIGHT_PRIMARY: "#00faff"
      THEME_LIGHT_ACCENT: "#329ba8"
      THEME_LIGHT_SECONDARY: "#a8328f"
      THEME_LIGHT_SUCCESS: "#34a832"
      THEME_LIGHT_INFO: "#ef00ff"
      THEME_LIGHT_WARNING: "#f9ff00"
      THEME_LIGHT_ERROR: "#ff1d00"
      BASE_URL: https://localhost
      # Database Settings
      DB_ENGINE: postgres
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: mealie
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mealie
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    volumes:
      - mealie-pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mealie
      POSTGRES_USER: mealie
      PGUSER: mealie
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  mealie-data:
  mealie-pgdata:
```

### Additional Information

- [ ] If this is accepted I'm willing to submit a PR to provide this feature
- [ ] If this is accepted I'm willing to help maintain this feature
- [ ] I'm willing to sponsor/pay a developer to do this work
