### DISCUSSION TITLE
Hide Username and password field when using OIDC

### DISCUSSION THREAD

**Discussion by userbradley** [mealie-recipes/mealie#5387] [Feature Request]
### First Check

- [X] I used the GitHub search to find a similar requests and didn't find it.
- [X] Checked the [tasks tagged](https://github.com/mealie-recipes/mealie/issues?q=is%3Aissue+is%3Aopen+label%3Atask+) issues and verified my feature is not covered

### Please provide a concise description of the problem that would be addressed by this feature.

Users trying to login with a username and password when their account is OIDC only

When OIDC sign in is enabled, it confuses users as the usual user pattern is to go to username and password field

### Please provide a concise description of the feature that would resolve your issue.

I am wanting a way to hide the username and password field when OIDC is enabled for Mealie, and either just force users in to an OIDC flow or just display the `Login with x` button

This will stop cases where a user has saved passwords for the subdomain from snapping to it, as well as confusion on login methods 

### Please consider and list out some caveats or tradeoffs made in your design decision

Bad:

* Admin needs to login with their original username and password

Good:

* Login is streamlined for _non-technical_ users who _"just want it to work"_

### Additional Information

- [ ] If this is accepted I'm willing to submit a PR to provide this feature
- [ ] If this is accepted I'm willing to help maintain this feature
- [ ] I'm willing to sponsor/pay a developer to do this work

**Comment by userbradley** [comment]
Something that looks like this 
![image](https://github.com/user-attachments/assets/1d6ff9a3-7847-45fc-9c1e-37346b674336)

**Comment by misha-artemiev** [comment]
about the bad part, you still can give admin rights when using OIDC

**Comment by misha-artemiev** [comment]
also i think it can be done quite easy (by someone who knows code base) in a similar way as visibility of an oidc button by adding additional environmental variable like  `INTERNAL_LOGIN` or other similar names. and ignore it (maybe) if there is no other ways to login

**Comment by daiw** [comment]
As far as I understand the docs, this should work by setting "ALLOW_PASSWORD_LOGIN: false". But for me it does not work :(

**Reply by michael-genson** [reply]
What version are you on?

**Reply by daiw** [reply]
Mealie docker image 2.8. I have OIDC enabled and set "ALLOW_PASSWORD_LOGIN: false" in docker compose env.
Log In remains possible with both password and OIDC...

**Reply by userbradley** [reply]
Weird, I am having the exact same situation!

**Reply by michael-genson** [reply]
This is only available in nightly. It's not in a release yet: https://github.com/mealie-recipes/mealie/pull/4943

**Reply by daiw** [reply]
Thx, that explains why I did not find the setting in any log or API output 😅
A bit confusing that the documentation is live before the release, but I'm happy to wait for the next release 👍

**Reply by ngoc-minh-do** [reply]
Came here by exactly same reason :D

**Comment by userbradley** [comment]
For anyone who comes here looking for the solution, use the below env variables

This example is for Pocket-id

```yaml
  OIDC_AUTH_ENABLED: "true"
  OIDC_CONFIGURATION_URL: "https://<>/.well-known/openid-configuration"
  OIDC_SIGNUP_ENABLED: "true"
  OIDC_CLIENT_ID: "<>"
  OIDC_CLIENT_SECRET: "<>"
  OIDC_PROVIDER_NAME: "Pocket ID"
  ALLOW_PASSWORD_LOGIN: "false"
  OIDC_AUTO_REDIRECT: "true"
  OIDC_REMEMBER_ME: "true"
# Optional stuff related to my config, that you're welcome to include if you want
  OIDC_SCOPES_OVERRIDE: "openid profile email groups"
  OIDC_NAME_CLAIM: "name"
  OIDC_ADMIN_GROUP: "mealie_admin"
  OIDC_USER_GROUP: "mealie"
```

You now get a page like

<img width="2519" height="1310" alt="image" src="https://github.com/user-attachments/assets/b2095663-6230-407e-937e-59b209b2d6df" />
