### DISCUSSION TITLE
PostgreSQL version: 15 vs 16.x or 17.5

### DISCUSSION THREAD

**Discussion by MilesTEG1** [mealie-recipes/mealie#5481] [General]
Hello,
I'm currently setting an instance of mealie in docker.
I'm reviewing the `docker-compose.yml` with PostgreSQL and I'm wondering the choice of the version 15 in the `docker-compose.yml` provided:
```yaml
  postgres:
    container_name: postgres
    image: postgres:15
```

I am completely new to databases, so I may ask a naïve question: Why is this "old version" being used when a newer 17.5 version is available? (Additionally, there is also a 15.13 version available, which is as recent as 17.5).

Thanks in advance for your answers.
