### ISSUE TITLE
[v1.0.0b] - Images not working on latest nightly

### ISSUE THREAD

**Issue by Sennevds** [mealie-recipes/mealie#1018]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Picture's aren't shown in the overview and detail screen. Getting a lot of 404's and when trying to update the image I still get a 404.
Using following compose file:

### Deployment

Docker (Linux)

### Deployment Details

```yaml
version: "3.1"
services:
  mealie-frontend:
    container_name: mealie-frontend
    image: hkotel/mealie:frontend-nightly
    restart: always
    ports:
      - "9925:3000"
    environment:
      - ALLOW_SIGNUP=true
      - API_URL=http://mealie-api:9000
    labels:
      - "traefik.http.routers.mealie_next.entrypoints=websecure"
      - "traefik.http.routers.mealie_next.rule=Host(`xxxxxxx`)"
      - "traefik.http.routers.mealie_next.tls=true"
      - "traefik.http.routers.mealie_next.tls.certresolver=myresolver"
      - "traefik.http.routers.mealie_next.middlewares=test-ipwhitelist@file"

  mealie-api:
    container_name: mealie-api
    image: hkotel/mealie:api-nightly
    restart: always
    volumes:
      - mealie-data:/app/data/
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie-beta.senne.tech

    
volumes:
  mealie-data:
    driver: local
networks: 
  default: 
    external: 
      name: proxy 
```
