### ISSUE TITLE
Environment var RECIPE_* are not used

### ISSUE THREAD

**Issue by maxthev** [mealie-recipes/mealie#1061]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Hello, 

I'm trying to disable "LANDSCAPE_VIEW" and "COMMENTS" so I edited default recipe settings with :

```
RECIPE_LANDSCAPE_VIEW=False
RECIPE_DISABLE_COMMENTS=True
```

but the app seems to ignore these settings.

Here is my setup : 

docker-compose.yml

```  
   mealie:
    image: hkotel/mealie:latest
    container_name: ${PROJECT}.mealie
    ports:
      - 8082:80
    env_file: conf/env/mealie.env
    volumes:
      - ./volume/mealie/data/:/app/data
    restart: unless-stopped
    networks:
      - http-proxy
```

mealie.env

```
TZ=Europe/Paris

RECIPE_PUBLIC=True
RECIPE_SHOW_NUTRITION=True
RECIPE_SHOW_ASSETS=True
RECIPE_LANDSCAPE_VIEW=False
RECIPE_DISABLE_COMMENTS=True
RECIPE_DISABLE_AMOUNT=False
```

When i query a recipe, the result is always the same : 
![Capture d’écran 2022-03-16 à 12 08 59](https://user-images.githubusercontent.com/13466285/158578037-ad4c8905-0e6c-46ce-b98b-4b8dfcff5233.png)

PS : I also tried different things but result is the same: 

- env directly in docker-compose.yml
- True/False with or without caps

PS2: `printenv` in the container show the right values

### Deployment

Docker (Linux)

### Mealie Version

0.5.6
