### ISSUE TITLE
Failing recipe scrape with proper JSON data

### ISSUE THREAD

**Issue by dmyoung9** [mealie-recipes/mealie#1085]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I have another recipe that fails to scrape, even with what appears to be proper JSON data.

The recipe is: https://natashaskitchen.com/chicken-tortilla-soup-recipe/

And I've pasted the JSON data returned in the scrape: https://www.toptal.com/developers/hastebin/uyitapicob.json

### Deployment

Docker (Linux)

### Deployment Details

I run Mealie using Docker Compose, on an Ubuntu 20.04.2 LTS virtual machine inside of Proxmox.

The relevant bit of my `docker-compose.yml` looks like this:
```yaml
version: "3"
services:
  ...

  mealie:
    container_name: mealie
    image: hkotel/mealie:v0.5.6
    restart: unless-stopped
    ports:
      - 9925:80
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
      RECIPE_PUBLIC: "true"
      RECIPE_SHOW_NUTRITION: "true"
      RECIPE_SHOW_ASSETS: "true"
      RECIPE_LANDSCAPE_VIEW: "true"
      RECIPE_DISABLE_COMMENTS: "false"
      RECIPE_DISABLE_AMOUNT: "false"
      WEB_CONCURRENCY: 2
      TOKEN_TIME: 336
    volumes:
      - /storage/docker/mealie/data/:/app/data
```

### Mealie Version

0.5.6
