### ISSUE TITLE
 [v1.0.0b] - TOKEN_TIME has no effect

### ISSUE THREAD

**Issue by makuris** [mealie-recipes/mealie#1131]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I set the TOKEN_TIME for the mealie API to 500, similar [as discussed for v0.5.6](https://github.com/hay-kot/mealie/issues/493#issuecomment-955580154) to reduce the quantity of log ins for everyone in my household.

500 should mean ca. every 20 days a new log in is necessary.
However, mealie is asking for log in already the next day.

Automatic updates of the docker container are deactivated. The mealie containers are currently running for 9 days without any stop.

### Deployment

Docker (Synology)

**Comment by hay-kot** [comment]
Have you checked the time of the token you're getting back? 

You can use https://token.dev/ to get the token values and https://www.epochconverter.com/ to see the token time being returned. 

I'm not able to replicate your issue. A few things to note though...

1. TOKEN_TIME only adjusts the default token value, when "Remember Me" is checked it uses 7 days regardless of the TOKEN_TIME variable.
2. The token is stored in browser as cookie `auth._token_expiration.local` if you're purging cookies on a regular basis you will lose your session.

**Comment by makuris** [comment]
Thank you for your support!

I have checked the token values set in the cookies with the developer tools and the epochconverter and the token time is approx. 21 days, which corresponds to the 500h I have set as TOKEN_TIME. So this is working as expected.

So maybe the cookie gets deleted by one of my browser add-ons in Firefox? Sorry, I am really not that experienced with cookies at all. As far as I understood the mealie cookies are session cookies and will be deleted as soon as I close the browser?

I used then the Edge Browser which is a blank installation on my PC without any additional add-ons that could mess things up.

In the developer tools I read in the column "Expires/Max. Age" for `auth._token_expiration.local` "Session". So as soon as I close the browser I have to log in again. Is this a setting in the browser I have to change?

**Comment by hay-kot** [comment]
> So maybe the cookie gets deleted by one of my browser add-ons in Firefox? 

If you have restrictive privacy settings it's possible that's what happening. Or FireFox itself could be deleting the cookies.

**Comment by makuris** [comment]
I am not able to identify the root cause. As long as no one else experiences a similar issue I guess the problem is on my side :-) So, sorry for wasting your time and thank you for your support.

**Comment by dmyoung9** [comment]
This morning, I went to do some "recipe maintenance", and was prompted to login (despite having logged in only a few days ago).

My config looks like:
```yaml
version: "3"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-3
    container_name: mealie-frontend
    environment:
      # Set Frontend ENV Variables Here
      - API_URL=http://mealie-api:9000  # This appears to be as-yet undocumented?
    restart: always
    ports:
      - "9926:3000"
    volumes:
      - mealie-data:/app/data/

  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-3
    container_name: mealie-api
    volumes:
      - mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - TOKEN_TIME=336
      - BASE_URL=https://mealie.yourdomain.com  # I don't use notifications, so never bothered to set this
    restart: always
```

Checking `auth._token_expiration.local` in Chrome (after having logged in) does indeed appear to be two weeks from when I logged in (`336hr == 14d`).

I'll check the token again before next time I need to log in and see what it says, but it doesn't seem that the token expiration is actually affecting anything here. I have to login almost every single time I visit.
