### ISSUE TITLE
[v1.0.0b] - Error when deploy stack.

### ISSUE THREAD

**Issue by mariushosting** [mealie-recipes/mealie#1297]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

II use Portainer to deploy stack. Everything is correctly set up but when I try to start the frontend container I receive this error: 
Server error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.
In the logs I found this:
 ERROR  [HPM] Error occurred while proxying request localhost:3001/api/app/about to http://localhost:9000/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)

Below my docker compose:

```yaml
version: "3.7"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0-beta-1
    container_name: mealie-frontend
    restart: always
    ports:
      - 9925:3000
    volumes:
      - /volume1/docker/mealie:/app/data/
  mealie-api:
    image: hkotel/mealie:api-v1.0.0-beta-1
    container_name: mealie-api
    volumes:
      - /volume1/docker/mealie:/app/data/
    environment:
      - ALLOW_SIGNUP=true
      - PUID=1026
      - PGID=100
      - TZ=Europe/Bucharest
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1

    restart: always

volumes:
  mealie-data:
    driver: local
```
### Deployment

Docker (Synology)
