### ISSUE TITLE
Search Logical Operators Work Backwards/Inverted (OR is exclusive, AND is inclusive) in Exclude Mode

### ISSUE THREAD

**Issue by duggym122** [mealie-recipes/mealie#1328]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I have checked for existing issues that have been resolved in v1-beta

### Overview
When using search-exclude, selecting multiple Categories with the AND operator should only exclude recipes in the intersecting set to display. Changing to "OR" mode causes the expected behavior for a logical "AND" operation functioning as the intersection of sets, and the "AND" option functions as the union of sets.

### Steps to Reproduce

1. Add a recipe, titled "Beef Stroganoff Soup Dumplings", set two category values "Cuisine: Dim Sum" and "Cuisine: French" 
2. Add a second recipe, titled "Red Curry Broccoli Stir-Fry", set one category value "Cuisine: Thai"
3. Search for recipes on the /search page
4. Ensure "Exclude" is selected on the left-hand category filter panel
5. Ensure "OR" is selected on the left-hand category filter panel
6. Enter "Cuisine: Dim Sum", "Cuisine: French", and "Cuisine: Thai" to the filters
7. Observe no recipes being displayed
8. Switch from "OR" to "AND"
9. Observe both recipes returning

### Deployment

Other

### Deployment Details

I'm using docker-compose via Portainer, running on a Synology NAS, but not relying on Synology UI for any operations

### Docker-Compose
```
version: "3"
services:
  recipe-app:
    image: hkotel/mealie:latest
    container_name: recipe-mealie-app
    network_mode: bridge
    env_file:
      - stack.env
    volumes:
      - $SYNO_VOL_MEALIE:/app/data
    ports:
      - <REDACTED>:80
    restart: unless-stopped
```

### .env File
```
PGID=<REDACTED>
PUID=<REDACTED>
TZ=America/Denver
RECIPE_PUBLIC='true'
RECIPE_SHOW_NUTRITION='true'
RECIPE_SHOW_ASSETS='true'
RECIPE_LANDSCAPE_VIEW='true'
RECIPE_DISABLE_COMMENTS='true'
RECIPE_DISABLE_AMOUNT='false'
DEFAULT_GROUP=Home
DEFAULT_EMAIL=<REDACTED>
DB_ENGINE=sqlite
TOKEN_TIME=12
AUTO_BACKUP_ENABLED='true'
API_PORT=9000
API_DOCS='true'
SYNO_VOL_MEALIE=<REDACTED>
```

### Mealie Version

v0.5.6
