### ISSUE TITLE
Can't deploy the latest nightly

### ISSUE THREAD

**Issue by Nabukodonosor** [mealie-recipes/mealie#1440]
So, I've tried the latest tag version, and it works, but the latest beta frontend-v1.0.0beta-3 version has many more features that I would like to try. But when I use this tag, or the frontend-nightly tag, I can't start it anymore. I have tried many times, but the result is the same. I use docker.

Here's the log:

```
{"level":"info","ts":1655913975.835223,"msg":"using provided configuration","config_file":"/app/Caddyfile","config_adapter":""}
{"level":"warn","ts":1655913975.8382642,"msg":"input is not formatted with 'caddy fmt'","adapter":"caddyfile","file":"/app/Caddyfile","line":36}
{"level":"warn","ts":1655913975.838681,"logger":"admin","msg":"admin endpoint disabled"}
{"level":"info","ts":1655913975.839309,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0004761c0"}
{"level":"info","ts":1655913975.8400736,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/root/.local/share/caddy"}
{"level":"info","ts":1655913975.8401077,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"info","ts":1655913975.8406043,"msg":"autosaved config (load with --resume flag)","file":"/root/.config/caddy/autosave.json"}
{"level":"info","ts":1655913975.8406148,"msg":"serving initial configuration"}
Successfully started Caddy (pid=14) - Caddy is running in the background
yarn run v1.22.19
$ nuxt start -p 3001
ℹ [HPM] Proxy created: api  -> http://localhost:9000
ℹ [HPM] Proxy rewrite rule created: "api" ~> "/api"
ℹ [HPM] Proxy created: /api  -> http://localhost:9000
ℹ Listening on: http://192.168.128.2:3001/
```

And here's my docker-compose:

```yaml
version: "3.1"
services:
   mealie:
     container_name: mealie
     image: hkotel/mealie:frontend-nightly
     restart: always
     ports:
       - 9925:80
     environment:
       PUID: 1000
       PGID: 100
       TZ: Europe/Belgrade
 
       # Default Recipe Settings
       RECIPE_PUBLIC: 'true'
       RECIPE_SHOW_NUTRITION: 'true'
       RECIPE_SHOW_ASSETS: 'true'
       RECIPE_LANDSCAPE_VIEW: 'false'
       RECIPE_DISABLE_COMMENTS: 'false'
       RECIPE_DISABLE_AMOUNT: 'false'
       DEFAULT_EMAIL: 'myemail@gmail.com'
 
       # Gunicorn
       # WEB_CONCURRENCY: 2
       # WORKERS_PER_CORE: 0.5
       # MAX_WORKERS: 8
     volumes:
       - /MainPool/Documents/Containers/mealie/data/:/app/data
```
Also, when I install any version but the tag:latest, my /app/data folder is empty.
