### ISSUE TITLE
[v1.0.0b] - Internal server error when creating Event Notifiers 

### ISSUE THREAD

**Issue by Meuschke23** [mealie-recipes/mealie#1485]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When I click on "Create" to create a new Event Notifier, nothing happens. When I reload the web page, I get an internal server error. 

![grafik](https://user-images.githubusercontent.com/65863113/179149378-80e7fd29-0ca7-456b-b782-daeff857ce9e.png)

Already existing event notifiers are no longer displayed.

### Deployment

Docker (Linux)

### Deployment Details
```
version: "3.7"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-nightly
    container_name: mealie-frontend
    environment:
    # Set Frontend ENV Variables Here
      - API_URL=http://mealie-api:9000 # 
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.app-mealie-s02.entrypoints=websecure
      - traefik.http.routers.app-mealie-s02.rule=Host(`<CENSORED>`)
      - traefik.http.services.app-mealie-s02.loadbalancer.server.port=3000
      - diun.enable=true
    networks:
      - proxy
      - intern
    restart: always
    volumes:
      - /srv/AppData/Mealie/data:/app/data/


  mealie-api:
    image: hkotel/mealie:api-nightly
    container_name: mealie-api
    volumes:
      - /srv/AppData/Mealie/data:/app/data/
    secrets:
      - MailPassword # optional but required for (1)
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=false
      - LDAP_AUTH_ENABLED=false
      - SMTP_HOST=<CENSORED>
      - SMTP_PORT=465
      - SMTP_FROM_NAME=Mealie
      - SMTP_AUTH_STRATEGY=SSL

      - SMTP_FROM_EMAIL=<CENSORED>
      - SMTP_USER=<CENSORED>
      - SMTP_PASSWORD=/srv/AppData/.secrets/Mail/<CENSORED>
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - WORKERS_PER_CORE=0.5
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://<CENSORED>
    labels:
      - diun.enable=true
    restart: always
    networks:
      - intern

volumes:
  mealie-data:
    driver: local

networks:
  intern:
  proxy:
    external: true
    
secrets:
  MailPassword:
    file: /srv/AppData/.secrets/Mail/<CENSORED>
```
