### ISSUE TITLE
[v1.0.0b] - user in other group can't see public recipes

### ISSUE THREAD

**Issue by schnuckz** [mealie-recipes/mealie#1525]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Hi, 

creating two new groups.
Put the default User in GroupA, create new user in GroupB they can't see the public recipes of GroupA and vice versa.
Nothing happens on change the recipe settings or group settings.

### Deployment

Docker (Linux)

### Deployment Details

```
version: "3.7"
services:
  frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-4
    networks:
      - proxy
      - intern
    depends_on:
      - mealie-api
    environment:
      - API_URL=http://mealie-api:9000
    restart: always
    volumes:
      - ${DATA_DIR}/mealie:/app/data/
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
#      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.docker.network=cus0"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${HOST}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${SECUREMIDDLEWARES}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=tls"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3000"


  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-4
    networks:
      - intern
      - extern
    depends_on:
      - postgres
    volumes:
      - ${DATA_DIR}/mealie:/app/data/
    environment:
      - ALLOW_SIGNUP
      - PUID
      - PGID
      - TZ
      - MAX_WORKERS
      - WEB_CONCURRENCY
      - BASE_URL=https://${HOST}
      - DEFAULT_GROUP
      - DEFAULT_EMAIL
      - TOKEN_TIME
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_FROM_NAME
      - SMTP_AUTH_STRATEGY
      - SMTP_FROM_EMAIL
      - SMTP_USER
      - SMTP_PASSWORD
      - DB_ENGINE=postgres
      - POSTGRES_USER=${COMPOSE_PROJECT_NAME}
      - POSTGRES_PASSWORD
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${COMPOSE_PROJECT_NAME}
    restart: always
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
#      - "com.centurylinklabs.watchtower.enable=true"


  postgres:
    restart: always
    image: postgres:14-alpine
#    shm_size: 256mb
    networks:
      - intern
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${COMPOSE_PROJECT_NAME}"]
    volumes:
      - ${DATA_DIR}/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER=${COMPOSE_PROJECT_NAME}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"


networks:
  proxy:
    external: true
    name: cus0
  intern:
    internal: true
  extern:
```
