### ISSUE TITLE
[v1.0.0b] - Can't Get Today's Recipe Image for Home Assistant

### ISSUE THREAD

**Issue by matthewmorris09** [mealie-recipes/mealie#1626]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I can't seem to get the today's meal image from the API to put into Home Assistant. I tried using the information from the [documentation](https://nightly.mealie.io/documentation/community-guide/home-assistant/), but it looks like the API has changed with the move to v1.0b.

The docs say the image should be available through `http://localhost:9000/api/meal-plans/today/image?group_name=Home` but that doesn't seem to work for me. I don't see that same endpoint available in the swagger API. I can see the endpoint to get the JSON for `/api/groups/mealplans/today` but that only gives an ID for the image.

Before I continue down this road I wanted to make sure there wasn't something obvious I was missing. 

My Setup:
I'm running a docker container in a Linux VM for the latest official release v1.0.0beta-4 (not the nightly). I'm also running it through a reverse proxy (SWAG).

### Deployment

Docker (Linux)

### Deployment Details

Docker install via a Linux VM managed through Proxmox. Running Mealie through a reverse proxy using SWAG.

**Comment by proffalken** [comment]
A quick test shows that [Get Recipe Image](https://nightly.mealie.io/api/redoc/#tag/Recipe:-Images-and-Assets/operation/get_recipe_img_api_media_recipes__recipe_id__images__file_name__get) is the endpoint you need to pull back the image.

I'm working out how to pull both the recipe name *and* the recipe id as separate attributes of the same sensor, at which point we should be able to use the `name` in the card description and the `id` to in the image URI.

**Comment by proffalken** [comment]
OK, change the sensor to the following:

```
sensor:
  - platform: rest
    resource: 'http://mealie/api/groups/mealplans/today'
    method: GET
    name: Mealie todays meal 
    headers:
      Authorization: Bearer <MY TOKEN>
    value_template: "{{ value_json.value }}"
    json_attributes_path: $..recipe
    json_attributes:
      - name
      - id
      - totalTime
      - prepTime
      - performTime
```

This will give you the attributes you need to pull back the title etc.

There is also a [HACS integration](https://github.com/Tommatheussen/mealie-hacs) I was pointed to on Reddit and that works for showing the image, but I can't get the recipe name to show over the top of it!
