### ISSUE TITLE
[v1.0.0b] - Possible to register a new user using the api when signups are disabled

### ISSUE THREAD

**Issue by RemakingEden** [mealie-recipes/mealie#1724]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

**Overview** 
On my personal system I have set  `- ALLOW_SIGNUP=false` in the docker-compose file as I do not wish anyone to be able to register without myself orchestrating this. 

I was playing around with the swagger docs at /docs and I noticed I could sign up very easily there with no authentication and log in.

**Steps to reproduce**
1. Set `- ALLOW_SIGNUP=false` in your docker compose file and use `docker-compose up` to start the system
2. Navigate to the swagger docs `http://deployment-url:deployment-port/docs`
3. Use the `/api/users/register` endpoint to create a new user

**Expected Result**
- A user cannot be created unless the user of the API is authenticated as an admin

**Actual Result**
- A new user is created and can be used to login to Mealie

### Deployment

Docker (Linux)

### Deployment Details

**Details**
Version: v1.0.0beta-4
Build: 13850cda1f9cb02a8c788030ba6cfa96bba33571
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.11.0

**Checks**
Secure Site: No
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: No
Docker Volumes: success

**Comment by RemakingEden** [comment]
I'm happy to do the work on this, struggling a little to get the dev containers environment working at the moment though. I've not used it before so perhaps it is user error.

**Comment by GeeteshMehto** [comment]
Hello sir, please assign this issue to me as i already worked on this kind of problem in past and has a great experience.

**Comment by RemakingEden** [comment]
Yeah no problem @GeeteshMehto assign it to yourself. I'm happy for you to take it.

**Comment by hay-kot** [comment]
Can you post your docker-compose?

**Comment by RemakingEden** [comment]
Sure! 
```yaml
---
version: "3.7"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-5
    container_name: mealie-frontend
    environment:
      - API_URL=http://mealie-api:9000 #
    restart: always
    ports:
      - "9925:3000" #
    volumes:
      - ${APPDATA}/mealie:/app/data # config files
  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-5
    container_name: mealie-api
    volumes:
      - ${APPDATA}/mealie:/app/data # config files
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=false
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ={TZ}
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=http://192.168.1.3
    restart: always

volumes:
  mealie-data:
    driver: local
```
