### ISSUE TITLE
[v1.0.0b] - Installation troubles with Ubuntu, Docker, Postgres, Nginx Proxy Manager

### ISSUE THREAD

**Issue by funkywaddle** [mealie-recipes/mealie#1765]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

SETUP
===========

- Ubuntu 20.04
- Docker 20.10
- Nginx Proxy Manager 2.9.18

ISSUE
===========
I first tried the Postgres docker-compose file listed on the website ([here](https://nightly.mealie.io/documentation/getting-started/installation/postgres/)) with minor changes (changed external port, base_url, and altered postegres database settings to use .env file for values). 

Then ran `docker compose up -d`

Everything appeared to download successfully, so I then setup the url in Nginx Proxy Manager to route the request to the port I put into the docker-compose file, and to force https (grabbing a cert from Let's Encrypt).

When I went to my browser and tried to go to the url, it forwarded me to the `/login` page, but the login page is throwing a 500 error.

I tried multiple minor other changes in the docker-compose file, with no luck.

I then read on one of the open issues that they had trouble with the beta images, but the nightly worked, so I tried using the nightly builds for both api and frontend.

This too lead to the same outcome (forward me to `/login`, throw a 500)

Please see current docker-compose file and access and error logs below for more info.

Thank you in advance for any help you can offer.

DOCKER-COMPOSE FILE
===========
```yml
version: "3.7"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-nightly
    container_name: mealie-frontend
    depends_on:
      - mealie-api
    environment:
    # Set Frontend ENV Variables Here
      - API_URL=http://mealie-api:9000
    restart: always
    ports:
      - "8002:3000"
      - "4447:443" 
    volumes:
      - mealie-data:/app/data/

  mealie-api:
    image: hkotel/mealie:api-nightly
    container_name: mealie-api
    deploy:
      resources:
        limits:
          memory: 1000M

    depends_on:
      - postgres
    volumes:
      - mealie-data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - MAX_WORKERS=2
      - WEB_CONCURRENCY=1
      - BASE_URL=https://[redacted]

    # Database Settings
      - DB_ENGINE=postgres
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASS}
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=${POSTGRES_DB_PORT}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    restart: always
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASS}
      POSTGRES_USER: ${POSTGRES_DB_USER}

volumes:
  mealie-data:
    driver: local
```

ACCESS LOG
===========
```log
[24/Oct/2022:03:02:10 +0000] - 302 302 - GET https [redacted domain] "/" [Client [redacted ip]] [Length 0] [Gzip -] [Sent-to [redacted ip]] "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0" "-"
[24/Oct/2022:03:02:10 +0000] - 500 500 - GET https [redacted domain] "/login" [Client [redacted ip]] [Length 919] [Gzip -] [Sent-to [redacted ip]] "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0" "-"
```

ERROR LOG
===========
```log
2022/10/24 03:01:45 [error] 506#506: *3645 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: [redacted ip], server: [redacted domain], request: "GET / HTTP/2.0", upstream: "https://[redacted ip]:8002/", host: "[redacted domain]"
```

### Deployment

Docker (Linux)
