### ISSUE TITLE
[v1.0.0b] - API container cannot connect to database container

### ISSUE THREAD

**Issue by SteveDinn** [mealie-recipes/mealie#1773]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

After installing 1.0.0-beta5, I couldn't bring up a working instance of Mealie. Upon starting the API container, it was unable to connect to the database container. I feel like I've missed something dumb here, but I don't know what it could be. I'm not sure why the hostname I've specified for the database container is not resolvable.

Logs from the API container are as follows:
```
# docker-compose up -d && docker logs -f --tail 100 mealie-api
Creating network "mealie_default" with the default driver
Creating mealie-db ... done
Creating mealie-api ... done
Creating mealie-frontend ... done
Production
Switching to dedicated user
Production

        User uid:    1000
        User gid:    1000

ERROR: 26-Oct-22 07:08:41       Error connecting to database: (psycopg2.OperationalError) could not translate host name "mealie-db" to address: Name or service not known

(Background on this error at: https://sqlalche.me/e/14/e3q8)
ERROR: 26-Oct-22 07:08:41       Database connection failed. Retrying in 1 seconds...
ERROR: 26-Oct-22 07:08:42       Error connecting to database: (psycopg2.OperationalError) could not translate host name "mealie-db" to address: Name or service not known
```

### Deployment

Docker (Linux)

### Deployment Details

The only changes to this docker-compose.yml file since running v1.0.0-beta4 successfully were the tags on the image names for the frontend and API containers to change them to v1.0.0beta-5. I've redacted some passwords and domain names.
```
version: "3.7"
services:
  db:
    container_name: mealie-db
    hostname: mealie-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "[redacted]"
      POSTGRES_USER: "mealie"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /srv/mealie/database:/var/lib/postgresql/data

  frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-5
    container_name: mealie-frontend
    hostname: mealie-frontend
    depends_on:
      - api
    environment:
      # Set Frontend ENV Variables Here
      API_URL: "http://mealie-api:9000"
      ALLOW_SIGNUP: "false"
    restart: always
    ports:
      - 8024:3000
    volumes:
      - /srv/mealie/data:/app/data/:ro

  api:
    image: hkotel/mealie:api-v1.0.0beta-5
    container_name: mealie-api
    hostname: mealie-api
    restart: always
    depends_on:
      - db
    volumes:
      - /srv/mealie/data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "true"
      PUID: "1000"
      PGID: "1000"
      TZ: "America/Halifax"
      MAX_WORKERS: "4"
      WEB_CONCURRENCY: "1"
      BASE_URL: "[redacted]"
      DEFAULT_EMAIL: "[redacted]"
      ALLOW_SIGNUP: "false"
      SECURITY_MAX_LOGIN_ATTEMPTS: "5"
      SECURITY_USER_LOCKOUT_TIME: "24"

      # SMTP Settings
      SMTP_HOST: "[redacted]"
      SMTP_PORT: "25"
      SMTP_FROM_NAME: "Mealie"
      SMTP_AUTH_STRATEGY: "NONE"
      SMTP_FROM_EMAIL: "[redacted]"

      # Database Settings
      DB_ENGINE: "postgres"
      POSTGRES_USER: "mealie"
      POSTGRES_PASSWORD: "[redacted]"
      POSTGRES_SERVER: "mealie-db"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "mealie"
```
