### ISSUE TITLE
Unable to restore recipes when going from v1.0.0beta-4 to v1.0.0beta-5

### ISSUE THREAD

**Issue by jrosetto** [mealie-recipes/mealie#1918]
I'm running a Ubuntu 20.04 docker container.  When I backup to a zip using the built in utility and down the v1.0.0beta-4 container to bring up the v1.0.0beta-5 container to restore the backup I get the following after I press restore and am logged out.

database backup schema version does not match current database

Any suggestions to get to beta5?

For now I switched back to beta4 container and everything is working as expected.

Thanks.

**Comment by hay-kot** [comment]
You can just upgrade the containers to the new image. Database migrations have been in place for a few beta versions so the only need to do a backup/restore is in the event something goes wrong. For upgrading I suggest

1. Take backup and download to local computer
2. Stop containers
3. Pull latest images
4. Start containers

Only if something goes wrong would you need to revert to the previous version and wait until we fix the issue.

**Comment by jrosetto** [comment]
I'm still fairly new new to the whole docker concept.  When I migrated from pre v1 to v1.0.4beta I downloaded the zip in releases and ran docker-compose up -d to start the container.  Then I imported my backup file.

Now running 'docker-compose pull' doesn't seem to do anything.

What would you suggest to get to beta5 in my scenario?
Should I extract the new beta5 zip on top of the previous directory?

**Comment by jrosetto** [comment]
I decided to take a snapshot and start playing around with docker to see what I could come up with.

I ended up extracting the 1.0.5 into a different directory and letting it create a new container.  I moved the data folder located in /var/lib/docker/volumes over to the directory the new container was using and all of my recipes showed up again.

Not sure if this is the correct way to do it but it worked for me.

If there is an easier/better way to be doing this please let me know.

Thank you for Mealie!

**Comment by hay-kot** [comment]
To use docker-compose pull to upgrade the image you first have to change the tag

```yml
---
version: "3.7"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-4
    container_name: mealie-frontend
    environment:
    # Set Frontend ENV Variables Here
      - API_URL=http://mealie-api:9000 # 
    restart: always
    ports:
      - "9925:3000" # 
    volumes:
      - mealie-data:/app/data/ # 
  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-4
    container_name: mealie-api
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - mealie-data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/Anchorage
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.yourdomain.com
    restart: always

volumes:
  mealie-data:
    driver: local
```

Becomes

```yaml
---
version: "3.7"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-5 # <- Note Increment of number
    container_name: mealie-frontend
    environment:
    # Set Frontend ENV Variables Here
      - API_URL=http://mealie-api:9000 # 
    restart: always
    ports:
      - "9925:3000" # 
    volumes:
      - mealie-data:/app/data/ # 
  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-5 # <- Note Increment of number
    container_name: mealie-api
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - mealie-data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/Anchorage
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.yourdomain.com
    restart: always

volumes:
  mealie-data:
    driver: local
```

Then when you run `pull` it will pull the new image tag
