### ISSUE TITLE
[v1.0.0b] -   ERROR  [HPM] Error occurred while proxying request 100.92.124.56:9925/api/tags to http://100.92.124.56:9000/

### ISSUE THREAD

**Issue by bee-san** [mealie-recipes/mealie#1976]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Hey folks! Trying to run the Mealie beta. I get this error when opening the webapp:

```
mealie-frontend  |  ERROR  [HPM] Error occurred while proxying request 100.92.124.56:9925/api/tags to http://100.92.124.56:9000/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

I also can't login:

```
mealie-frontend  |  ERROR  [HPM] Error occurred while proxying request 100.92.124.56:9925/api/auth/token to http://100.92.124.56:9000/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

This is very likely an issue with my setup, but I do not know much about networking & the documentation doesn't mention this. I can run the non-beta version v0.5 just fine.

### Deployment

Docker (Linux)

### Deployment Details

100.92.124.56 = the IP of my server within my VPN
Using LocalHost and ignoring the VPN produces the same errors for me :)

Compose:

```
---
version: "3.7"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-5
    container_name: mealie-frontend
    environment:
    # Set Frontend ENV Variables Here
      - API_URL=http://100.92.124.56:9000 # 
    restart: always
    ports:
      - "9925:3000" # 
    volumes:
      - mealie-data:/app/data/ # 
  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-5
    container_name: mealie-api
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - mealie-data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/Anchorage
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=http://100.92.124.56:9925
    restart: always

volumes:
  mealie-data:
    driver: local
```
