### ISSUE TITLE
Shopping list copy to clipboard not working

### ISSUE THREAD

**Issue by Aerodynamite** [mealie-recipes/mealie#2205]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I have checked for existing issues that have been resolved in v1-beta

### What is the issue you are experiencing?

The copy to clipboard button on the shopping list doesn't work and generates a console error:
```
vue.runtime.esm.js:1897 TypeError: Cannot read properties of undefined (reading 'writeText')
    at a.textToClipboard (TheCopyButton.vue:58:27)
    at click (TheCopyButton.vue?18ca:4:13)
    at ie (vue.runtime.esm.js:1863:26)
    at a.n (vue.runtime.esm.js:2188:14)
    at ie (vue.runtime.esm.js:1863:26)
    at t.$emit (vue.runtime.esm.js:3903:9)
    at a.click (VBtn.ts:163:7)
    at ie (vue.runtime.esm.js:1863:26)
    at HTMLButtonElement.n (vue.runtime.esm.js:2188:14)
    at Qr.o._wrapper (vue.runtime.esm.js:6961:25)
```

![image](https://user-images.githubusercontent.com/10129439/222892391-a420b776-dfe9-4653-94e8-64a45c7d5203.png)

### Deployment

Docker (Linux)

### Deployment Details

Mealie section of my docker-compose file:

```
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    restart: unless-stopped
    ports:
      - 9110:80
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

      # Default Recipe Settings
      - RECIPE_PUBLIC=true
      - RECIPE_SHOW_NUTRITION=true
      - RECIPE_SHOW_ASSETS=true
      - RECIPE_LANDSCAPE_VIEW=true
      - RECIPE_DISABLE_COMMENTS=false
      - RECIPE_DISABLE_AMOUNT=false

      # Gunicorn
      # - WEB_CONCURRENCY=2
      # - WORKERS_PER_CORE=0.5
      # - MAX_WORKERS=8
    volumes:
      - ${USERDIR}/docker/mealie/:/app/data
```

### Mealie Version

image: hkotel/mealie:latest
