### ISSUE TITLE
[v1.0.0b] - API Create user replacing username with full name

### ISSUE THREAD

**Issue by robert-sandor** [mealie-recipes/mealie#2209]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Creating a new user using the API (`POST /api/users`) results in the username being ignored, and replaced by the value from the full_name.

Example:
```
POST /api/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer <access_token>
Host: mealie.example.com
Content-Length: 154

{
	"username": "username",
	"fullName": "full name",
	"group": "home",
	"email": "email@example.com",
	"admin": false,
	"password": "verysecurepassword"
}
```

results in 

```
{
	"username": "full name",
	"fullName": "full name",
	"email": "email@example.com",
	"admin": false,
	"group": "Home",
	"favoriteRecipes": [],
	"id": 4,
	"tokens": []
}
```

whereas expected result would be:
```
{
	"username": "username",
	"fullName": "full name",
	"email": "email@example.com",
	"admin": false,
	"group": "Home",
	"favoriteRecipes": [],
	"id": 4,
	"tokens": []
}
```

### Deployment

Docker (Linux)

### Deployment Details

compose.yml
```
version: "3.8"

services:
  mealie:
    container_name: mealie
    hostname: mealie
    image: hkotel/mealie:latest
    restart: unless-stopped
    environment:
      TZ: Europe/Bucharest
      PUID: 1000
      PGID: 1000
    volumes:
      - "./data:/app/data"
    networks:
      - apps
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.services.mealie.loadbalancer.server.port=80
      - traefik.http.routers.mealie.rule=Host(`mealie.example.com`)
      - traefik.http.routers.mealie.entrypoints=websecure
      - traefik.http.routers.mealie.service=mealie

networks:
  apps:
    external: true
```
