### ISSUE TITLE
[v1.0.0b] - LDAP Not functional with AD on current nightly (3/23/2023)

### ISSUE THREAD

**Issue by LargoUsagi** [mealie-recipes/mealie#2279]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

As of latest nightly with changes to the LDAP_USER_FILTER I am seeing the new error that there are multiple users coming back.

```
ERROR: 23-Mar-23 15:33:54 [LDAP] Multiple users found with the provided user filter
```

When using the same filters via `Get-ADUser -LDAPFilter 'expression'` in powershell I am only sing a single result.

I would expect that if there where multiple responses it would at least take the first response in the set and attempt a bind to that.

It is also unclear if this was a breaking change to how this field worked before merging https://github.com/hay-kot/mealie/pull/2199 based on the discussion here https://github.com/hay-kot/mealie/issues/2228

### Deployment

Other

### Deployment Details

Kubernetes using containerd on linux.

Application works flawlessly outside of raised issue and worked for a few weeks before pulling latest nightly.

**Comment by cmintey** [comment]
Can you please share your `LDAP_USER_FILTER`?

**Comment by LargoUsagi** [comment]
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mealie-config
data:
  PUID: "1000"
  PGID: "1000"
  ALLOW_SIGNUP: 'false'
  MAX_WORKERS: "1"
  WEB_CONCURRENCY: "1"
  BASE_URL: "https://foodlibrary.****"
  LDAP_AUTH_ENABLED: "true"
  LDAP_SERVER_URL: "ldap://****:389"
  LDAP_TLS_INSECURE: "true"
  LDAP_BASE_DN: "dc=****,dc=****,dc=****"
  LDAP_QUERY_BIND: "****"
  LDAP_QUERY_PASSWORD: "****"
  LDAP_ID_ATTRIBUTE: "sAMAccountName"
  LDAP_USER_FILTER: "(&(|({id_attribute}={input})({mail_attribute}={input}))(objectClass=user))"
  LDAP_ADMIN_FILTER: "(memberOf=cn=MealieAdmin,OU=Domain Groups,dc=****,dc=****,dc=****)"
```

I Have also removed it and tried the default, or used the objectClass of person.

This only returns one result

```powershell
 Get-ADUser -LDAPFilter '(|(sAMAccountName=largousagi)(mail=largousagi))(objectClass=user)'
```

I also tested setting the user filter to match the admin filter of
```
(memberOf=cn=MealieAdmin,OU=Domain Groups,dc=****,dc=****,dc=****)
```
