### ISSUE TITLE
[v1.0.0b] - Invalid Credentials when behind NGINX reverse proxy on Yunohost system. Missing Bearer token

### ISSUE THREAD

**Issue by pihomeserver** [mealie-recipes/mealie#2397]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Hi
On a Yunohost system (Debian 11 VPS) i have installed different apps in docker containers. I did the same for Mealie but i could not logged in, getting an invalid credentials message. I'm pretty sure it's due to the Nginx configuration but can't figure why (i saw issue [#1845](https://github.com/hay-kot/mealie/issues/1845) but I don't think it's related to my situation)
When doing curl commands on the host it works
When using the API from docs i can log in but other actions are rejected
It seems that the Authorization header is not properly set. If i hard code the bearer token then i can reach the site and browse it

Any idea about NGINX reverse proxy configuration to set to make credentials / token keep ?

### Deployment

Docker (Linux)

### Deployment Details

Here is the docker compose file
```
version: "3.7"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-5
    container_name: mealie-frontend
    environment:
    # Set Frontend ENV Variables Here
      - API_URL=http://mealie-api:9000
    restart: unless-stopped
    ports:
      - "9925:3000"
    volumes:
      - ./mealie/data/:/app/data
  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-5
    container_name: mealie-api
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - ./mealie/data/:/app/data
    environment:
    # Set Backend ENV Variables Here
      ALLOW_SIGNUP: true
      PUID: 61616
      PGID: 61616
      TZ: ${MEALIE_TZ}
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://recettes.myhost.fr
    restart: unless-stopped
```

Here is the redirect Nginx configuration
```
location / {
  proxy_pass        http://127.0.0.1:9925;
  proxy_redirect    off;
  proxy_set_header  Host $host;
  proxy_set_header  X-Real-IP $remote_addr;
  proxy_set_header  X-Forwarded-Proto $scheme;
  proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header  X-Forwarded-Host $server_name;
  proxy_set_header  X-Forwarded-Port $server_port;

  #proxy_set_header Authorization $http_authorization;
  proxy_set_header Authorization "Bearer $arg_token";
  proxy_pass_header Authorization;   
  
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";

  # Include SSOWAT user panel.
  include conf.d/yunohost_panel.conf.inc;
  more_clear_input_headers 'Accept-Encoding';
}
```
