### ISSUE TITLE
v1.0.0beta-5 LDAP docker-compose template

### ISSUE THREAD

**Issue by ghost** [mealie-recipes/mealie#2402]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I have checked for existing issues that have been resolved in v1-beta

### What is the issue you are experiencing?

Hi there,

I would like to implement LDAP into my mealie installation and used the provided docker-compose template provided in the mealie documentation. I'm trying to connect to my Active Directory DC and added to LDAP env values. I'm learning LDAP/AD at moment so I apologize for not understanding it fully. My docker-compose.yml goes as follows:

```
---
version: "3.7"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-5
    container_name: mealie-frontend
    environment:
    # Set Frontend ENV Variables Here
      - API_URL=http://mealie-api:9000 #
      - LDAP_AUTH_ENABLED = true
      - LDAP_SERVER_URI=ldap://192.168.1.1:389/
      - LDAP_TLS_INSECURE = true
      - LDAP_BASE_DN = cn=users,dc=lab,dc=lan
      - LDAP_QUERY_BIND = cn=ldapuser,dc=lab,dc=lan
      - LDAP_QUERY_PASSWORD = password
      - LDAP_USER_FILTER = cn=users,dc=lab,dc=lan
      - LDAP_ID_ATTRIBUTE = userPrincipalName
      - LDAP_NAME_ATTRIBUTE = sAMAccount
      - LDAP_MAIL_ATTRIBUTE = mail
    restart: always
    ports:
      - "9925:3000" # 
    volumes:
      - mealie-data:/app/data/ # 
  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-5
    container_name: mealie-api
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - mealie-data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/Anchorage
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.example.com
    restart: always

volumes:
  mealie-data:
    driver: local
```

![image](https://github.com/hay-kot/mealie/assets/111548844/7f8ac800-fbdb-4d56-823c-b06885935b9e)

### Deployment

Docker (Linux)

### Mealie Version

v1.0.0beta-5

**Comment by cmintey** [comment]
It looks like you're currently running `v1.0.0beta-5` and the environment variables you have are for `nightly`. LDAP is not working in the beta5 so if you want to use it, you must be on nightly.

**Comment by ghost** [comment]
Hi cmintey,

I will give this a go thank you very much.

**Comment by ghost** [comment]
Hi there,

So I pulled the nightly images but the LDAP config still doesn't work.
I'm not sure where to put the ENV variables.
Would you be able to help out?

```
---
version: "3.7"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-nightly
    container_name: mealie-frontend
    environment:
    # Set Frontend ENV Variables Here
       - API_URL=http://mealie-api:9000 #
     restart: always
    ports:
       - "9925:3000" # 
    volumes:
      - mealie-data:/app/data/ # 
      - mealie-api:
    image: hkotel/mealie:api-nightly
    container_name: mealie-api
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - mealie-data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/Anchorage
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.example.com
      - LDAP_AUTH_ENABLED = true
      - LDAP_SERVER_URI=ldap://192.168.1.10:389/
      - LDAP_TLS_INSECURE = true
      - LDAP_BASE_DN = dc=example,dc=com
      - LDAP_QUERY_BIND = ldap.bind@example.com
      - LDAP_QUERY_PASSWORD = password
      - LDAP_USER_FILTER = cn=users,dc=example,dc=com
      - LDAP_ID_ATTRIBUTE = userPrincipalName
      - LDAP_NAME_ATTRIBUTE = sAMAccount
      - LDAP_MAIL_ATTRIBUTE = mail

    restart: always
volumes:
  mealie-data:
    driver: local
```
