### ISSUE TITLE
[Bug] Docker Caddy IP Forwarding Headers

### ISSUE THREAD

**Issue by jnortell** [mealie-recipes/mealie#2407]
Continuation of the original issue detailed in this PR: #2365 

When attempting to use a fail2ban regex filter on the "Incorrect username or password from *" log, the log always shows the internal IP of the front-end docker container.

From @hay-kot
This is likely due to a mis-configuration on the internal proxy that we use here https://github.com/hay-kot/mealie/blob/mealie-next/docker/frontend.Caddyfile
Probably just need to adjust it to forward the headers from the original request.

From @jecorn 
...But the caddy docs suggest that it should be easy to do add the relevant IP forwarding....

Issue created at the request of @jecorn

**Comment by jecorn** [comment]
This is my bad. I wrote and tested the IP logging code on a bare metal dev instance, forgetting that networking is different in a docker container. I’ll take care of this next week.

**Comment by jecorn** [comment]
Hmm. I need a hint from someone who uses the mealie docker dev container. I just confirmed that bare metal dev instance correctly gets IPs from two different machines (because there's no forwarding from outside a container to inside).. 

But when I tried to then recreate the problem with a docker dev container, I got stuck. I can access the container on the machine running the dev container via localhost:3000 or localhost:9000/docs. And in that case, the container reports failed logins as coming from 127.0.0.1, and not the docker network. But unlike the bare metal dev instance, the container seems to not be listening to other machines coming from outside localhost. A separate laptop that successfully connects to the bare metal dev instance can't do so for the docker dev instance. So I can't yet make sure that any changes I made are actually working.

Can someone working with docker dev give me a hint here about getting it to listen on the network? @hay-kot ?

**Comment by jnortell** [comment]
> Hmm. I need a hint from someone who uses the mealie docker dev container. I just confirmed that bare metal dev instance correctly gets IPs from two different machines (because there's no forwarding from outside a container to inside)..
> 
> But when I tried to then recreate the problem with a docker dev container, I got stuck. I can access the container on the machine running the dev container via localhost:3000 or localhost:9000/docs. And in that case, the container reports failed logins as coming from 127.0.0.1, and not the docker network. But unlike the bare metal dev instance, the container seems to not be listening to other machines coming from outside localhost. A separate laptop that successfully connects to the bare metal dev instance can't do so for the docker dev instance. So I can't yet make sure that any changes I made are actually working.
> 
> Can someone working with docker dev give me a hint here about getting it to listen on the network? @hay-kot ?

I'm unsure what exactly is being asked, so my apologies if this is irrelevant information. I'm able to access my container via another computer on the local network with 192.168.x.x:9925

Here is my docker compose setup:
```
version: "3.7"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-nightly
    container_name: mealie-frontend
    environment:
      - API_URL=http://mealie-api:9000
    restart: unless-stopped
    ports:
      - "9925:3000"
    volumes:
      - /path_to_data/mealie:/app/data/
    depends_on:
      - mealie-api
    networks:
      - <REDACTED>

  mealie-api:
    image: hkotel/mealie:api-nightly
    container_name: mealie-api
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - /path_to_data/mealie:/app/data/
    environment:
      - ALLOW_SIGNUP=false
      - PUID=<REDACTED>
      - PGID=<REDACTED>
      - TZ=America/New_York
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - DEFAULT_EMAIL=<REDACTED>
      - DEFAULT_GROUP=Home
      - BASE_URL=<REDACTED>
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_FROM_NAME=<REDACTED>
      - SMTP_AUTH_STRATEGY=TLS
      - SMTP_FROM_EMAIL=<REDACTED>
      - SMTP_USER=<REDACTED>
      - SMTP_PASSWORD=<REDACTED>
    restart: unless-stopped
    networks:
      - <REDACTED>
```
