### ISSUE TITLE
[BUG] - Import error on LDAP auth login

### ISSUE THREAD

**Issue by timosturm** [mealie-recipes/mealie#2514]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

Cannot login using LDAP auth because of error: `ImportError: libldap_r-2.4.so.2: cannot open shared object file: No such file or directory`

Apart from the LDAP configuration the docker-compose.yml I use is taken from the offical guide [here](https://nightly.mealie.io/documentation/getting-started/installation/postgres/).

### Steps to Reproduce

1. Setup the docker image as shown below
2. First login any user configured in LDAP
3. "Something went wrong"

### Please provide relevent logs

```
mealie-api       | ERROR: 21-Aug-23 12:37:02    Exception in ASGI application
mealie-api       | Traceback (most recent call last):
mealie-api       |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
mealie-api       |     result = await app(self.scope, self.receive, self.send)
mealie-api       |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
mealie-api       |     return await self.app(scope, receive, send)
mealie-api       |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
mealie-api       |     await super().__call__(scope, receive, send)
mealie-api       |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
mealie-api       |     await self.middleware_stack(scope, receive, send)
mealie-api       |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
mealie-api       |     raise exc
mealie-api       |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
mealie-api       |     await self.app(scope, receive, _send)
mealie-api       |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
mealie-api       |     await responder(scope, receive, send)
mealie-api       |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 43, in __call__
mealie-api       |     await self.app(scope, receive, self.send_with_gzip)
mealie-api       |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
mealie-api       |     raise exc
mealie-api       |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
mealie-api       |     await self.app(scope, receive, sender)
mealie-api       |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
mealie-api       |     raise e
mealie-api       |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
mealie-api       |     await self.app(scope, receive, send)
mealie-api       |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
mealie-api       |     await route.handle(scope, receive, send)
mealie-api       |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
mealie-api       |     await self.app(scope, receive, send)
mealie-api       |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
mealie-api       |     response = await func(request)
mealie-api       |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
mealie-api       |     raw_response = await run_endpoint_function(
mealie-api       |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
mealie-api       |     return await run_in_threadpool(dependant.call, **values)
mealie-api       |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
mealie-api       |     return await anyio.to_thread.run_sync(func, *args)
mealie-api       |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
mealie-api       |     return await get_asynclib().run_sync_in_worker_thread(
mealie-api       |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
mealie-api       |     return await future
mealie-api       |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
mealie-api       |     result = context.run(func, *args)
mealie-api       |   File "/app/./mealie/routes/auth/auth.py", line 58, in get_token
mealie-api       |     user = authenticate_user(session, email, password)  # type: ignore
mealie-api       |   File "/app/./mealie/core/security/security.py", line 120, in authenticate_user
mealie-api       |     return user_from_ldap(db, email, password)
mealie-api       |   File "/app/./mealie/core/security/security.py", line 51, in user_from_ldap
mealie-api       |     import ldap
mealie-api       |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/ldap/__init__.py", line 34, in <module>
mealie-api       |     import _ldap
mealie-api       | ImportError: libldap_r-2.4.so.2: cannot open shared object file: No such file or directory
```

### Mealie Version

v1.0.0-beta-5

### Deployment

Docker (Linux)

### Additional Deployment Details

```yaml
version: "3.7"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-5
    container_name: mealie-frontend
    depends_on:
      - mealie-api
    environment:
    # Set Frontend ENV Variables Here
      - API_URL=http://mealie-api:9000


    restart: unless-stopped
    ports:
      - "8095:3000"


    volumes:
      - mealie-data:/app/data/


  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-5
    container_name: mealie-api
    deploy:
      resources:
        limits:
          memory: 1000M


    depends_on:
      - postgres
    volumes:
      - mealie-data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=false
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
#      - BASE_URL=https://mealie.yourdomain.com

    # LDAP
      - LDAP_AUTH_ENABLED=True
      - LDAP_SERVER_URL=192.168.2.201:3890
      - LDAP_TLS_INSECURE=True
      - LDAP_BASE_DN=ou=people,dc=example,dc=com
      - LDAP_QUERY_BIND=uid=search_user,ou=people,dc=example,dc=com
      - LDAP_QUERY_PASSWORD=<password>
      - LDAP_USER_FILTER=(&(uid=*)(!(uid=search_user)))
      - LDAP_ADMIN_FILTER=(memberof=cn=lldap_admin,ou=groups,dc=example,dc=com)

    # Database Settings
      - DB_ENGINE=postgres
      - POSTGRES_USER=mealie
      - POSTGRES_PASSWORD=mealie
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mealie
    restart: unless-stopped

  postgres:
    container_name: mealie-postgres
    image: postgres
    restart: unless-stopped
    volumes:
      - ./mealie-pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mealie
      POSTGRES_USER: mealie

volumes:
  mealie-data:
  mealie-pgdata:
```
