### ISSUE TITLE
Is it possible to change the API port?

### ISSUE THREAD

**Issue by shimizurei** [mealie-recipes/mealie#2574]
The API sits on port 9000, which for me is already occupied by Portainer. When creating the container, I used the nightly docker-compose file to change it to 9004, but the only thing that showed up was a JSON page with `{"detail":"Not Found"}`.

My compose file

```yaml
version: "3.7"
services:
  mealie-omni:
    image: hkotel/mealie:omni-nightly
    container_name: mealie
    restart: always
    ports:
      - "8888:3000"
      - "9004:9000"
    volumes:
      - mealie-data:/app/data/
    environment:
      - ALLOW_SIGNUP=false
      - PUID=1000
      - PGID=1000
      - TZ=America/Anchorage
      - BASE_URL=http://192.168.0.XXX

volumes:
  mealie-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/to/mealie
```
