### ISSUE TITLE
[BUG] - Reloading HTTPS site requests HTTP site on some pages

### ISSUE THREAD

**Issue by Kuchenpirat** [mealie-recipes/mealie#2591]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

On the new single container setup reloading some pages is generating an HTTP request instead of an HTTPS request. This can lead to an 404 Error for users that allow secure connections only. The same is happening when opening the page in a new tab. 

Allowing unsecure connections (Port 80) into the container fixed the problem but the browser window is from now on running an unsecure HTTP session. 

Affected pages: 
- Profile Page (and all pages it leads to besides the recepie page)
  - Group Member Overview
  - Category Page
  - Recipe Tags
  - Tools
  - User Profile Edit 
  - Group Settings
  - Manage Cookbooks
  - Notifications
  - Manage Data
  - Data Migration
- Meal Planner
- Shopping list overview (but not the page for each specific shopping list)
- Timeline 
- Admin site Settings (and all pages it leads to)
  - Admin manage users
  - Admin manage groups
  - Backups
  - Maintenance
  - Background tasks
  - Parser

### Steps to Reproduce

- Install new single container mealie
- Configure reverse Proxy to only allow HTTPS connections into the container
- Reload any of the pages above and get greeted by an 404 error

### Please provide relevent logs

For every request there is a 307 Temporary Redirect Info log. 

INFO:     172.18.0.2:49984 - "GET /admin/manage/users HTTP/1.1" 307 Temporary Redirect

The Chrome Network Page shows that mealie redirects the request to an http ressource. 

![Screenshot 2023-10-04 110440](https://github.com/mealie-recipes/mealie/assets/24235032/30bd7458-e83d-496b-83c9-aafa5f6f0971)

### Mealie Version

The new Version does no longer have an functioning Version tag. I am currently running the newest version of the single container setup. 

### Deployment

Docker (Linux)

### Additional Deployment Details

```
mealie:
    image: ghcr.io/mealie-recipes/mealie:nightly
    container_name: mealie
    restart: "always"
    #ports: 
    #  - "9925:9000"
    volumes:
      - ./config/mealie:/app/data/
    environment:
      - ALLOW_SIGNUP=false
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.example.com
      - TOKEN_TIME=720

    labels: # traefik reverse proxy configuration
      - "traefik.enable=true"
      # HTTPS
      - "traefik.http.routers.mealie.entrypoints=websecure"
      - "traefik.http.routers.mealie.rule=Host(`mealie.example.com`)"
      - "traefik.http.routers.mealie.tls=true"
      - "traefik.http.routers.mealie.tls.certresolver=myresolver"
```
