### ISSUE TITLE
[BUG] - Password reset link being rewritten incorrectly

### ISSUE THREAD

**Issue by brheinfelder** [mealie-recipes/mealie#2620]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

I have an instance of Mealie I just set up and am reverse proxying to using nginx. Everything works fine except for the password reset link. The generated link is of the format:
https://mydomain.com:9000/reset-password?token=[insert generated token here]
Upon pasting into the browser, it gets automatically rewritten as follows (note the removal of the port number and the addition of a slash after 'reset-password'):
https://mydomain.com/reset-password/?token=[insert token here]
This generates a 404 page with my setup.
After some experimentation, I have discovered that the link works if I simply reinsert the port as follows:
https://mydomain.com:9000/reset-password/?token=[insert token here]

So either the link is being generated incorrectly, or rewritten incorrectly. I'm not entirely sure. My docker-compose and nginx configuration are included below. Any help would be much appreciated.

Nginx Config:
```
server {
        listen 9925 ssl http2;
        server_name mealie;
        ssl_certificate /storage/certs/fullchain.cer;
        ssl_certificate_key /storage/certs/key.key;
        location / {
                proxy_pass http://127.0.0.1:9000;
                proxy_set_header Host $host;
                proxy_set_header X-Real_IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto https;
        }
}
```

docker-compose:
```
---
version: "3.7"
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:nightly
    container_name: mealie
    ports:
        - "9000:9000" #


    deploy:
      resources:
        limits:
          memory: 1000M #


    volumes:
      - /opt/docker/mealie/data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=false
      - PUID=1000
      - PGID=1000
      - TZ=
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mydomain.com:9000
    restart: always

volumes:
  mealie-data:
    driver: local
```

### Steps to Reproduce

1) Setup as described above
2) Generate password reset link

### Please provide relevent logs

no relevant log entries. Clearly an issue with my setup

### Deployment

Docker (Linux)
