### ISSUE TITLE
[BUG] Adding dedicated IP with macvlan not working

### ISSUE THREAD

**Issue by realthore** [mealie-recipes/mealie#2675]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

I'm trying to setup mealie (portainer on Synology NAS) with a dedicated IP from my network using macvlan. This works on other containers using
```
networks:
      mvl:
        ipv4_address: 192.168.178.196
      networks:
        mvl:
          external: true
```
within the docker compose. When doing that with mealie
```
---
version: "3.7"
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.0.0-RC1.1
    container_name: mealie
    ports:
        - "9000:9000" # 
    networks:
      mvl:
        ipv4_address: 192.168.178.196
      networks:
        mvl:
          external: true
    deploy:
      resources:
        limits:
          memory: 2000M # 
    volumes:
      - mealie-data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1024
      - PGID=100
      - TZ=Europe/berlin
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.yourdomain.com
    restart: always

volumes:
  mealie-data:
    driver: local
```
I get an error message: 
"Deployment error
failed to deploy a stack: validating /data/compose/24/docker-compose.yml: services.mealie.networks.networks Additional property mvl is not allowed"
What am I doing wrong? 

### Steps to Reproduce

na

### Please provide relevent logs

na

### Deployment

Docker (Synology)
