### ISSUE TITLE
Https while accesing via IP missing 

### ISSUE THREAD

**Issue by ArthurHuyghe** [mealie-recipes/mealie#2716]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

I have installed Mealie on my synology, however I can't connect to it via https (https://10.0.0.10:9925/). using http works fine. I also noticed in the dashboard under configuration there is a warning sign next to `Secure Site`. 
The problem is that I can't seem to find a guide for configuring https, nor do I find any more info as to what that Secure Site warning means.

I also want to use SMTP but coudn't find documentation for it either beside the list with env variables, which isn't very helpful on its own. I would like to use my outlook email for this but haven't got it working on my own.

What should be set for the `BASE_URL`?

Hope someone could help me with this!

### Steps to Reproduce

Install Mealie using Docker.

### Please provide relevent logs

If I try connecting using https, I get a error in the log stating `WARNING: Invalid HTTP request received.`

### Mealie Version

v1.0.0-RC1.1

### Deployment

Docker (Synology)

### Additional Deployment Details

My Docker Compose file:
```
version: "3.7"
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.0.0-RC1.1
    container_name: mealie
    ports:
        - "9925:9000" # 
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - /volume1/docker/mealie:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://localhost
    restart: always

volumes:
  mealie-data:
    driver: local
```
