### ISSUE TITLE
[BUG] - Scale function in portions for recipes don't increment or decrement by 1

### ISSUE THREAD

**Issue by Yannou90** [mealie-recipes/mealie#2896]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When clicking on add or remove "portion" in recipe, a factor is appliqued , but no increment by 1 or decrement by 1

For the example, in a recipe I have 6 portions.

If I click on "plus" button, it's now 12 portions, like 6->1, 12->2.

I understand the scale factor but it's not intuitive: 
1. click on button : it is 1 for factor, I want 3 portion
2. add some math function to find the good factor : 6/2 = 3 => 1/2 = 0.5
3. apply factor : replace 1 by 0.5 -> great I have 3 portions!

If x is the number of portions in original recipe, then
6/6 = 1 -> x/x = 1
1 is the original factor from recipe.

Now if we increment by 1 -> 7/6 => (x+1)/x
If we decrement by 1 -> 5/6 => (x-1)/x

All ingredient is calculated in a more easy way and end user should easily apply the number of  portions without doing math.

I found this:
https://github.com/mealie-recipes/mealie/blob/mealie-next/frontend/components/Domain/Recipe/RecipeScaleEditButton.vue

But I don't know how to replace the scale value, I can't help.

I try some other recipe manager, but no one is great like mealie. It's the only annoying thing I found for now.

Thank's for your hard work

### Steps to Reproduce

1. Open recipe
2. Increment by clicking plus button
3. Factor is appliqued, not increment

### Please provide relevant logs

No log, all work great, but it's for me a non-sens like the "portion" button work

### Mealie Version

Version
v1.0.0-RC2

Build
c9852daf0e213dc4cadf97971c7787cf6fc66dfc

### Deployment

Other (please specify below)

### Additional Deployment Details

Operating System: Debian GNU/Linux 12 (bookworm)  
 Kernel: Linux 6.1.0-16-amd64
Architecture: x86-64

I use podman for rootless docker :
podman version 4.3.1

mealie:v1.0.0-RC2

docker-compose.yalm:

```
version: "3.7"
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.0.0-RC2
    container_name: mealie
    ports:
        - 9000:9000
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - /home/yannou90/Podman/mealie/data:/app/data
    environment:
      - PRODUCTION=true
      - IS_DEMO=false
      - AUTO_BACKUP_ENABLED=true
      - DEFAULT_GROUP=Maison
      - DB_ENGINE=sqlite
      - ALLOW_SIGNUP=false
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=http://192.168.0.11:9000
      - SECURITY_MAX_LOGIN_ATTEMPTS=3
      - SECURITY_USER_LOCKOUT_TIME=24
      - API_DOCS=True
      - API_PORT=9000
    restart: unless-stopped
    healthcheck:
      disable: true
```
