### ISSUE TITLE
I can't add any new recipes.

### ISSUE THREAD

**Issue by Manny8787** [mealie-recipes/mealie#2977]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I can't add any new recipes, every new url added come sback with the error. 

I have even deleted recipes that have already been successfully added, copied the orignal URL and tried to re-add them with the same error. I haven't changed anything since the container was working. 

### Steps to Reproduce

add new recipe from url, copy and paste url. 

### Please provide relevant logs

"Only websites containing ld+json or microdata can be imported by Mealie. Most major recipe websites support this data structure. If your site cannot be imported but there is json data in the log, please submit a github issue with the URL and data. "

### Mealie Version

```yaml
version: "3.7"
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.0.0-RC2
    container_name: mealie
    ports:
        - 9925:9000
    volumes:
      - /share/CACHEDEV1_DATA/appdata/mealie/app:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1001
      - PGID=1000
      - TZ=Europe/Paris
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=***************************
      
       #Email Configuration
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_FROM_NAME=Mealie
      - SMTP_AUTH_STRATEGY=TLS
      - SMTP_FROM_EMAIL=*******************
      - SMTP_USER=**************************
      - SMTP_PASSWORD=********************
    restart: always
```

### Deployment

Other (please specify below)

### Additional Deployment Details

Qnap Container Station
