### ISSUE TITLE
[BUG] - cannot import name 'main' on pi4 mealie:v1.1.1

### ISSUE THREAD

**Issue by firefly2442** [mealie-recipes/mealie#3117]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I have an issue that seems to only occur on the `mealie:v1.1.1` but if I back out to `mealie:v1.1.0` it goes away. 

### Steps to Reproduce

`docker-compose.yaml`

```
version: "3.1"
services:
  mealie:
    container_name: mealie
    # image: hkotel/mealie:v0.5.6 # old image
    image: ghcr.io/mealie-recipes/mealie:latest
    restart: unless-stopped
    ports:
      - 9925:9000
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Denver

      # Default Recipe Settings
      RECIPE_PUBLIC: "true"
      RECIPE_SHOW_NUTRITION: "true"
      RECIPE_SHOW_ASSETS: "true"
      RECIPE_LANDSCAPE_VIEW: "true"
      RECIPE_DISABLE_COMMENTS: "false"
      RECIPE_DISABLE_AMOUNT: "false"

      # Gunicorn
      WEB_CONCURRENCY: 1
      # WORKERS_PER_CORE: 0.5
      MAX_WORKERS: 1
    volumes:
      - ./data/:/app/data
 ````

### Please provide relevant logs

```
usermod: no changes
Switching to dedicated user

        User uid:    1000
        User gid:    1000
        
Traceback (most recent call last):
  File "/opt/poetry/bin/poetry", line 5, in <module>
    from poetry.console.application import main
ImportError: cannot import name 'main' from 'poetry.console.application' (/opt/poetry/venv/lib/python3.10/site-packages/poetry/console/application.py)
/app/run.sh: line 51: /opt/pysetup/.venv/bin/uvicorn: Success
```

### Mealie Version

`mealie:v1.1.1`

### Deployment

Docker (Linux)

### Additional Deployment Details

Docker on Raspberry Pi4, Ubuntu OS.
