### ISSUE TITLE
[BUG] - alembic.util.exc.CommandError: Path doesn't exist: '/alembic'

### ISSUE THREAD

**Issue by cbaeyens** [mealie-recipes/mealie#3201]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I am trying to install Mealie on a docker container using a pre-existing Postgresql. After installation I was not able to log in using the default credentials. I found in another bug report that the cause could be that the database already existed during installation. This was the case because the sql-user for mealie doesn't have permission to create a database, so I created one on beforehand. The solution given in that thread was then to run init_db.py. This was the result:

`root@docker:~/docker/mealie# docker exec mealie python /app/mealie/db/init_db.py
INFO: 20-Feb-24 17:43:03        Database connection established.
Traceback (most recent call last):
  File "/app/mealie/db/init_db.py", line 113, in <module>
    main()
  File "/app/mealie/db/init_db.py", line 91, in main
    if db_is_at_head(alembic_cfg):
  File "/app/mealie/db/init_db.py", line 49, in db_is_at_head
    directory = script.ScriptDirectory.from_config(alembic_cfg)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/base.py", line 226, in from_config
    return ScriptDirectory(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/base.py", line 107, in __init__
    raise util.CommandError(
alembic.util.exc.CommandError: Path doesn't exist: '/alembic'.  Please use the 'init' command to create a new scripts folder.`

When I execute the init script, this was the result:
`root@docker:~/docker/mealie# docker exec mealie python /opt/poetry/venv/lib/python3.10/site-packages/poetry/console/commands/init.py
Traceback (most recent call last):
  File "/opt/poetry/venv/lib/python3.10/site-packages/poetry/console/commands/init.py", line 12, in <module>
    from cleo.helpers import option
ModuleNotFoundError: No module named 'cleo'`

### Steps to Reproduce

1) Create database 'mealie' on preexisting postgresql
2) Install mealie docker container
3) Notice you can't log in into the UI given the default credentials and notice database is empty
4) Run `docker exec mealie python /app/mealie/db/init_db.py`

### Please provide relevant logs

[docker compose log.txt](https://github.com/mealie-recipes/mealie/files/14348861/docker.compose.log.txt)

### Mealie Version

[ghcr.io/mealie-recipes/mealie:v1.1.0]

### Deployment

Docker (Linux)

### Additional Deployment Details

Pre-existing postgres

**Comment by hay-kot** [comment]
Could you post your docker compose file? (without it's secrets)

**Comment by cbaeyens** [comment]
Here you go.
```
---
version: "3.7"
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.1.0 # 
    container_name: mealie
    ports:
        - "9925:9000" # 
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - mealie-data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.local

    # Database Settings
      - DB_ENGINE=postgres
      - POSTGRES_USER=[redacted]
      - POSTGRES_PASSWORD=[redacted]
      - POSTGRES_SERVER=192.168.1.35
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mealie
    restart: always

volumes:
  mealie-data:
    driver: local
```
