### ISSUE TITLE
[BUG] - Mealie won't load.

### ISSUE THREAD

**Issue by brandon-daniels** [mealie-recipes/mealie#3476]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

The site won't load.

### Steps to Reproduce

Navigate to https://demo.mealie.io/ and it will not load. Same with my self-hosted version.

### Please provide relevant logs

Switching to dedicated user

        User uid:    1000
        User gid:    1000

INFO     2024-04-16T16:57:58 - Started server process [1]
INFO     2024-04-16T16:57:58 - Waiting for application startup.
INFO     2024-04-16T16:57:58 - start: database initialization
INFO     2024-04-16T16:57:58 - Database connection established.
INFO     2024-04-16T16:57:58 - Context impl SQLiteImpl.
INFO     2024-04-16T16:57:58 - Will assume non-transactional DDL.
INFO     2024-04-16T16:57:58 - Migration needed. Performing migration...
INFO     2024-04-16T16:57:58 - Context impl SQLiteImpl.
INFO     2024-04-16T16:57:58 - Will assume non-transactional DDL.
INFO     2024-04-16T16:57:58 - Running upgrade 09aba125b57a -> d7c6efd2de42, migrate favorites and ratings to user_ratings
INFO     2024-04-16T16:57:58 - Checking for migration data fixes
INFO     2024-04-16T16:57:58 - end: database initialization
INFO     2024-04-16T16:57:58 - -----SYSTEM STARTUP-----
INFO     2024-04-16T16:57:58 - ------APP SETTINGS------
INFO     2024-04-16T16:57:58 - {
    "theme": {
        "light_primary": "#E58325",
        "light_accent": "#007A99",
        "light_secondary": "#973542",
        "light_success": "#43A047",
        "light_info": "#1976D2",
        "light_warning": "#FF6D00",
        "light_error": "#EF5350",
        "dark_primary": "#E58325",
        "dark_accent": "#007A99",
        "dark_secondary": "#973542",
        "dark_success": "#43A047",
        "dark_info": "#1976D2",
        "dark_warning": "#FF6D00",
        "dark_error": "#EF5350"
    },
    "PRODUCTION": true,
    "BASE_URL": "http://localhost:8080",
    "STATIC_FILES": "/spa/static",
    "IS_DEMO": false,
    "HOST_IP": "*",
    "API_HOST": "0.0.0.0",
    "API_PORT": 9000,
    "API_DOCS": true,
    "TOKEN_TIME": 48,
    "LOG_CONFIG_OVERRIDE": null,
    "LOG_LEVEL": "info",
    "GIT_COMMIT_HASH": "6bd5a82b928a672e1c592269af9858bd23975a69",
    "ALLOW_SIGNUP": false,
    "SECURITY_MAX_LOGIN_ATTEMPTS": 5,
    "SECURITY_USER_LOCKOUT_TIME": 24,
    "DB_ENGINE": "sqlite",
    "DEFAULT_GROUP": "Home",
    "SMTP_HOST": null,
    "SMTP_PORT": "587",
    "SMTP_FROM_NAME": "Mealie",
    "SMTP_FROM_EMAIL": null,
    "SMTP_AUTH_STRATEGY": "TLS",
    "LDAP_AUTH_ENABLED": false,
    "LDAP_SERVER_URL": null,
    "LDAP_TLS_INSECURE": false,
    "LDAP_TLS_CACERTFILE": null,
    "LDAP_ENABLE_STARTTLS": false,
    "LDAP_BASE_DN": null,
    "LDAP_QUERY_BIND": null,
    "LDAP_QUERY_PASSWORD": null,
    "LDAP_USER_FILTER": null,
    "LDAP_ADMIN_FILTER": null,
    "LDAP_ID_ATTRIBUTE": "uid",
    "LDAP_MAIL_ATTRIBUTE": "mail",
    "LDAP_NAME_ATTRIBUTE": "name",
    "OIDC_AUTH_ENABLED": false,
    "OIDC_CLIENT_ID": null,
    "OIDC_CONFIGURATION_URL": null,
    "OIDC_SIGNUP_ENABLED": true,
    "OIDC_USER_GROUP": null,
    "OIDC_ADMIN_GROUP": null,
    "OIDC_AUTO_REDIRECT": false,
    "OIDC_PROVIDER_NAME": "OAuth",
    "OIDC_REMEMBER_ME": false,
    "OIDC_SIGNING_ALGORITHM": "RS256",
    "OIDC_USER_CLAIM": "email",
    "TESTING": false
}
INFO     2024-04-16T16:57:58 - Application startup complete.
INFO     2024-04-16T16:57:58 - Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
INFO     2024-04-16T16:58:17 - [127.0.0.1:60576] 200 OK "GET /api/app/about HTTP/1.1"

### Mealie Version

v1.5.0
hkotel/mealie:latest

### Deployment

Docker (Linux)

### Additional Deployment Details

Sorry if you are already aware.

**Comment by michael-genson** [comment]
Do you have any other logs? There are no errors in the logs you provided

**Comment by brandon-daniels** [comment]
No other logs from the docker container. I can also add my compose file, but I figured since the demo site isn't loading for me on any device/network that my particular installation isn't the problem.

**Comment by michael-genson** [comment]
The demo being down is unrelated to any bug, there was an issue with the demo, so the issue you're experiencing is likely related to your deployment. Without any logs or other details I'm not sure how to help

**Comment by brandon-daniels** [comment]
Here is my compose file. Any ideas for where else I can look for logs? Part of my problem is that the container logs has no errors. 

Sorry for assuming my problem was the same as the demo!

```
    mealie:
        container_name: mealie
        image: hkotel/mealie:latest
        restart: always
        ports:
          - 9925:80
        environment:
          PUID: 1000
          PGID: 1000
          TZ: America/Denver

          # Default Recipe Settings
          RECIPE_PUBLIC: 'true'
          RECIPE_SHOW_NUTRITION: 'false'
          RECIPE_SHOW_ASSETS: 'true'
          RECIPE_LANDSCAPE_VIEW: 'true'
          RECIPE_DISABLE_COMMENTS: 'true'
          RECIPE_DISABLE_AMOUNT: 'false'
        volumes:
          - /home/brandon/mealie/data/:/app/data
```
