### ISSUE TITLE
[BUG] - Warning about `/run/secrets` not existing on startup

### ISSUE THREAD

**Issue by felixschndr** [mealie-recipes/mealie#3885]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When starting Mealie the logs states the following:
```text
mealie_app        | Switching to dedicated user
mealie_app        |
mealie_app        |         User uid:    1000
mealie_app        |         User gid:    1000
mealie_app        |
mealie_app        | /opt/pysetup/.venv/lib/python3.10/site-packages/pydantic_settings/sources.py:431: UserWarning: directory "/run/secrets" does not exist
mealie_app        |   warnings.warn(f'directory "{self.secrets_path}" does not exist')
mealie_app        | INFO     2024-07-11T21:58:16 - Started server process [1]
mealie_app        | INFO     2024-07-11T21:58:16 - Waiting for application startup.
....
```

It `warn`s about the directory `/run/secrets` not existing. This error does not cause any issues as Mealie continues to start up afterwards.

This issue is raised as a followup on https://github.com/mealie-recipes/mealie/issues/3852#issuecomment-2211619896

### Steps to Reproduce

docker-compose.yml
```yaml
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie
    container_name: mealie_app
    ports:
        - 12000:9000
    deploy:
      resources:
        limits:
          memory: 400M
    volumes:
      - ./data/mealie:/app/data/
    environment:
      ALLOW_SIGNUP: "false"
      PUID: ${ENV_PUID}
      PGID: ${ENV_PGID}
      TZ: ${TIMEZONE}
      API_DOCS: "false"
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      DB_ENGINE: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SERVER: mealie_database
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      ...
    restart: always
    depends_on:
      - database
```
Start Mealie with docker compose and check the logs

### Please provide relevant logs

```
/opt/pysetup/.venv/lib/python3.10/site-packages/pydantic_settings/sources.py:431: UserWarning: directory "/run/secrets" does not exist
```

### Mealie Version

Version
: v1.10.1
Build
: [d639d168fa7c39ffb802d46ba05e4ec4de33faf9](https://github.com/mealie-recipes/mealie/commit/d639d168fa7c39ffb802d46ba05e4ec4de33faf9)

### Deployment

Docker (Linux)
