### ISSUE TITLE
[BUG] - Unable to change theme color, verified env variable exists. 

### ISSUE THREAD

**Issue by DanielShmu** [mealie-recipes/mealie#4094]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I am unable to change the theme color even though I have started the container with the env variable changed while following the backend configuration guide for the theme. I inputted THEME_DARK_PRIMARY: "#F598CE" inside the docker compose file. I also tried deleting and repulling the container and still same issue. 

### Steps to Reproduce

Used docker compose with the following data:
```

version: "3" # Specifies the version of the Docker Compose file format

# Service definitions for the big-bear-mealie application
services:
  # Service name: app
  # The `app` service definition
  app:
    # Name of the container
    container_name: mealie

    # Image to be used for the container
    image: hkotel/mealie:latest

    # Container restart policy
    restart: unless-stopped

    # Volumes to be mounted to the container
    volumes:
      # Mounting the docker volume to /app/data inside the container
      - mealie_data:/app/data

    # Ports mapping between host and container
    ports:
      # Mapping port 9925 of the host to port 9000 of the container
      - "9925:9000"
     
    environment:
      THEME_DARK_PRIMARY: "#F598CE"

# Volumes
volumes:
  # Define a named volume for data persistence
  mealie_data:

```
### Please provide relevant logs

Here are the logs indicating the variable exists inside of the container: 
    "theme": {
        "light_primary": "#E58325",
        "light_accent": "#007A99",
        "light_secondary": "#973542",
        "light_success": "#43A047",
        "light_info": "#1976D2",
        "light_warning": "#FF6D00",
        "light_error": "#EF5350",
        **"dark_primary": "#F598CE",**
        "dark_accent": "#007A99",
        "dark_secondary": "#973542",
        "dark_success": "#43A047",
        "dark_info": "#1976D2",
        "dark_warning": "#FF6D00",
        "dark_error": "#EF5350"
    },

showing all the variables:

docker exec mealie env
PATH=/opt/poetry/bin:/opt/pysetup/.venv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=d653a569b264
**THEME_DARK_PRIMARY=#F598CE**
LANG=C.UTF-8
GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D
PYTHON_VERSION=3.10.14
PYTHON_PIP_VERSION=23.0.1
PYTHON_SETUPTOOLS_VERSION=65.5.1
PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/66d8a0f637083e2c3ddffc0cb1e65ce126afb856/public/get-pip.py
PYTHON_GET_PIP_SHA256=6fb7b781206356f45ad79efbb19322caa6c2a5ad39092d0d44d0fec94117e118
MEALIE_HOME=/app
PYTHONUNBUFFERED=1
PYTHONDONTWRITEBYTECODE=1
PIP_NO_CACHE_DIR=off
PIP_DISABLE_PIP_VERSION_CHECK=on
PIP_DEFAULT_TIMEOUT=100
POETRY_HOME=/opt/poetry
POETRY_VIRTUALENVS_IN_PROJECT=true
POETRY_NO_INTERACTION=1
PYSETUP_PATH=/opt/pysetup
VENV_PATH=/opt/pysetup/.venv
PRODUCTION=true
TESTING=false
GIT_COMMIT_HASH=0d06494bbfc62fc8a1771a85fd308190891d6167
LD_LIBRARY_PATH=/usr/local/lib
APP_PORT=9000
STATIC_FILES=/spa/static
HOST=0.0.0.0
HOME=/root

This is from the API endpoint /api/app/about/theme, showing that its using the old variable

{
  "lightPrimary": "#E58325",
  "lightAccent": "#007A99",
  "lightSecondary": "#973542",
  "lightSuccess": "#43A047",
  "lightInfo": "#1976D2",
  "lightWarning": "#FF6D00",
  "lightError": "#EF5350",
  **"darkPrimary": "#E58325",**
  "darkAccent": "#007A99",
  "darkSecondary": "#973542",
  "darkSuccess": "#43A047",
  "darkInfo": "#1976D2",
  "darkWarning": "#FF6D00",
  "darkError": "#EF5350"
}

### Mealie Version

latest image

### Deployment

Docker (Linux)
