### ISSUE TITLE
[BUG] - Wrong content-type returned for webp images

### ISSUE THREAD

**Issue by jerobins** [mealie-recipes/mealie#4144]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [x] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When retrieving an image for a recipe, the content-type in the resulting response is: text/plain

Expected content type for a webp image is: image/webp

### Steps to Reproduce

curl -D - -o temp 'http://192.168.1.11:9925/api/media/recipes/87ce09ef-03a1-4053-90a4-7217714551e2/images/min-original.webp'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/1.1 200 OK
date: Tue, 03 Sep 2024 00:57:14 GMT
server: uvicorn
content-type: text/plain; charset=utf-8
content-length: 23846
last-modified: Mon, 08 Apr 2024 11:23:56 GMT
etag: "942d7915d22b932bf801600128381c65"

### Please provide relevant logs

none relevant

### Mealie Version

**Details**
Version: v1.12.0
Build: 0d06494bbfc62fc8a1771a85fd308190891d6167
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: postgres
Recipe Scraper Version: 15.0.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
OIDC Ready: No
OpenAI Ready: No
Email Configured: No

### Deployment

Docker (Linux)

### Additional Deployment Details

```
  mealie:
    container_name: mealie
    image: ghcr.io/mealie-recipes/mealie:latest
    ports:
      - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    depends_on:
      - postgres
    volumes:
      - /srv/mealie_data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TOKEN_TIME=9600
      - TZ=America/New_York
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=http://quark/

    # Database Settings
      - DB_ENGINE=postgres
```
