### ISSUE TITLE
[BUG] - Searching for "Ris-oat-o" doesn't find it

### ISSUE THREAD

**Issue by nununo** [mealie-recipes/mealie#4208]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I have a recipe called "Ris-oat-o" which was imported from here: https://food52.com/recipes/21577-ris-oat-o

But when I search for "Ris-oat-o" (without the quotes of course) it is not found.

### Steps to Reproduce

When I search for "Ris-oat-o" (without the quotes of course) it is not found:
<img width="849" alt="image" src="https://github.com/user-attachments/assets/c287bcb7-d706-4cfa-b52e-a9976f0f4735">

And yet if I search for "Risot" it is found probably because the word "Risotto" is part of the recipe description:
<img width="848" alt="image" src="https://github.com/user-attachments/assets/8364371a-17f0-4461-a7f6-7b4e808abb79">

I tried to replicate this in the demo site and it works fine in the demo site. Maybe because the search engine of the demo site is different?

### Please provide relevant logs

NA

### Mealie Version

Version: v1.12.0 [0d06494bbfc62fc8a1771a85fd308190891d6167](https://github.com/mealie-recipes/mealie/commit/0d06494bbfc62fc8a1771a85fd308190891d6167)

Docker-compose:
```yaml
version: '3.5'

volumes:
  data:

services:
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    restart: unless-stopped
    environment:
      DB_TYPE: sqlite
      TOKEN_TIME: 999999
      TZ: Europe/Lisbon
    env_file: mealie.env
    volumes:
      - data:/app/data
```

### Deployment

Docker (Linux)

### Additional Deployment Details

A Debian VM running on Proxmox.
