### ISSUE TITLE
[BUG] - Postgres connections fail if dollar sign (`$`) exists in password

### ISSUE THREAD

**Issue by andrewvaughan** [mealie-recipes/mealie#4224]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When creating Mealie with Docker, if the Postgres password contains a dollar sign, it cannot connect. Connections work fine from all other containers (e.g., pgAdmin and simply using `psql` from another contianer) leading this to likely be an issue with how Mealie is generating Postgres connection strings or similar.

Removing the dollar signs from the password corrected the issue.

### Steps to Reproduce

Docker compose config, similar to:

```yaml
services:
  mealie:
    container_name : "mealie"
    image          : "ghcr.io/mealie-recipes/mealie:latest"

    depends_on:
      postgres-mealie:
        condition: "service_started"

    networks:
      - "reverse-proxy"
      - "postgres-mealie"

    volumes:
      - "mealie-app:/app/data"

    environment:
      # ...
      DB_ENGINE: "postgres"
      POSTGRES_SERVER: "postgres-mealie"
      POSTGRES_DB: "mealie"
      POSTGRES_USER: "mealie"
      POSTGRES_PASSWORD: "Test$$1234" # fails, but `Test1234` is fine
```

### Please provide relevant logs

```
$ sudo docker compose up mealie
[+] Running 2/2
 ✔ Container postgres-mealie  Running                                                                                                                                             0.0s
 ✔ Container mealie           Recreated                                                                                                                                           0.2s
Attaching to mealie
mealie  | Switching to dedicated user
mealie  |
mealie  |         User uid:    1000
mealie  |         User gid:    1000
mealie  |
mealie  | INFO     2024-09-17T13:34:00 - Started server process [1]
mealie  | INFO     2024-09-17T13:34:00 - Waiting for application startup.
mealie  | INFO     2024-09-17T13:34:00 - start: database initialization
mealie  | ERROR    2024-09-17T13:34:00 - Error connecting to database: (psycopg2.OperationalError) connection to server at "postgres-mealie" (172.19.0.3), port 5432 failed: FATAL:  password authentication failed for user "mealie"
```

### Mealie Version

`ghcr.io/mealie-recipes/mealie:latest`

### Deployment

Docker (Linux)
