### ISSUE TITLE
API Time Zone is different to Mealie Time Zone set in ENV, posting wrong meal of the day on API request.

### ISSUE THREAD

**Issue by mopedy** [mealie-recipes/mealie#4263]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Setting the TZ in the docker env to Australia/Adelaide does not change the timezone for API requests.
This causes the Meal of the day request via API rest request to change @UTC time instead of the set Timezone.

### Steps to Reproduce

Meal Plan
![image](https://github.com/user-attachments/assets/b9a2327b-f73e-4768-a534-db62c129afac)

Homeassistant Rest Sensor
![image](https://github.com/user-attachments/assets/b05a055b-06fb-483c-b162-2fe0ea09dbfd)

Docker Container Time
![image](https://github.com/user-attachments/assets/cfa9be8c-44b3-4b14-9d67-e470940e33be)

### Please provide relevant logs

[_mealie_logs (3).txt](https://github.com/user-attachments/files/17105775/_mealie_logs.3.txt)

### Mealie Version

**Details**
Version: v1.12.0
Build: 0d06494bbfc62fc8a1771a85fd308190891d6167
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 15.0.0

**Checks**
Secure Site: No
Server Side Base URL: Yes
LDAP Ready: No
OIDC Ready: No
OpenAI Ready: No
Email Configured: No

[docker.io/ghcr.io/mealie-recipes/mealie:v1.12.0](http://192.168.1.116:9000/#!/2/docker/images/docker.io~2Fghcr.io~2Fmealie-recipes~2Fmealie%3Av1.12.0)

### Deployment

Docker (Synology)

**Comment by boc-the-git** [comment]
How is the HA sensor being created?

**Comment by mopedy** [comment]
I create it as sensor entity in config.
![image](https://github.com/user-attachments/assets/63bed379-d9fc-4162-9d58-b169dfc50779)

Not sure if it helps but it has the correct meal in the calender in HA, just the picture in camera entity that is created with the generic camera does not match until 09:30am

![image](https://github.com/user-attachments/assets/9e63f46b-04d2-4ed3-a9bf-f53314b57412)
  
http://192.168.1.116:9925/api/media/recipes/{{states('sensor.mealie_todays_meal_id')}}/images/min-original.webp 

It seems Mealie integration and Mealie use the set TZ of ACST which is UTC +9:30 but the API uses UTC.

Thanks for looking into this.

**Comment by fabianluque** [comment]
Can confirm same happening to me. I'm on EST time, have a similar sensor configured in HA:

```
rest:
  - headers:
      Authorization: >
        Bearer  ---
    scan_interval: 60
    resource: http://homeassistant:9925/api/households/mealplans/today
    sensor:
      - name: "Meal of the Day"
        value_template: "{{ value_json[0].recipe.name }} "
        json_attributes_path: "$.[0].recipe"
        json_attributes:
          - id
```

My sensor changes to the next meal around 8pm EST time:

![image](https://github.com/user-attachments/assets/1692b3b5-7308-423e-aa98-a3db5dcdadd0)
