### ISSUE TITLE
Configuration issues

### ISSUE THREAD

**Issue by starlord998** [mealie-recipes/mealie#4443]
Relatively new to docker. I have  setup Mealie on my Synology NAS in a docker container with the following docker-compose.
---
version: "3.8"

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest 
    container_name: mealie
    restart: always
    ports:
        - "9925:9000" # 
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - /volume1/docker/mealie/mealie-data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "true"
      PUID: 1030
      PGID: 100
      TZ: America/Chicago
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://mealie.xxx.me
      API_PORT: 9000
      LOG_LEVEL: debug
    # GMAIL
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_FROM_NAME: username@gmail.com
      SMTP_AUTH_STRATEGY: TLS
      SMTP_FROM_EMAIL: username@gmail.com
      SMTP_USER: username@gmail.com
      SMTP_PASSWORD: <password>
    # OPENAI
      OPENAI_BASE_URL: https://api.openai.com/v1
      OPENAI_MODEL: gpt-4
      OPENAI_WORKERS: 2
      OPENAI_CUSTOM_HEADERS:
      OPENAI_CUSTOM_PARAMS:
      OPENAI_REQUEST_TIMEOUT: 90
      OPENAI_SEND_DATABASE_DATA: "true"
      OPENAI_ENABLE_IMAGE_SERVICES: "True"
      OPENAI_API_KEY: <OpenAI API key here>
    # Database Settings
      DB_ENGINE: postgres
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: mealie
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mealie
    depends_on:
      postgres:
        condition: service_healthy
    
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    volumes:
      - /volume1/docker/mealie/mealie-pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mealie
      POSTGRES_USER: mealie
      PGUSER: mealie
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 60s
      timeout: 60s
      retries: 3
   

volumes:
  mealie-data:
  mealie-pgdata:

I am able to deploy the container without errors and able to create the admin user and manually add recipes.

Issues:
1. I am unable to Import recipes via URL: I get an error "looks like we couldn't find anything". I tried various sites such as allrecipes.com. I think I see the following in the logs INFO     2024-10-24T12:08:38 - [104.28.104.25:0] 405 Method Not Allowed "POST /api/recipes/create-url HTTP/1.1"
2. When I go to site settings: the application versions (null) and the General About keeps saying "Loading"
3. The OpenAI is not ready: I have a paid subscription to OpenAI and create the API key but no luck.

I do see this error in the log
DEBUG    2024-10-24T11:50:11 - Running hourly callbacks
ERROR    2024-10-24T11:50:11 - Error in scheduled task func='locked_user_reset': exception='AllRepositories.__init__() got an unexpected keyword argument 'user_id''

I think these issues are somehow related to so networking issues.
I am able to send test emails to my gmail account without any issues.

Love the program otherwise any direction would be appreciated. Cheers.

**Comment by michael-genson** [comment]
Can you wrap your `yaml` in triple backticks? It makes it easier to read.

````
```yaml
YOUR-YAML-HERE
```
````

How exactly are you deploying via Synology? There are a few different ways of using docker compose (using projects, via SSH, etc.).

Regarding OpenAI, you can remove the `OPENAI_BASE_URL` environment variable entirely, it will default to the correct endpoint. Also, make sure you actually supplied your API key in your real docker compose config (it's empty in the config you shared)

**Comment by michael-genson** [comment]
> Error in scheduled task func='locked_user_reset'

Don't worry about that, that's a bug (which has been fixed in nightly) but it won't impact anything you're seeing here.

**Comment by starlord998** [comment]
> Can you wrap your `yaml` in triple backticks? It makes it easier to read.
> 
> 
> 
> ````
> 
> ```yaml
> 
> YOUR-YAML-HERE
> 
> ```
> 
> ````
> 
> 
> 
> How exactly are you deploying via Synology? There are a few different ways of using docker compose (using projects, via SSH, etc.).
> 
> 
> 
> Regarding OpenAI, you can remove the `OPENAI_BASE_URL` environment variable entirely, it will default to the correct endpoint. Also, make sure you actually supplied your API key in your real docker compose config (it's empty in the config you shared)

I am deploying via portainer by creating a stack. 
Regarding the openAI, I will remove the base URL. I do have my API in my actual docker compose.

**Comment by michael-genson** [comment]
Can you edit your post to surround your yaml in triple backticks?

**Comment by starlord998** [comment]
```
version: "3.8"

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: always
    ports:
      - "9925:9000" #
    deploy:
      resources:
        limits:
          memory: 1000M #
    volumes:
      - /volume1/docker/mealie/mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "true"
      PUID: 1030
      PGID: 100
      TZ: America/Chicago
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://mealie.xxx.me
      API_PORT: 9000
      LOG_LEVEL: debug
      # GMAIL
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_FROM_NAME: username@gmail.com
      SMTP_AUTH_STRATEGY: TLS
      SMTP_FROM_EMAIL: username@gmail.com
      SMTP_USER: username@gmail.com
      SMTP_PASSWORD:
      # OPENAI
      OPENAI_BASE_URL: https://api.openai.com/v1
      OPENAI_MODEL: gpt-4
      OPENAI_WORKERS: 2
      OPENAI_CUSTOM_HEADERS:
      OPENAI_CUSTOM_PARAMS:
      OPENAI_REQUEST_TIMEOUT: 90
      OPENAI_SEND_DATABASE_DATA: "true"
      OPENAI_ENABLE_IMAGE_SERVICES: "True"
      OPENAI_API_KEY:
      # Database Settings
      DB_ENGINE: postgres
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: mealie
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mealie
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    volumes:
      - /volume1/docker/mealie/mealie-pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mealie
      POSTGRES_USER: mealie
      PGUSER: mealie
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 60s
      timeout: 60s
      retries: 3

volumes:
  mealie-data:
  mealie-pgdata:

```

My apologies. The copy and paste had stripped the formatting the first time.
