### ISSUE TITLE
[BUG] - Paprika recipe migration upload submission not working

### ISSUE THREAD

**Issue by kyp44** [mealie-recipes/mealie#4511]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Paprika recipe migration not working on my self-hosted app. When submitting, the migration the working bar shows up top just for a split-second but then nothing happens. The migration does not show in the list below and nothing is imported. If I instead upload some garbage zip file, it uploads correctly and shows as failed in the list below. The problem only occurs for an actual Paprika export.

The migration works completely fine on the demo site with the identical zip file, both are using the nightly channel, though they do have different commit hashes. Comparing the **Site Setting** screens between the demo site and mine, they are identical except for the _Demo Status_ and the _Default Group_ ("Home" on mine and "home" on the demo site).

I am hoping that this is something easy that I am doing wrong or bad setting in my local deployment or something. I just need this to work once so I can migrate without tedious recipe copying.

### Steps to Reproduce

1. Login
2. Go to migration screen
3. Select Paprika Recipe Manager from the drop-down
4. Select exported zip file (renamed from a `.paprikarecipes` file)
5. Press submit

### Please provide relevant logs

The log does not appear to emit any useful messages when the error occurs.

### Mealie Version

Docker channel: `nightly`
Build tag: `dbbbe06a23260be753d4cca663d1e320efbd5dea`

### Deployment

Docker (Linux)

### Additional Deployment Details

Here is the relevant section of my docker compose file:
```yaml
# Recipe manager                                                                                                                                                                      
  mealie:
    image: ghcr.io/mealie-recipes/mealie:nightly
    container_name: mealie
    restart: always

    ports:
        - "9925:9000" #                                                                                                                                                                 
    deploy:
      resources:
        limits:
          memory: 1000M #                                                                                                                                                               
    volumes:
      - ./mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here                                                                                                                                                  
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: America/New York
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: (redacted)
```
