### ISSUE TITLE
[BUG] - Unable to Docker Compose

### ISSUE THREAD

**Issue by Aether0Pneuma** [mealie-recipes/mealie#4723]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Tried to deploy via compose, got an error with default yaml in repo

### Steps to Reproduce

Docking compose

### Please provide relevant logs

```
Deployment error
Failed to deploy a stack: mealie Pulling mealie Warning pull access denied for mealie, repository does not exist or may require 'docker login': denied: requested access to the resource is denied resolve : lstat /data/compose/docker: no such file or directory
```

Compose 

```
services:
  mealie:
    container_name: mealie
    image: mealie:dev
    build:
      context: ../
      target: production
      dockerfile: ./docker/Dockerfile
    restart: always
    volumes:
      - mealie-data:/app/data/
    ports:
      - 9091:9000
    environment:
      ALLOW_SIGNUP: "false"
      LOG_LEVEL: "DEBUG"

      DB_ENGINE: sqlite # Optional: 'sqlite', 'postgres'
      # =====================================
      # Postgres Config
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: mealie
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mealie
      # =====================================
      # Email Configuration
      # SMTP_HOST=
      # SMTP_PORT=587
      # SMTP_FROM_NAME=Mealie
      # SMTP_AUTH_STRATEGY=TLS # Options: 'TLS', 'SSL', 'NONE'
      # SMTP_FROM_EMAIL=
      # SMTP_USER=
      # SMTP_PASSWORD=

volumes:
  mealie-data:
    driver: local
```

### Deployment

Docker (Linux)
