### ISSUE TITLE
[BUG] - Cannot login after initialization 2.4.1

### ISSUE THREAD

**Issue by wieczyk** [mealie-recipes/mealie#4807]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I just setup mealie and it does not work. I cannot login with default credentials. In the UI I see notification that I cannot login. I do not see any error in logs although I have enabled debug logs.

In the database I see that 'MyPassword' is valid password. 

### Steps to Reproduce

Just run it using docker compose

```
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.4.1 #
    container_name: mealie
    restart: always
    #ports:
    #  - 9925:9000 #
    deploy:
      resources:
        limits:
          memory: 1000M #
    volumes:
      - ./mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: Europe/Warsaw
      BASE_URL: my public url
      LOG_LEVEL: debug
    networks:
      - public_http
networks:
  public_http:
    external: true
```

### Please provide relevant logs

```
mealie  | INFO     2024-12-31T23:57:12 - [127.0.0.1:34424] 200 OK "GET /api/app/about HTTP/1.1"
mealie  | DEBUG    2024-12-31T23:57:21 - Calling on_part_begin with no data
mealie  | DEBUG    2024-12-31T23:57:21 - Calling on_header_field with data[61:80]
mealie  | DEBUG    2024-12-31T23:57:21 - Calling on_header_value with data[82:108]
mealie  | DEBUG    2024-12-31T23:57:21 - Calling on_header_end with no data
mealie  | DEBUG    2024-12-31T23:57:21 - Calling on_headers_finished with no data
mealie  | DEBUG    2024-12-31T23:57:21 - Calling on_part_data with data[112:132]
mealie  | DEBUG    2024-12-31T23:57:21 - Calling on_part_end with no data
mealie  | DEBUG    2024-12-31T23:57:21 - Calling on_part_begin with no data
mealie  | DEBUG    2024-12-31T23:57:21 - Calling on_header_field with data[195:214]
mealie  | DEBUG    2024-12-31T23:57:21 - Calling on_header_value with data[216:242]
mealie  | DEBUG    2024-12-31T23:57:21 - Calling on_header_end with no data
mealie  | DEBUG    2024-12-31T23:57:21 - Calling on_headers_finished with no data
mealie  | DEBUG    2024-12-31T23:57:21 - Calling on_part_data with data[246:256]
mealie  | DEBUG    2024-12-31T23:57:21 - Calling on_part_end with no data
mealie  | DEBUG    2024-12-31T23:57:21 - Calling on_part_begin with no data
mealie  | DEBUG    2024-12-31T23:57:21 - Calling on_header_field with data[319:338]
mealie  | DEBUG    2024-12-31T23:57:21 - Calling on_header_value with data[340:369]
mealie  | DEBUG    2024-12-31T23:57:21 - Calling on_header_end with no data
mealie  | DEBUG    2024-12-31T23:57:21 - Calling on_headers_finished with no data
mealie  | DEBUG    2024-12-31T23:57:21 - Calling on_part_data with data[373:378]
mealie  | DEBUG    2024-12-31T23:57:21 - Calling on_part_end with no data
mealie  | DEBUG    2024-12-31T23:57:21 - Calling on_end with no data
mealie  | INFO     2024-12-31T23:57:21 - [193.28.84.20:0] 200 OK "POST /api/auth/token HTTP/1.1"
```

### Mealie Version

2.4.1

### Deployment

Docker (Linux)

### Additional Deployment Details

sqlite> SELECT * FROM users;
2024-12-31 22:44:12.256370|2024-12-31 22:44:12.256378|be1150bb15ed4823974ed7c269e1cfe1|Change Me|admin|changeme@example.com|$2b$12$owFCmZpX8BmiBOFv6K/E7.CR6tpzlXEO5qCXHEsJXNSUD7SEtF8P2|1|1|855fb8b98d8741d8b012296741f34027|1234|1|1|1||0||MEALIE|b4bef24849304f2785cfea350f17676a|1

**Comment by wieczyk** [comment]
I see the problem is another place. I have configured nginx proxy to require a password to access mealie virtual host. It seems to be totally incompatible with mealie. How to fix it? I want to have authentication on the nginx level.

**Comment by rwarner** [comment]
I was having a similar issue getting this started but I ended up needing to add in, due to my other containers setup running in the top level docker-compose file.

```
services:
  mealie:
    network_mode: host 
```

Might be worth removing, and trying that instead of this:

```
    networks:
      - public_http
networks:
  public_http:
    external: true
```

Also double check 

- Your `./mealie-data` directory is getting created with your appropriate `PUID`/`PGID`
- You're accessing port <ip>:9925
