### ISSUE TITLE
[BUG] - Docker High Idle CPU Usage from Health Checks

### ISSUE THREAD

**Issue by guicattani** [mealie-recipes/mealie#4844]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Docker health checks are making the idle CPU usage sit around 4%. Changing it to something like 
```
    healthcheck:
      test: [ "CMD-SHELL", "echo 0" ]
      interval: 120000s
      retries: 5
      start_period: 30s
      timeout: 10s
```
Makes the usage negligible

![image](https://github.com/user-attachments/assets/fc8800c5-33de-4eda-922d-ef50c70e606e)

### Steps to Reproduce

1) Deploy mealie
2) Check CPU usage after it stabilizes

### Please provide relevant logs

None

### Mealie Version

v2.4.1

### Deployment

Docker (Linux)
