### ISSUE TITLE
[BUG] - HTML being sent to OpenAI even if the HTTP request fails

### ISSUE THREAD

**Issue by smileBeda** [mealie-recipes/mealie#5012]
### First Check

- [x] This is not a feature request.
- [x] I added a very descriptive title to this issue (title field is above this).
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the Mealie documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I enabled OpenAI by adding the `OPENAI_API_KEY` to the docker file `environment` section.
I restarted the service, and in the Mealie Settings it told me:
> OpenAI Ready
Not all OpenAI Values are configured. This can be ignored if you are not using OpenAI features.

So I also added `OPENAI_MODEL` (set to `gpt4-o`) `OPENAI_BASE_URL` (left empty as suggested).
Still the same message appears in the settings.

Checking in the logs I can see:
```
"OPENAI_BASE_URL": null,
mealie    |     "OPENAI_API_KEY": "*****",
mealie    |     "OPENAI_MODEL": "gpt-4o",
mealie    |     "OPENAI_CUSTOM_HEADERS": {},
mealie    |     "OPENAI_CUSTOM_PARAMS": {},
mealie    |     "OPENAI_ENABLE_IMAGE_SERVICES": true,
mealie    |     "OPENAI_WORKERS": 2,
mealie    |     "OPENAI_SEND_DATABASE_DATA": true,
mealie    |     "OPENAI_REQUEST_TIMEOUT": 60,
...
INFO     2025-02-03T14:55:58 - ------APP FEATURES------
mealie    | INFO     2025-02-03T14:55:58 - --------==SMTP==--------
mealie    | INFO     2025-02-03T14:55:58 - Enabled: False
mealie    | Reason: Missing required values for ['SMTP_HOST', 'SMTP_FROM_EMAIL']
mealie    | INFO     2025-02-03T14:55:58 - --------==LDAP==--------
mealie    | INFO     2025-02-03T14:55:58 - Enabled: False
mealie    | Reason: LDAP_AUTH_ENABLED is false
mealie    | INFO     2025-02-03T14:55:58 - --------==OIDC==--------
mealie    | INFO     2025-02-03T14:55:58 - Enabled: False
mealie    | Reason: OIDC_AUTH_ENABLED is false
mealie    | INFO     2025-02-03T14:55:58 - -------==OPENAI==-------
mealie    | INFO     2025-02-03T14:55:58 - Enabled: True
mealie    | INFO     2025-02-03T14:55:58 - ------------------------
mealie    | INFO     2025-02-03T14:55:58 - Daily tasks scheduled for 2025-02-04 02:45:00+00:00
mealie    | INFO     2025-02-03T14:55:58 - Application startup complete.
```

Everything seems fine... yet OpenAI is not working on the instance. The message persists, and trying to import an URL where no JSON is available, which should trigger a call to OpenAI, is still failing.
Creating recipe from image weirdly works.

Yet the DOC is clear:
> OpenAI Features

> The OpenAI Ingredient Parser can be used as an alternative to the NLP and Brute Force parsers. Simply choose the OpenAI parser while parsing ingredients ( v1.7.0)
> **When importing a recipe via URL, if the default recipe scraper is unable to read the recipe data from a webpage, the webpage contents will be parsed by OpenAI ( v1.9.0)**
> You can import an image of a written recipe, which is sent to OpenAI and imported into Mealie. The recipe can be hand-written or typed, as long as the text is in the picture. You can also optionally have OpenAI translate the recipe into your own language ( v1.12.0)

This does not appear to be working for me. 
The entire system was installed yesterday at latest version 2.5

This happens be it on localhost, direct IP or secure HTTPS via domain (which is proxied, as can be seen in the docker file)

### Steps to Reproduce

1) Install Mealie Docker
2) Make sure to pass OpenAI Key
3. Head to Settings and see the message about OpenAI not being ready, try to import a (failing/incompatible) URL and see the import failing. **Image import works**

### Please provide relevant logs

No errors whatsoever in the logs.

### Mealie Version

There is no such thing in Mealie Settings (build tag):
> Application Version
Your current version (null) does not match the latest release. Considering updating to the latest version (null).

However, I installed:
```
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.5.0
    container_name: mealie
    restart: always
    ports:
      - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - /media/redacted/Data1/meals/mealie:/app/data/
    environment:
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: redacted
      BASE_URL: https://redacted.com
      DB_ENGINE: postgres
      POSTGRES_USER: redacted
      POSTGRES_PASSWORD: redacted
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: redacted
      OPENAI_API_KEY: sk-proj-redacted-redacted
      OPENAI_MODEL: gpt-4o
      OPENAI_BASE_URL:
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      proxy:
        ipv4_address: redacted
      internal:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    volumes:
      - /media/redacted/Data1/meals/mealie-pg:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: redacted
      POSTGRES_PASSWORD: redacted
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - internal
networks:
  proxy:
    external: true
    name: npm_proxy
  internal:
    driver: bridge
```

### Deployment

Docker (Linux)
