### ISSUE TITLE
[BUG] - After update to v2.7.0, container won't run

### ISSUE THREAD

**Issue by jdmartin** [mealie-recipes/mealie#5126]
### First Check

- [x] This is not a feature request.
- [x] I added a very descriptive title to this issue (title field is above this).
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the Mealie documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Today, I pulled the latest (v2.7.0) version of the mealie container to update from my running v.2.6.0.  After startup, the service is unable to run.  The healthcheck reports: `/usr/local/bin/python: Error while finding module specification for 'mealie.scripts.healthcheck' (ModuleNotFoundError: No module named 'mealie') ` 

Unsurprisingly, the startup logs (see below) show that clients cannot access the site.

### Steps to Reproduce

1) Have a running v2.6.0 container
2) Stop the container
3) Pull the one tagged with `:latest` as of the time of writing
4) Run the new container with the same config as the previous one.

### Please provide relevant logs

```

Actions
    "BASE_URL": "http://localhost:8080",
    "STATIC_FILES": "/spa/static",
    "IS_DEMO": false,
    "HOST_IP": "*",
    "API_HOST": "0.0.0.0",
    "API_PORT": 9000,
    "API_DOCS": true,
    "TOKEN_TIME": 48,
    "GIT_COMMIT_HASH": "f0bbe796ce40ef32a4a00eecdfb0efe4eef9da07",
    "ALLOW_SIGNUP": false,
    "DAILY_SCHEDULE_TIME": "23:45",
    "SECURITY_MAX_LOGIN_ATTEMPTS": 5,
    "SECURITY_USER_LOCKOUT_TIME": 24,
    "DB_ENGINE": "sqlite",
    "DEFAULT_GROUP": "Home",
    "DEFAULT_HOUSEHOLD": "Family",
    "SMTP_HOST": null,
    "SMTP_PORT": "587",
    "SMTP_FROM_NAME": "Mealie",
    "SMTP_FROM_EMAIL": null,
    "SMTP_USER": null,
    "SMTP_PASSWORD": null,
    "SMTP_AUTH_STRATEGY": "TLS",
    "LDAP_AUTH_ENABLED": false,
    "LDAP_SERVER_URL": null,
    "LDAP_TLS_INSECURE": false,
    "LDAP_TLS_CACERTFILE": null,
    "LDAP_ENABLE_STARTTLS": false,
    "LDAP_BASE_DN": null,
    "LDAP_QUERY_BIND": null,
    "LDAP_QUERY_PASSWORD": null,
    "LDAP_USER_FILTER": null,
    "LDAP_ADMIN_FILTER": null,
    "LDAP_ID_ATTRIBUTE": "uid",
    "LDAP_MAIL_ATTRIBUTE": "mail",
    "LDAP_NAME_ATTRIBUTE": "name",
    "OIDC_AUTH_ENABLED": false,
    "OIDC_CLIENT_ID": null,
    "OIDC_CLIENT_SECRET": null,
    "OIDC_CONFIGURATION_URL": null,
    "OIDC_SIGNUP_ENABLED": true,
    "OIDC_USER_GROUP": null,
    "OIDC_ADMIN_GROUP": null,
    "OIDC_AUTO_REDIRECT": false,
    "OIDC_PROVIDER_NAME": "OAuth",
    "OIDC_REMEMBER_ME": false,
    "OIDC_USER_CLAIM": "email",
    "OIDC_NAME_CLAIM": "name",
    "OIDC_GROUPS_CLAIM": "groups",
    "OIDC_SCOPES_OVERRIDE": null,
    "OIDC_TLS_CACERTFILE": null,
    "OPENAI_BASE_URL": null,
    "OPENAI_API_KEY": null,
    "OPENAI_MODEL": "gpt-4o",
    "OPENAI_CUSTOM_HEADERS": {},
    "OPENAI_CUSTOM_PARAMS": {},
    "OPENAI_ENABLE_IMAGE_SERVICES": true,
    "OPENAI_WORKERS": 2,
    "OPENAI_SEND_DATABASE_DATA": true,
    "OPENAI_REQUEST_TIMEOUT": 60,
    "WORKER_PER_CORE": 1,
    "UVICORN_WORKERS": 1,
    "TLS_CERTIFICATE_PATH": null,
    "TLS_PRIVATE_KEY_PATH": null
}

INFO     2025-02-28T00:25:00 - ------APP FEATURES------
INFO     2025-02-28T00:25:00 - --------==SMTP==--------
INFO     2025-02-28T00:25:00 - Enabled: False
Reason: Missing required values for ['SMTP_HOST', 'SMTP_FROM_EMAIL']
INFO     2025-02-28T00:25:00 - --------==LDAP==--------
INFO     2025-02-28T00:25:00 - Enabled: False
Reason: LDAP_AUTH_ENABLED is false
INFO     2025-02-28T00:25:00 - --------==OIDC==--------
INFO     2025-02-28T00:25:00 - Enabled: False
Reason: OIDC_AUTH_ENABLED is false
INFO     2025-02-28T00:25:00 - -------==OPENAI==-------
INFO     2025-02-28T00:25:00 - Enabled: False
Reason: OPENAI_API_KEY is not set
INFO     2025-02-28T00:25:00 - ------------------------
INFO     2025-02-28T00:25:00 - Daily tasks scheduled for 2025-02-28 23:45:00+00:00
INFO     2025-02-28T00:25:00 - Application startup complete.
INFO     2025-02-28T00:25:00 - Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
INFO     2025-02-28T00:25:25 - [xxx] 404 Not Found "GET / HTTP/1.1"
INFO     2025-02-28T00:25:25 - [xxx] 404 Not Found "GET /favicon.ico HTTP/1.1"
INFO     2025-02-28T00:25:26 - [xxx] 404 Not Found "GET / HTTP/1.1"
INFO     2025-02-28T00:25:26 - [xxx] 404 Not Found "GET /sw.js HTTP/1.1"
```

### Mealie Version

UI not working. Upgrading from v2.6.0 to v2.7.0 by referencing the `:latest` container on Docker Hub.

### Deployment

Docker (Synology)

**Comment by michael-genson** [comment]
Someone reported a similar issue on Discord; can you post your docker compose?

It may be as simple as tearing the container down, deleting the image, then rebuilding from scratch

**Comment by jdmartin** [comment]
Thanks for the quick response!  I'll try the remedy you suggest.  In the meantime, as I built this with Portainer, I've used docker-autocompose to export the docker compose from the container.  The result is:

```
networks:
  internet:
    external: true
    name: "internet"

services:
  recipes:
    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"
    container_name: "recipes"
    dns:
      - "9.9.9.9"
      - "1.1.1.1"
    entrypoint:
      - "/app/run.sh"
    environment:
      - "PATH=/opt/poetry/bin:/opt/pysetup/.venv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "LANG=C.UTF-8"
      - "GPG_KEY=[...]"
      - "PYTHON_VERSION=3.10.13"
      - "PYTHON_SHA256=aab0950817735172601879872d937c1e4928a57c409ae02369ec3d91dccebe79"
      - "MEALIE_HOME=/app"
      - "PYTHONUNBUFFERED=1"
      - "PYTHONDONTWRITEBYTECODE=1"
      - "PIP_NO_CACHE_DIR=off"
      - "PIP_DISABLE_PIP_VERSION_CHECK=on"
      - "PIP_DEFAULT_TIMEOUT=100"
      - "VENV_PATH=/opt/pysetup/.venv"
      - "PRODUCTION=true"
      - "TESTING=false"
      - "GIT_COMMIT_HASH=f0bbe796ce40ef32a4a00eecdfb0efe4eef9da07"
      - "LD_LIBRARY_PATH=/usr/local/lib"
      - "APP_PORT=9000"
      - "HOST=0.0.0.0"
      - "POETRY_HOME=/opt/poetry"
      - "POETRY_VIRTUALENVS_IN_PROJECT=true"
      - "POETRY_NO_INTERACTION=1"
      - "PYSETUP_PATH=/opt/pysetup"
      - "STATIC_FILES=/spa/static"
      - "PYTHON_PIP_VERSION=23.0.1"
      - "PYTHON_SETUPTOOLS_VERSION=65.5.1"
      - "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/049c52c665e8c5fd1751f942316e0a5c777d304f/public/get-pip.py"
      - "PYTHON_GET_PIP_SHA256=7cfd4bdc4d475ea971f1c0710a5953bcc704d171f83c797b9529d9974502fcc6"
    hostname: "1adf48b9159e"
    image: "docker.io/hkotel/mealie:latest"
    ipc: "private"
    labels:
      org.opencontainers.image.source: "https://github.com/mealie-recipes/mealie"
    logging:
      driver: "db"
      options: {}
    networks:
      - "internet"
    ports:
      - "3017:9000/tcp"
    restart: "unless-stopped"
    volumes:
      - "/volume1/docker/mealie:/app/data"
    working_dir: "/"
version: "3.6"
```
