### ISSUE TITLE
[BUG] - SMTP fails with timeout

### ISSUE THREAD

**Issue by dvnkln** [mealie-recipes/mealie#5341]
### First Check

- [x] This is not a feature request.
- [x] I added a very descriptive title to this issue (title field is above this).
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the Mealie documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Fresh install. Trying to setup email and test it fails with a timeout. It works with the exact same settings in multiple other applications.

![Image](https://github.com/user-attachments/assets/8178e516-5eb5-4118-a9bf-f4fa0e8111c1)

I made sure:
- the smtp is reachable on the docker host
- the smtp dns is resolvable on the Mealie container
- the credentials work (currently using them in other applications)
- the credentials are passed correctly to Mealie

My SMTP provider is Strato.
I'm currently using secrets to pass the credentials and made sure the container is able to read them.
Nevertheless i tried passing them as plaintext directly in the compose file which didn't help sadly.

### Steps to Reproduce

1) Deploy your container
2) Make sure you set the SMTP EV
3) Go to Site Settings -> Test Email

Here's my compose:
```
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest # 
    container_name: mealie
    restart: unless-stopped
    ports:
        - "9925:9000" # 
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - data:/app/data/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
      BASE_URL: https://mealie.my.domain
      DEFAULT_HOUSEHOLD: HD
      LOG_LEVEL: debug
      SMTP_Host: smtp.strato.de
      SMTP_Port: 465
      SMTP_FROM_NAME: Mealie
      SMTP_AUTH_STRATEGY: TLS
      SMTP_FROM_EMAIL: notify@my.domain
      SMTP_USER_FILE: /run/secrets/smtp_mydomain_user
      SMTP_PASSWORD_FILE: /run/secrets/smtp_mydomain_pass
    secrets:
      - smtp_mydomain_user
      - smtp_mydomain_pass

secrets:
   smtp_mydomain_user:
     file: /some/path/smtp_mydomain_user
   smtp_mydomain_pass:
     file: /some/path/smtp_mydomain_pass

volumes:
  data:
```

### Please provide relevant logs

All logs occuring while hitting the test. Debug didn't provide anything more.

```
INFO     2025-04-13T17:26:02 - [192.168.XXX.XX:0] 200 OK "GET /api/admin/about HTTP/1.1"
INFO     2025-04-13T17:26:02 - [192.168.XXX.XX:0] 200 OK "GET /api/admin/about/check HTTP/1.1"
ERROR    2025-04-13T17:26:17 - Connection unexpectedly closed: timed out
ERROR    2025-04-13T17:26:17 - Connection unexpectedly closed: timed out
INFO     2025-04-13T17:26:17 - [192.168.XXX.XX:0] 200 OK "POST /api/admin/email HTTP/1.1"
INFO     2025-04-13T17:26:27 - [127.0.0.1:33136] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2025-04-13T17:26:58 - [127.0.0.1:58008] 200 OK "GET /api/app/about HTTP/1.1"
ERROR    2025-04-13T17:27:19 - Connection unexpectedly closed: timed out
ERROR    2025-04-13T17:27:19 - Connection unexpectedly closed: timed out
INFO     2025-04-13T17:27:19 - [192.168.XXX.XX:0] 200 OK "POST /api/admin/email HTTP/1.1"
INFO     2025-04-13T17:27:28 - [127.0.0.1:53488] 200 OK "GET /api/app/about HTTP/1.1"
```

Mealie seems to be reading the settings correctly.

```
"SMTP_HOST": "smtp.strato.de",
"SMTP_PORT": "465",
"SMTP_FROM_NAME": "Mealie",
"SMTP_FROM_EMAIL": "notify@my.domain",
"SMTP_USER": "*****",
"SMTP_PASSWORD": "*****",
"SMTP_AUTH_STRATEGY": "TLS",
```

### Mealie Version

Version v2.8.0
Build [2deb9c276cfff6b1aff473776dd327110f2eb55b](https://github.com/mealie-recipes/mealie/commit/2deb9c276cfff6b1aff473776dd327110f2eb55b)

### Deployment

Docker (Linux)

### Additional Deployment Details

Portainer - Compose.
