### ISSUE TITLE
[SCRAPER] - Issue scrapping recipes created from AI

### ISSUE THREAD

**Issue by GerardPolloRebozado** [mealie-recipes/mealie#5427]
### First Check

- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I have verified that this issue _is not_ related to the underlying library
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers) by **1)** checking
the [debugger](https://demo.mealie.io/g/home/r/create/debug) and data is returned, **2)**
verifying that there _are_ errors in the log related to application level code, or
**3)** verified that the site provides recipe data, or is otherwise supported by
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers)

- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/)

### Please provide 1-5 example URLs that are having errors

https://www.instagram.com/p/DEu2rV7sT4T/

### Please provide your logs for the Mealie container `docker logs <container-id> > mealie.logs`

It doesnt show any errors as the recipe is being created

I'm developing an application that converts social media videos into recipes. I’m using Mealie to parse the generated HTML from these videos, but in many cases, Mealie doesn’t extract the recipe information properly, ingredients, instructions, and images are often missing or misinterpreted, even when the HTML structure is relatively clean.

Here’s an example of a recipe I'm testing:
```

<h1>Receta de Cookies de Lotus</h1>

<p>Ingredientes:</p>
<ul>
  <li>115 g de mantequilla</li>
  <li>80 g de azúcar moreno</li>
  <li>70 g de azúcar granulada</li>
  <li>1 huevo</li>
  <li>160 g de harina</li>
  <li>3 g de bicarbonato de sodio</li>
  <li>Una pizca de sal</li>
  <li>225 g de chocolate blanco</li>
  <li>Crema de Lotus</li>
</ul>

<h2>Paso a Paso:</h2>
<ol>
  <li>Precalienta el horno a 180°C y prepara una bandeja con papel de horno.</li>
  <li>En un bol grande, bate la mantequilla con el azúcar moreno y el azúcar hasta que la mezcla esté suave y cremosa.</li>
  <li>Añade el huevo y mezcla hasta que todo esté bien integrado.</li>
  <li>Añade la harina, el bicarbonato y la sal hasta que se integre.</li>
  <li>Incorpora los chips de chocolate blanco.</li>
  <li>Forma bolitas con la masa y colócalas en la bandeja para hornear, dejando espacio entre ellas, haz un agujerito con el dedo y ponle crema de lotus.</li>
  <li>Hornea durante 10-12 minutos o hasta que los bordes estén dorados. Los centros pueden estar ligeramente blandos, pero se endurecerán mientras se enfrían.</li>
</ol>

<p><img src="https://d.rapidcdn.app/thumb?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJodHRwczovL3Njb250ZW50LXZpZTEtMS5jZG5pbnN0YWdyYW0uY29tL3YvdDUxLjI4ODUtMTUvNDczMTM4MTY2XzU1Nzk1Mzg3NzI0MzA2M184MDQzMTgyMTAzOTg1MjAxNDM0X24uanBnP3N0cD1jMC4yNDguNjQwLjY0MGFfZHN0LWpwZ19lMTVfdHQ2Jl9uY19odD1zY29udGVudC12a
WUxLTEuY2RuaW5zdGFncmFtLmNvbSZfbmNfY2F0PTExMSZfbmNfb2M9UTZjWjJRSFJiWHloU09ENjAydVhOTG02VS1WX2VlQnRJWjhTSnB0UWViLW43cmEwVFdSVGhKSGFOai1ubEZSWExuMHhUbGcmX25jX29oYz1hQ0xvME5mS2p4a1E3a052d0duZk9HeiZfbmNfZ2lkPWFzXzd2UE5QMFAxVHRMVXlNczQzSXcmZWRtPUFQczE3Q1VCQUFBQSZjY2I9Ny01Jm9oPTAwX0FmRW1VcjlFNy1ZcTNsb194Rmt5TjdGeFprV0RJRU96RXp1SlN0aEh0c3RQTEEmb2U9NjgxRDkxOTkmX25jX3NpZD0xMGQxM2IiLCJoZWFkZXJzIjp7InVzZXItYWdlbnQiOiJUZWxlZ3JhbUJvdCAobGlrZSBUd2l0dGVyQm90KSJ9LCJpYXQiOjE3NDYzNzk4MDh9.ir3xUSkUXLV4gvtaVtSjD-E0-SOLoHMpbx5eR_5InGs" alt=" Cookies de Lotus"></p>

<p>Origen: <a href="https://www.instagram.com/p/DEu2rV7sT4T/">https://www.instagram.com/p/DEu2rV7sT4T/</a></p>
```
I already did an [issue ](https://github.com/hhursev/recipe-scrapers/issues/1565#issuecomment-2860163413)on the library

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Please provide your docker compose and your logs. If you're using the OpenAI integration, we need to see what went wrong to help you. If you're not using the OpenAI integration, we can't parse non-standard recipe data.

**Comment by GerardPolloRebozado** [comment]
```
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: always
    ports:
      - 9925:9000
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - ./data:/app/data/
    environment:
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: Europe/Madrid
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://comida.pollorebozado.com
      # Database Settings
      DB_ENGINE: postgres
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: D@rvvEU&LTNHU413ZIrE
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mealie
      OPENAI_BASE_URL: https://api.groq.com/openai/v1
      OPENAI_API_KEY: xxxx
      OPENAI_ENABLE_IMAGE_SERVICES: false
      OPENAI_MODEL: llama3-8b-8192
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - backup=true
```
Im currently using groq because its cheaper but the same issue happens when using open ai

**Comment by GerardPolloRebozado** [comment]
```
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: always
    ports:
      - 9925:9000
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - ./data:/app/data/
    environment:
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: Europe/Madrid
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: xxxx
      # Database Settings
      DB_ENGINE: postgres
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: xxxx
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mealie
      OPENAI_BASE_URL: https://api.groq.com/openai/v1
      OPENAI_API_KEY: xxxx
      OPENAI_ENABLE_IMAGE_SERVICES: false
      OPENAI_MODEL: llama3-8b-8192
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - backup=true
```
Im currently using groq because its cheaper but the same issue happens when using open ai
