### ISSUE TITLE
[BUG] - Initialisation stuck on Downloading required NLTK resource

### ISSUE THREAD

**Issue by GwinGit** [mealie-recipes/mealie#5541]
### First Check

- [x] This is not a feature request.
- [x] I added a very descriptive title to this issue (title field is above this).
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the Mealie documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When first starting mealie it doesn't progress beyond `Downloading required NLTK resource: averaged_perceptron_tagger_eng`, even after multiple days of waiting. The web UI is not reachable and the container is shown as unhealthy.

### Steps to Reproduce

1) create a new empty folder and `cd` inside
2) create `docker-compose.yaml` with the recommended [SQLite Config](https://docs.mealie.io/documentation/getting-started/installation/sqlite/)
3) change timezone and base url
4) start with `docker compose up -d`

### Please provide relevant logs

```
$ docker compose logs
mealie  | Switching to dedicated user
mealie  | 
mealie  |         User uid:    1000
mealie  |         User gid:    1000
mealie  |         
mealie  | DEBUG    2025-06-16T17:47:16 - Language set to en
mealie  | Downloading required NLTK resource: averaged_perceptron_tagger_eng
```

### Mealie Version

v2.8.0

### Deployment

Docker (Linux)

### Additional Deployment Details

`docker-compose.yaml`:

```
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.8.0
    container_name: mealie
    restart: always
    ports:
        - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
      BASE_URL: http://123.4.567.890
      LOG_LEVEL: debug

volumes:
  mealie-data:
```
