### ISSUE TITLE
Issue with nginx Basic Auth

### ISSUE THREAD

**Issue by patsa** [mealie-recipes/mealie#690]
Hello,

I installed mealie using docker-compose on my server. My docker-compose.yml looks as follows:

```
version: "3.1"
services:
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    restart: always
    ports:
      - 127.0.0.1:9925:80
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin

      # Default Recipe Settings
      RECIPE_PUBLIC: 'true'
      RECIPE_SHOW_NUTRITION: 'true'
      RECIPE_SHOW_ASSETS: 'true'
      RECIPE_LANDSCAPE_VIEW: 'true'
      RECIPE_DISABLE_COMMENTS: 'false'
      RECIPE_DISABLE_AMOUNT: 'false'

      DEFAULT_EMAIL: myemail
      API_DOCS: 'false'
      TOKEN_TIME: 24
      # Gunicorn
      WEB_CONCURRENCY: 2
      # WORKERS_PER_CORE: 0.5
      # MAX_WORKERS: 8
    volumes:
      - ./mealie/data/:/app/data
```

So far so good. It runs as expected on port 9925. Although it is important to mention, that without the 127.0.0.1: before 9925, docker has the unpleasant habit of exposing the port to the outside world even though services like ufw should stop this behaviour. As it turns out, docker overwrites the iptables and bypasses ufw by doing so. However by writing the host in front of the local port, the port stays closed. At least to my knowledge. 

But now to my problem:

As I didn't want to fiddle around with SWAG (my server already has nginx up and running), I created a conf file for mealie, in which I use a reverse proxy to direct calls to my domain to the mealie container:

```
server {

    server_name example.com;

    access_log /var/log/... combined buffer=64k flush=5m if=$loggable;
    error_log /var/log/...;

    location / {
       proxy_set_header Authorization "";
       auth_basic            "Basic Auth";
       auth_basic_user_file  "/location/of/my/password/file";
       proxy_pass http://localhost:9925;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header Accept-Encoding "";
       proxy_read_timeout 90;
    }

    ... 
    # some more Let's Encrypt stuff
```

The basic auth works like a charm for the frontend and the normal statically served elements. But as soon as an URL with the word 'api' in it is requested, it returns 401, as it is obviously also trying to use basic auth, but can't get any credentials. 

Even though this is only partially related to Mealie itself, I'm sure I'm not the only one interested in a solution to this problem, as the general authentication layer is only supposed to come around version 1.0 and I don't want everyone to be able to see my recipes in the WWW.

Does anyone have any idea how to solve the problem? I guess it will involve changing the Caddyfile in some way.

tldr; When using native nginx with basic authentication, all API requests return error 401.

Thanks in advance to everyone!

Best regards, 
Patrick
