### ISSUE TITLE
Unprocessable entity

### ISSUE THREAD

**Issue by loranger** [mealie-recipes/mealie#696]
I cannot upload any asset (wheras I can define an image for each recipe)

**Steps To Reproduce**
1. I use mealie on docker
2. I open a recipe
3. I click on edit button
4. I scroll down to assets
5. I click on + button
6. I select File or Image
7. I click on upload button and choose a jpg (70k file, 600x600)
8. I click on create button
9. I get an "Unprocessable entity" alert error and no file were uploaded

**Expected behavior**
I would expect the asset is uploaded and available for download

**Actual Behavior**
`Unprocessable entity` error is displayed on recipe editor and here is the docker-compose ouput for this action :
`mealie-mealie | 172.18.0.8:0 - "POST /api/recipes/gyozas/assets HTTP/1.1" 422`

**Device Information (please complete the following information):**
 - OS: Debian 10
 - Deployment: docker-compose
 - Browser: Firefox
 - Version: 94

**Additional context**

<details>
<summary>
docker-compose.yml
</summary>

```yaml
version: "3.1"
services:
  mealie:
    container_name: ${APP_PROJECT}-mealie
    image: hkotel/mealie:latest
    labels:
      - "traefik.http.routers.${APP_PROJECT}-web.entrypoints=http"
      - "traefik.http.routers.${APP_PROJECT}-web.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.${APP_PROJECT}-web.middlewares=redirect-to-https@file"
      - "traefik.http.routers.${APP_PROJECT}-websecure.entrypoints=https"
      - "traefik.http.routers.${APP_PROJECT}-websecure.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.${APP_PROJECT}-websecure.tls=true"
      - "traefik.http.routers.${APP_PROJECT}-websecure.tls.certresolver=letsencrypt"
      - "com.centurylinklabs.watchtower.enable=true"
    env_file:
      - .env
    restart: always
    # ports:
    #   - 9925:80
    volumes:
      - ./.docker/data/:/app/data
      # - ./.docker/config/caddy.conf:/app/Caddyfile

networks:
  default:
    external:
      name: my_external_traefik_network
```

</details>

<details>
<summary>
.env
</summary>

```env
APP_PROJECT=mealie
APP_URL=mealie.my-domain.tld

DB_TYPE=sqlite
TZ=Europe/Paris

PUID=1000
PGID=1000
```

</details>

Did I miss something ?
(Anyway, thank you so much for this awesome software 👍🏻)
