### ISSUE TITLE
Backups take all space available on my hard-drive

### ISSUE THREAD

**Issue by bemble** [mealie-recipes/mealie#773]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

After running `mealie` on Docker for nearly 2 months with only 1 recipes, the backup folder take 440GB.
How to avoid this situation? Is it possible to set the maximum number of backups or disable it (I manage my backup system-wide and not per app)?

### Deployment

Docker (Synology)

### Deployment Details

docker-compose.yml:
```yml
  mealie:
    image: hkotel/mealie:latest
    container_name: mealie
    restart: unless-stopped
    ports:
      - ${PORT_MEALIE}:80
    volumes:
      - "${PWD}/mealie:/app/data"
    environment:
      - PUID=${DOCKER_UID}
      - PGID=${DOCKER_GID}
      - TZ=${TIMEZONE}
      - RECIPE_PUBLIC=true
      - RECIPE_SHOW_NUTRITION=true
      - RECIPE_SHOW_ASSETS=true
      - RECIPE_LANDSCAPE_VIEW=true
      - RECIPE_DISABLE_COMMENTS=true
      - RECIPE_DISABLE_AMOUNT=true
      - WEB_CONCURRENCY=2
```

### Mealie Version

v0.5.3
