### ISSUE TITLE
POSTRES_PASSWORD treated as part of POSTGRES_SERVER.

### ISSUE THREAD

**Issue by cinderblockgames** [mealie-recipes/mealie#895]
### First Check

- [x] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When I specify POSTGRES_PASSWORD, it is treated as part of POSTGRES_SERVER:

.env clip:

    POSTGRES_SERVER=db-01
    POSTGRES_PASSWORD=mypasswordhere

Logs:

    sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "mypasswordhere@db-01" to address: Name or service not known,
    (Background on this error at: https://sqlalche.me/e/14/e3q8)

If I don't provide POSTGRES_PASSWORD, mealie connects to the postgres instance (though obviously doesn't successfully authenticate).

### Deployment

Docker (Linux)

### Mealie Version

v0.5.4

**Comment by cinderblockgames** [comment]
Okay, assuming the issue might be it not adding the user as well?  Should be `user:password@host`, right?

    POSTGRES_USER=mealie

**Comment by hay-kot** [comment]
Can you provide your docker-compose and/or all your ENV variables? You'll need more than just those two to connect to Postgres.

**Comment by cinderblockgames** [comment]
Sure!

docker-compose.yaml:

```
Version: '3.8'

services:

  mealie:
    image: 'hkotel/mealie:v0.5.4'
    env_file: .env
    volumes:
      - '/run/homelab/mealie/data:/app/data'
    networks:
      - traefik
      - mealie-internet
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - 'traefik.enable=true'
        - 'traefik.docker.network=traefik'
        - 'traefik.http.routers.mealie.rule=Host(`mealie.[redacted]`)'
        - 'traefik.http.routers.mealie.entrypoints=web-secure'
        - 'traefik.http.routers.mealie.tls'
        - 'traefik.http.services.mealie.loadbalancer.server.port=80'

networks:
  traefik:
    external: true
  mealie-internet:
    external: true
```

.env:

```
PUID=1000
PGID=1000
TZ=America/New_York

DB_ENGINE=postgres
POSTGRES_USER=mealie
POSTGRES_PASSWORD=[redacted]
POSTGRES_SERVER=db-01
POSTGRES_PORT=5432
POSTGRES_DB=mealie

RECIPE_PUBLIC=true
RECIPE_SHOW_NUTRITION=true
RECIPE_SHOW_ASSETS=true
RECIPE_LANDSCAPE_VIEW=true
RECIPE_DISABLE_COMMENTS=false
RECIPE_DISABLE_AMOUNT=false

DEFAULT_GROUP=Me+Wife
DEFAULT_EMAIL=[redacted]
DEFAULT_PASSWORD=[redacted]
BASE_URL=https://mealie.[redacted]
```
