### ISSUE TITLE
Home Assistant returns no food name using API

### ISSUE THREAD

**Issue by lasharor** [mealie-recipes/mealie#940]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I copy pasted this in my config:

```
sensor:
  - platform: rest
    resource: http://url/api/meal-plans/today
    method: GET
    name: Meal Today
    headers:
      Authorization: 'key'
    value_template: "{{value_json.name }}"
    json_attributes:
      - slug
```

Returns no name in the entities overview. When checking via developer options it returns: UndefinedError: 'value_json' is undefined

logs:

`WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'name' when rendering '{{value_json.name }}'`

Confirmed that API works by using an API testing tool 

### Deployment

Docker (Linux)

### Deployment Details

Latest docker image

### Mealie Version

v0.5.4
